// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbortSequenceT struct {
	Id uint32 `json:"id"`
}

func (t *AbortSequenceT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	AbortSequenceStart(builder)
	AbortSequenceAddId(builder, t.Id)
	return AbortSequenceEnd(builder)
}

func (rcv *AbortSequence) UnPackTo(t *AbortSequenceT) {
	t.Id = rcv.Id()
}

func (rcv *AbortSequence) UnPack() *AbortSequenceT {
	if rcv == nil {
		return nil
	}
	t := &AbortSequenceT{}
	rcv.UnPackTo(t)
	return t
}

type AbortSequence struct {
	_tab flatbuffers.Table
}

func GetRootAsAbortSequence(buf []byte, offset flatbuffers.UOffsetT) *AbortSequence {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbortSequence{}
	x.Init(buf, n+offset)
	return x
}

func FinishAbortSequenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAbortSequence(buf []byte, offset flatbuffers.UOffsetT) *AbortSequence {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AbortSequence{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAbortSequenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AbortSequence) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbortSequence) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AbortSequence) Id() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AbortSequence) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func AbortSequenceStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AbortSequenceAddId(builder *flatbuffers.Builder, id uint32) {
	builder.PrependUint32Slot(0, id, 0)
}
func AbortSequenceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
