// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BatchT struct {
	Entries []*CommandT `json:"entries"`
}

func (t *BatchT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	entriesOffset := flatbuffers.UOffsetT(0)
	if t.Entries != nil {
		entriesLength := len(t.Entries)
		entriesOffsets := make([]flatbuffers.UOffsetT, entriesLength)
		for j := 0; j < entriesLength; j++ {
			entriesOffsets[j] = t.Entries[j].Pack(builder)
		}
		BatchStartEntriesVector(builder, entriesLength)
		for j := entriesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(entriesOffsets[j])
		}
		entriesOffset = builder.EndVector(entriesLength)
	}
	BatchStart(builder)
	BatchAddEntries(builder, entriesOffset)
	return BatchEnd(builder)
}

func (rcv *Batch) UnPackTo(t *BatchT) {
	entriesLength := rcv.EntriesLength()
	t.Entries = make([]*CommandT, entriesLength)
	for j := 0; j < entriesLength; j++ {
		x := Command{}
		rcv.Entries(&x, j)
		t.Entries[j] = x.UnPack()
	}
}

func (rcv *Batch) UnPack() *BatchT {
	if rcv == nil {
		return nil
	}
	t := &BatchT{}
	rcv.UnPackTo(t)
	return t
}

type Batch struct {
	_tab flatbuffers.Table
}

func GetRootAsBatch(buf []byte, offset flatbuffers.UOffsetT) *Batch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Batch{}
	x.Init(buf, n+offset)
	return x
}

func FinishBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBatch(buf []byte, offset flatbuffers.UOffsetT) *Batch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Batch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Batch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Batch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Batch) Entries(obj *Command, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Batch) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BatchAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(entries), 0)
}
func BatchStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
