// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandBatchT struct {
	Timestamp uint64 `json:"timestamp"`
	ImmediateCommands []*CommandT `json:"immediate_commands"`
	Sequences []*SequenceT `json:"sequences"`
	AbortAll bool `json:"abort_all"`
}

func (t *CommandBatchT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	immediateCommandsOffset := flatbuffers.UOffsetT(0)
	if t.ImmediateCommands != nil {
		immediateCommandsLength := len(t.ImmediateCommands)
		immediateCommandsOffsets := make([]flatbuffers.UOffsetT, immediateCommandsLength)
		for j := 0; j < immediateCommandsLength; j++ {
			immediateCommandsOffsets[j] = t.ImmediateCommands[j].Pack(builder)
		}
		CommandBatchStartImmediateCommandsVector(builder, immediateCommandsLength)
		for j := immediateCommandsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(immediateCommandsOffsets[j])
		}
		immediateCommandsOffset = builder.EndVector(immediateCommandsLength)
	}
	sequencesOffset := flatbuffers.UOffsetT(0)
	if t.Sequences != nil {
		sequencesLength := len(t.Sequences)
		sequencesOffsets := make([]flatbuffers.UOffsetT, sequencesLength)
		for j := 0; j < sequencesLength; j++ {
			sequencesOffsets[j] = t.Sequences[j].Pack(builder)
		}
		CommandBatchStartSequencesVector(builder, sequencesLength)
		for j := sequencesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(sequencesOffsets[j])
		}
		sequencesOffset = builder.EndVector(sequencesLength)
	}
	CommandBatchStart(builder)
	CommandBatchAddTimestamp(builder, t.Timestamp)
	CommandBatchAddImmediateCommands(builder, immediateCommandsOffset)
	CommandBatchAddSequences(builder, sequencesOffset)
	CommandBatchAddAbortAll(builder, t.AbortAll)
	return CommandBatchEnd(builder)
}

func (rcv *CommandBatch) UnPackTo(t *CommandBatchT) {
	t.Timestamp = rcv.Timestamp()
	immediateCommandsLength := rcv.ImmediateCommandsLength()
	t.ImmediateCommands = make([]*CommandT, immediateCommandsLength)
	for j := 0; j < immediateCommandsLength; j++ {
		x := Command{}
		rcv.ImmediateCommands(&x, j)
		t.ImmediateCommands[j] = x.UnPack()
	}
	sequencesLength := rcv.SequencesLength()
	t.Sequences = make([]*SequenceT, sequencesLength)
	for j := 0; j < sequencesLength; j++ {
		x := Sequence{}
		rcv.Sequences(&x, j)
		t.Sequences[j] = x.UnPack()
	}
	t.AbortAll = rcv.AbortAll()
}

func (rcv *CommandBatch) UnPack() *CommandBatchT {
	if rcv == nil {
		return nil
	}
	t := &CommandBatchT{}
	rcv.UnPackTo(t)
	return t
}

type CommandBatch struct {
	_tab flatbuffers.Table
}

const CommandBatchIdentifier = "CMND"

func GetRootAsCommandBatch(buf []byte, offset flatbuffers.UOffsetT) *CommandBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandBatch{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(CommandBatchIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func CommandBatchBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, CommandBatchIdentifier)
}

func GetSizePrefixedRootAsCommandBatch(buf []byte, offset flatbuffers.UOffsetT) *CommandBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(CommandBatchIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedCommandBatchBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, CommandBatchIdentifier)
}

func (rcv *CommandBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandBatch) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CommandBatch) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *CommandBatch) ImmediateCommands(obj *Command, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CommandBatch) ImmediateCommandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CommandBatch) Sequences(obj *Sequence, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CommandBatch) SequencesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CommandBatch) AbortAll() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CommandBatch) MutateAbortAll(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func CommandBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func CommandBatchAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(0, timestamp, 0)
}
func CommandBatchAddImmediateCommands(builder *flatbuffers.Builder, immediateCommands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(immediateCommands), 0)
}
func CommandBatchStartImmediateCommandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CommandBatchAddSequences(builder *flatbuffers.Builder, sequences flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(sequences), 0)
}
func CommandBatchStartSequencesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CommandBatchAddAbortAll(builder *flatbuffers.Builder, abortAll bool) {
	builder.PrependBoolSlot(3, abortAll, false)
}
func CommandBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
