// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CustomT struct {
	Topic string `json:"topic"`
	Payload string `json:"payload"`
}

func (t *CustomT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	topicOffset := flatbuffers.UOffsetT(0)
	if t.Topic != "" {
		topicOffset = builder.CreateString(t.Topic)
	}
	payloadOffset := flatbuffers.UOffsetT(0)
	if t.Payload != "" {
		payloadOffset = builder.CreateString(t.Payload)
	}
	CustomStart(builder)
	CustomAddTopic(builder, topicOffset)
	CustomAddPayload(builder, payloadOffset)
	return CustomEnd(builder)
}

func (rcv *Custom) UnPackTo(t *CustomT) {
	t.Topic = string(rcv.Topic())
	t.Payload = string(rcv.Payload())
}

func (rcv *Custom) UnPack() *CustomT {
	if rcv == nil {
		return nil
	}
	t := &CustomT{}
	rcv.UnPackTo(t)
	return t
}

type Custom struct {
	_tab flatbuffers.Table
}

func GetRootAsCustom(buf []byte, offset flatbuffers.UOffsetT) *Custom {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Custom{}
	x.Init(buf, n+offset)
	return x
}

func FinishCustomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCustom(buf []byte, offset flatbuffers.UOffsetT) *Custom {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Custom{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCustomBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Custom) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Custom) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Custom) Topic() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Custom) Payload() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CustomStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CustomAddTopic(builder *flatbuffers.Builder, topic flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(topic), 0)
}
func CustomAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func CustomEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
