// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type Instruction byte

const (
	InstructionNONE        Instruction = 0
	InstructionDummyConfig Instruction = 1
	InstructionInfoMessage Instruction = 2
)

var EnumNamesInstruction = map[Instruction]string{
	InstructionNONE:        "NONE",
	InstructionDummyConfig: "DummyConfig",
	InstructionInfoMessage: "InfoMessage",
}

var EnumValuesInstruction = map[string]Instruction{
	"NONE":        InstructionNONE,
	"DummyConfig": InstructionDummyConfig,
	"InfoMessage": InstructionInfoMessage,
}

func (v Instruction) String() string {
	if s, ok := EnumNamesInstruction[v]; ok {
		return s
	}
	return "Instruction(" + strconv.FormatInt(int64(v), 10) + ")"
}

type InstructionT struct {
	Type Instruction
	Value interface{}
}

func (t *InstructionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case InstructionDummyConfig:
		return t.Value.(*DummyConfigT).Pack(builder)
	case InstructionInfoMessage:
		return t.Value.(*InfoMessageT).Pack(builder)
	}
	return 0
}

func (rcv Instruction) UnPack(table flatbuffers.Table) *InstructionT {
	switch rcv {
	case InstructionDummyConfig:
		var x DummyConfig
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionDummyConfig, Value: x.UnPack()}
	case InstructionInfoMessage:
		var x InfoMessage
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionInfoMessage, Value: x.UnPack()}
	}
	return nil
}
