// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type Instruction byte

const (
	InstructionNONE          Instruction = 0
	InstructionNotify        Instruction = 1
	InstructionSetLed        Instruction = 2
	InstructionAbortSequence Instruction = 3
	InstructionCustom        Instruction = 4
)

var EnumNamesInstruction = map[Instruction]string{
	InstructionNONE:          "NONE",
	InstructionNotify:        "Notify",
	InstructionSetLed:        "SetLed",
	InstructionAbortSequence: "AbortSequence",
	InstructionCustom:        "Custom",
}

var EnumValuesInstruction = map[string]Instruction{
	"NONE":          InstructionNONE,
	"Notify":        InstructionNotify,
	"SetLed":        InstructionSetLed,
	"AbortSequence": InstructionAbortSequence,
	"Custom":        InstructionCustom,
}

func (v Instruction) String() string {
	if s, ok := EnumNamesInstruction[v]; ok {
		return s
	}
	return "Instruction(" + strconv.FormatInt(int64(v), 10) + ")"
}

type InstructionT struct {
	Type Instruction
	Value interface{}
}

func (t *InstructionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case InstructionNotify:
		return t.Value.(*NotifyT).Pack(builder)
	case InstructionSetLed:
		return t.Value.(*SetLedT).Pack(builder)
	case InstructionAbortSequence:
		return t.Value.(*AbortSequenceT).Pack(builder)
	case InstructionCustom:
		return t.Value.(*CustomT).Pack(builder)
	}
	return 0
}

func (rcv Instruction) UnPack(table flatbuffers.Table) *InstructionT {
	switch rcv {
	case InstructionNotify:
		var x Notify
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionNotify, Value: x.UnPack()}
	case InstructionSetLed:
		var x SetLed
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionSetLed, Value: x.UnPack()}
	case InstructionAbortSequence:
		var x AbortSequence
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionAbortSequence, Value: x.UnPack()}
	case InstructionCustom:
		var x Custom
		x.Init(table.Bytes, table.Pos)
		return &InstructionT{Type: InstructionCustom, Value: x.UnPack()}
	}
	return nil
}
