// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NotifyT struct {
	Message string `json:"message"`
}

func (t *NotifyT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	messageOffset := flatbuffers.UOffsetT(0)
	if t.Message != "" {
		messageOffset = builder.CreateString(t.Message)
	}
	NotifyStart(builder)
	NotifyAddMessage(builder, messageOffset)
	return NotifyEnd(builder)
}

func (rcv *Notify) UnPackTo(t *NotifyT) {
	t.Message = string(rcv.Message())
}

func (rcv *Notify) UnPack() *NotifyT {
	if rcv == nil {
		return nil
	}
	t := &NotifyT{}
	rcv.UnPackTo(t)
	return t
}

type Notify struct {
	_tab flatbuffers.Table
}

func GetRootAsNotify(buf []byte, offset flatbuffers.UOffsetT) *Notify {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Notify{}
	x.Init(buf, n+offset)
	return x
}

func FinishNotifyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNotify(buf []byte, offset flatbuffers.UOffsetT) *Notify {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Notify{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNotifyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Notify) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Notify) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Notify) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NotifyStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NotifyAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func NotifyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
