// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SequenceT struct {
	Id uint32 `json:"id"`
	Loop bool `json:"loop"`
	Commands []*CommandT `json:"commands"`
}

func (t *SequenceT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	commandsOffset := flatbuffers.UOffsetT(0)
	if t.Commands != nil {
		commandsLength := len(t.Commands)
		commandsOffsets := make([]flatbuffers.UOffsetT, commandsLength)
		for j := 0; j < commandsLength; j++ {
			commandsOffsets[j] = t.Commands[j].Pack(builder)
		}
		SequenceStartCommandsVector(builder, commandsLength)
		for j := commandsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(commandsOffsets[j])
		}
		commandsOffset = builder.EndVector(commandsLength)
	}
	SequenceStart(builder)
	SequenceAddId(builder, t.Id)
	SequenceAddLoop(builder, t.Loop)
	SequenceAddCommands(builder, commandsOffset)
	return SequenceEnd(builder)
}

func (rcv *Sequence) UnPackTo(t *SequenceT) {
	t.Id = rcv.Id()
	t.Loop = rcv.Loop()
	commandsLength := rcv.CommandsLength()
	t.Commands = make([]*CommandT, commandsLength)
	for j := 0; j < commandsLength; j++ {
		x := Command{}
		rcv.Commands(&x, j)
		t.Commands[j] = x.UnPack()
	}
}

func (rcv *Sequence) UnPack() *SequenceT {
	if rcv == nil {
		return nil
	}
	t := &SequenceT{}
	rcv.UnPackTo(t)
	return t
}

type Sequence struct {
	_tab flatbuffers.Table
}

func GetRootAsSequence(buf []byte, offset flatbuffers.UOffsetT) *Sequence {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Sequence{}
	x.Init(buf, n+offset)
	return x
}

func FinishSequenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSequence(buf []byte, offset flatbuffers.UOffsetT) *Sequence {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Sequence{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSequenceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Sequence) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Sequence) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Sequence) Id() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Sequence) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Sequence) Loop() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Sequence) MutateLoop(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *Sequence) Commands(obj *Command, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Sequence) CommandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SequenceStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SequenceAddId(builder *flatbuffers.Builder, id uint32) {
	builder.PrependUint32Slot(0, id, 0)
}
func SequenceAddLoop(builder *flatbuffers.Builder, loop bool) {
	builder.PrependBoolSlot(1, loop, false)
}
func SequenceAddCommands(builder *flatbuffers.Builder, commands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(commands), 0)
}
func SequenceStartCommandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SequenceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
