// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetLedT struct {
	Color uint32 `json:"color"`
	Mask uint32 `json:"mask"`
}

func (t *SetLedT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SetLedStart(builder)
	SetLedAddColor(builder, t.Color)
	SetLedAddMask(builder, t.Mask)
	return SetLedEnd(builder)
}

func (rcv *SetLed) UnPackTo(t *SetLedT) {
	t.Color = rcv.Color()
	t.Mask = rcv.Mask()
}

func (rcv *SetLed) UnPack() *SetLedT {
	if rcv == nil {
		return nil
	}
	t := &SetLedT{}
	rcv.UnPackTo(t)
	return t
}

type SetLed struct {
	_tab flatbuffers.Table
}

func GetRootAsSetLed(buf []byte, offset flatbuffers.UOffsetT) *SetLed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetLed{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetLedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetLed(buf []byte, offset flatbuffers.UOffsetT) *SetLed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetLed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetLedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetLed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetLed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetLed) Color() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SetLed) MutateColor(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SetLed) Mask() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SetLed) MutateMask(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func SetLedStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SetLedAddColor(builder *flatbuffers.Builder, color uint32) {
	builder.PrependUint32Slot(0, color, 0)
}
func SetLedAddMask(builder *flatbuffers.Builder, mask uint32) {
	builder.PrependUint32Slot(1, mask, 0)
}
func SetLedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
