#ifndef PACKETS_READER_H
#define PACKETS_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct Dummy_table *Dummy_table_t;
typedef struct Dummy_table *Dummy_mutable_table_t;
typedef const flatbuffers_uoffset_t *Dummy_vec_t;
typedef flatbuffers_uoffset_t *Dummy_mutable_vec_t;
#ifndef Dummy_file_identifier
#define Dummy_file_identifier 0
#endif
/* deprecated, use Dummy_file_identifier */
#ifndef Dummy_identifier
#define Dummy_identifier 0
#endif
#define Dummy_type_hash ((flatbuffers_thash_t)0x5e27297b)
#define Dummy_type_identifier "\x7b\x29\x27\x5e"
#ifndef Dummy_file_extension
#define Dummy_file_extension "bin"
#endif



struct Dummy_table { uint8_t unused__; };

static inline size_t Dummy_vec_len(Dummy_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Dummy_table_t Dummy_vec_at(Dummy_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Dummy_table_t, vec, i, 0)
__flatbuffers_table_as_root(Dummy)

__flatbuffers_define_scalar_field(0, Dummy, timestamp, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_vector_field(1, Dummy, data, flatbuffers_uint8_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* PACKETS_READER_H */
