#ifndef PACKETS_BUILDER_H
#define PACKETS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef PACKETS_READER_H
#include "packets_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __Dummy_required[] = { 0 };
typedef flatbuffers_ref_t Dummy_ref_t;
static Dummy_ref_t Dummy_clone(flatbuffers_builder_t *B, Dummy_table_t t);
__flatbuffers_build_table(flatbuffers_, Dummy, 2)

#define __Dummy_formal_args , uint16_t v0, flatbuffers_uint8_vec_ref_t v1
#define __Dummy_call_args , v0, v1
static inline Dummy_ref_t Dummy_create(flatbuffers_builder_t *B __Dummy_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Dummy, Dummy_file_identifier, Dummy_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, Dummy_timestamp, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), Dummy)
__flatbuffers_build_vector_field(1, flatbuffers_, Dummy_data, flatbuffers_uint8, uint8_t, Dummy)

static inline Dummy_ref_t Dummy_create(flatbuffers_builder_t *B __Dummy_formal_args)
{
    if (Dummy_start(B)
        || Dummy_data_add(B, v1)
        || Dummy_timestamp_add(B, v0)) {
        return 0;
    }
    return Dummy_end(B);
}

static Dummy_ref_t Dummy_clone(flatbuffers_builder_t *B, Dummy_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Dummy_start(B)
        || Dummy_data_pick(B, t)
        || Dummy_timestamp_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Dummy_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PACKETS_BUILDER_H */
