# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Instruction(object):
    NONE = 0
    Notify = 1
    SetLed = 2
    AbortSequence = 3
    Custom = 4

def InstructionCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Instruction.Notify:
        return NotifyT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Instruction.SetLed:
        return SetLedT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Instruction.AbortSequence:
        return AbortSequenceT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Instruction.Custom:
        return CustomT.InitFromBuf(table.Bytes, table.Pos)
    return None


class Custom(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Custom()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCustom(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CustomBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # Custom
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Custom
    def Topic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Custom
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CustomStart(builder):
    builder.StartObject(2)

def CustomAddTopic(builder, topic):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(topic), 0)

def CustomAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def CustomEnd(builder):
    return builder.EndObject()



class CustomT(object):

    # CustomT
    def __init__(
        self,
        topic = None,
        payload = None,
    ):
        self.topic = topic  # type: Optional[str]
        self.payload = payload  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        custom = Custom()
        custom.Init(buf, pos)
        return cls.InitFromObj(custom)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, custom):
        x = CustomT()
        x._UnPack(custom)
        return x

    # CustomT
    def _UnPack(self, custom):
        if custom is None:
            return
        self.topic = custom.Topic()
        self.payload = custom.Payload()

    # CustomT
    def Pack(self, builder):
        if self.topic is not None:
            topic = builder.CreateString(self.topic)
        if self.payload is not None:
            payload = builder.CreateString(self.payload)
        CustomStart(builder)
        if self.topic is not None:
            CustomAddTopic(builder, topic)
        if self.payload is not None:
            CustomAddPayload(builder, payload)
        custom = CustomEnd(builder)
        return custom


class Notify(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Notify()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNotify(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NotifyBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # Notify
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Notify
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def NotifyStart(builder):
    builder.StartObject(1)

def NotifyAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def NotifyEnd(builder):
    return builder.EndObject()



class NotifyT(object):

    # NotifyT
    def __init__(
        self,
        message = None,
    ):
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        notify = Notify()
        notify.Init(buf, pos)
        return cls.InitFromObj(notify)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, notify):
        x = NotifyT()
        x._UnPack(notify)
        return x

    # NotifyT
    def _UnPack(self, notify):
        if notify is None:
            return
        self.message = notify.Message()

    # NotifyT
    def Pack(self, builder):
        if self.message is not None:
            message = builder.CreateString(self.message)
        NotifyStart(builder)
        if self.message is not None:
            NotifyAddMessage(builder, message)
        notify = NotifyEnd(builder)
        return notify


class SetLed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetLed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetLed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SetLedBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # SetLed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetLed
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SetLed
    def Mask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SetLedStart(builder):
    builder.StartObject(2)

def SetLedAddColor(builder, color):
    builder.PrependUint32Slot(0, color, 0)

def SetLedAddMask(builder, mask):
    builder.PrependUint32Slot(1, mask, 0)

def SetLedEnd(builder):
    return builder.EndObject()



class SetLedT(object):

    # SetLedT
    def __init__(
        self,
        color = 0,
        mask = 0,
    ):
        self.color = color  # type: int
        self.mask = mask  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setLed = SetLed()
        setLed.Init(buf, pos)
        return cls.InitFromObj(setLed)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setLed):
        x = SetLedT()
        x._UnPack(setLed)
        return x

    # SetLedT
    def _UnPack(self, setLed):
        if setLed is None:
            return
        self.color = setLed.Color()
        self.mask = setLed.Mask()

    # SetLedT
    def Pack(self, builder):
        SetLedStart(builder)
        SetLedAddColor(builder, self.color)
        SetLedAddMask(builder, self.mask)
        setLed = SetLedEnd(builder)
        return setLed


class Sequence(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Sequence()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSequence(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SequenceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # Sequence
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sequence
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Sequence
    def Loop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Sequence
    def Commands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Command()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Sequence
    def CommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Sequence
    def CommandsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SequenceStart(builder):
    builder.StartObject(3)

def SequenceAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def SequenceAddLoop(builder, loop):
    builder.PrependBoolSlot(1, loop, 0)

def SequenceAddCommands(builder, commands):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(commands), 0)

def SequenceStartCommandsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SequenceCreateCommandsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def SequenceEnd(builder):
    return builder.EndObject()


try:
    from typing import List
except:
    pass

class SequenceT(object):

    # SequenceT
    def __init__(
        self,
        id = 0,
        loop = False,
        commands = None,
    ):
        self.id = id  # type: int
        self.loop = loop  # type: bool
        self.commands = commands  # type: Optional[List[CommandT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sequence = Sequence()
        sequence.Init(buf, pos)
        return cls.InitFromObj(sequence)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sequence):
        x = SequenceT()
        x._UnPack(sequence)
        return x

    # SequenceT
    def _UnPack(self, sequence):
        if sequence is None:
            return
        self.id = sequence.Id()
        self.loop = sequence.Loop()
        if not sequence.CommandsIsNone():
            self.commands = []
            for i in range(sequence.CommandsLength()):
                if sequence.Commands(i) is None:
                    self.commands.append(None)
                else:
                    command_ = CommandT.InitFromObj(sequence.Commands(i))
                    self.commands.append(command_)

    # SequenceT
    def Pack(self, builder):
        if self.commands is not None:
            commandslist = []
            for i in range(len(self.commands)):
                commandslist.append(self.commands[i].Pack(builder))
            SequenceStartCommandsVector(builder, len(self.commands))
            for i in reversed(range(len(self.commands))):
                builder.PrependUOffsetTRelative(commandslist[i])
            commands = builder.EndVector()
        SequenceStart(builder)
        SequenceAddId(builder, self.id)
        SequenceAddLoop(builder, self.loop)
        if self.commands is not None:
            SequenceAddCommands(builder, commands)
        sequence = SequenceEnd(builder)
        return sequence


class AbortSequence(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AbortSequence()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAbortSequence(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AbortSequenceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # AbortSequence
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AbortSequence
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AbortSequenceStart(builder):
    builder.StartObject(1)

def AbortSequenceAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AbortSequenceEnd(builder):
    return builder.EndObject()



class AbortSequenceT(object):

    # AbortSequenceT
    def __init__(
        self,
        id = 0,
    ):
        self.id = id  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        abortSequence = AbortSequence()
        abortSequence.Init(buf, pos)
        return cls.InitFromObj(abortSequence)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, abortSequence):
        x = AbortSequenceT()
        x._UnPack(abortSequence)
        return x

    # AbortSequenceT
    def _UnPack(self, abortSequence):
        if abortSequence is None:
            return
        self.id = abortSequence.Id()

    # AbortSequenceT
    def Pack(self, builder):
        AbortSequenceStart(builder)
        AbortSequenceAddId(builder, self.id)
        abortSequence = AbortSequenceEnd(builder)
        return abortSequence


class Command(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Command()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # Command
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Command
    def CommandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Command
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CommandStart(builder):
    builder.StartObject(2)

def CommandAddCommandType(builder, commandType):
    builder.PrependUint8Slot(0, commandType, 0)

def CommandAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def CommandEnd(builder):
    return builder.EndObject()


try:
    from typing import Union
except:
    pass

class CommandT(object):

    # CommandT
    def __init__(
        self,
        commandType = 0,
        command = None,
    ):
        self.commandType = commandType  # type: int
        self.command = command  # type: Union[None, 'NotifyT', 'SetLedT', 'AbortSequenceT', 'CustomT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        command = Command()
        command.Init(buf, pos)
        return cls.InitFromObj(command)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, command):
        x = CommandT()
        x._UnPack(command)
        return x

    # CommandT
    def _UnPack(self, command):
        if command is None:
            return
        self.commandType = command.CommandType()
        self.command = InstructionCreator(self.commandType, command.Command())

    # CommandT
    def Pack(self, builder):
        if self.command is not None:
            command = self.command.Pack(builder)
        CommandStart(builder)
        CommandAddCommandType(builder, self.commandType)
        if self.command is not None:
            CommandAddCommand(builder, command)
        command = CommandEnd(builder)
        return command


class CommandBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CommandBatchBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x4D\x4E\x44", size_prefixed=size_prefixed)

    # CommandBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandBatch
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CommandBatch
    def ImmediateCommands(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Command()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CommandBatch
    def ImmediateCommandsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommandBatch
    def ImmediateCommandsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # CommandBatch
    def Sequences(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Sequence()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CommandBatch
    def SequencesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommandBatch
    def SequencesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # CommandBatch
    def AbortAll(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def CommandBatchStart(builder):
    builder.StartObject(4)

def CommandBatchAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def CommandBatchAddImmediateCommands(builder, immediateCommands):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(immediateCommands), 0)

def CommandBatchStartImmediateCommandsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def CommandBatchCreateImmediateCommandsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CommandBatchAddSequences(builder, sequences):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sequences), 0)

def CommandBatchStartSequencesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def CommandBatchCreateSequencesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CommandBatchAddAbortAll(builder, abortAll):
    builder.PrependBoolSlot(3, abortAll, 0)

def CommandBatchEnd(builder):
    return builder.EndObject()


try:
    from typing import List
except:
    pass

class CommandBatchT(object):

    # CommandBatchT
    def __init__(
        self,
        timestamp = 0,
        immediateCommands = None,
        sequences = None,
        abortAll = False,
    ):
        self.timestamp = timestamp  # type: int
        self.immediateCommands = immediateCommands  # type: Optional[List[CommandT]]
        self.sequences = sequences  # type: Optional[List[SequenceT]]
        self.abortAll = abortAll  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        commandBatch = CommandBatch()
        commandBatch.Init(buf, pos)
        return cls.InitFromObj(commandBatch)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, commandBatch):
        x = CommandBatchT()
        x._UnPack(commandBatch)
        return x

    # CommandBatchT
    def _UnPack(self, commandBatch):
        if commandBatch is None:
            return
        self.timestamp = commandBatch.Timestamp()
        if not commandBatch.ImmediateCommandsIsNone():
            self.immediateCommands = []
            for i in range(commandBatch.ImmediateCommandsLength()):
                if commandBatch.ImmediateCommands(i) is None:
                    self.immediateCommands.append(None)
                else:
                    command_ = CommandT.InitFromObj(commandBatch.ImmediateCommands(i))
                    self.immediateCommands.append(command_)
        if not commandBatch.SequencesIsNone():
            self.sequences = []
            for i in range(commandBatch.SequencesLength()):
                if commandBatch.Sequences(i) is None:
                    self.sequences.append(None)
                else:
                    sequence_ = SequenceT.InitFromObj(commandBatch.Sequences(i))
                    self.sequences.append(sequence_)
        self.abortAll = commandBatch.AbortAll()

    # CommandBatchT
    def Pack(self, builder):
        if self.immediateCommands is not None:
            immediateCommandslist = []
            for i in range(len(self.immediateCommands)):
                immediateCommandslist.append(self.immediateCommands[i].Pack(builder))
            CommandBatchStartImmediateCommandsVector(builder, len(self.immediateCommands))
            for i in reversed(range(len(self.immediateCommands))):
                builder.PrependUOffsetTRelative(immediateCommandslist[i])
            immediateCommands = builder.EndVector()
        if self.sequences is not None:
            sequenceslist = []
            for i in range(len(self.sequences)):
                sequenceslist.append(self.sequences[i].Pack(builder))
            CommandBatchStartSequencesVector(builder, len(self.sequences))
            for i in reversed(range(len(self.sequences))):
                builder.PrependUOffsetTRelative(sequenceslist[i])
            sequences = builder.EndVector()
        CommandBatchStart(builder)
        CommandBatchAddTimestamp(builder, self.timestamp)
        if self.immediateCommands is not None:
            CommandBatchAddImmediateCommands(builder, immediateCommands)
        if self.sequences is not None:
            CommandBatchAddSequences(builder, sequences)
        CommandBatchAddAbortAll(builder, self.abortAll)
        commandBatch = CommandBatchEnd(builder)
        return commandBatch


