# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sensors

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RingSensorData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # RingSensorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RingSensorData
    def S0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # RingSensorData
    def S1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # RingSensorData
    def S2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # RingSensorData
    def S3(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # RingSensorData
    def S4(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # RingSensorData
    def S5(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # RingSensorData
    def S6(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # RingSensorData
    def S7(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))

def CreateRingSensorData(builder, s0, s1, s2, s3, s4, s5, s6, s7):
    builder.Prep(2, 16)
    builder.PrependUint16(s7)
    builder.PrependUint16(s6)
    builder.PrependUint16(s5)
    builder.PrependUint16(s4)
    builder.PrependUint16(s3)
    builder.PrependUint16(s2)
    builder.PrependUint16(s1)
    builder.PrependUint16(s0)
    return builder.Offset()


class RingSensorDataT(object):

    # RingSensorDataT
    def __init__(
        self,
        s0 = 0,
        s1 = 0,
        s2 = 0,
        s3 = 0,
        s4 = 0,
        s5 = 0,
        s6 = 0,
        s7 = 0,
    ):
        self.s0 = s0  # type: int
        self.s1 = s1  # type: int
        self.s2 = s2  # type: int
        self.s3 = s3  # type: int
        self.s4 = s4  # type: int
        self.s5 = s5  # type: int
        self.s6 = s6  # type: int
        self.s7 = s7  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        ringSensorData = RingSensorData()
        ringSensorData.Init(buf, pos)
        return cls.InitFromObj(ringSensorData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, ringSensorData):
        x = RingSensorDataT()
        x._UnPack(ringSensorData)
        return x

    # RingSensorDataT
    def _UnPack(self, ringSensorData):
        if ringSensorData is None:
            return
        self.s0 = ringSensorData.S0()
        self.s1 = ringSensorData.S1()
        self.s2 = ringSensorData.S2()
        self.s3 = ringSensorData.S3()
        self.s4 = ringSensorData.S4()
        self.s5 = ringSensorData.S5()
        self.s6 = ringSensorData.S6()
        self.s7 = ringSensorData.S7()

    # RingSensorDataT
    def Pack(self, builder):
        return CreateRingSensorData(builder, self.s0, self.s1, self.s2, self.s3, self.s4, self.s5, self.s6, self.s7)


class ProximityLightData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 36

    # ProximityLightData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProximityLightData
    def Proximity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # ProximityLightData
    def AmbientLight(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # ProximityLightData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # ProximityLightData
    def Padding(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(34))

def CreateProximityLightData(builder, proximity_s0, proximity_s1, proximity_s2, proximity_s3, proximity_s4, proximity_s5, proximity_s6, proximity_s7, ambientLight_s0, ambientLight_s1, ambientLight_s2, ambientLight_s3, ambientLight_s4, ambientLight_s5, ambientLight_s6, ambientLight_s7, timestampOffset, padding):
    builder.Prep(2, 36)
    builder.PrependUint16(padding)
    builder.PrependUint16(timestampOffset)
    builder.Prep(2, 16)
    builder.PrependUint16(ambientLight_s7)
    builder.PrependUint16(ambientLight_s6)
    builder.PrependUint16(ambientLight_s5)
    builder.PrependUint16(ambientLight_s4)
    builder.PrependUint16(ambientLight_s3)
    builder.PrependUint16(ambientLight_s2)
    builder.PrependUint16(ambientLight_s1)
    builder.PrependUint16(ambientLight_s0)
    builder.Prep(2, 16)
    builder.PrependUint16(proximity_s7)
    builder.PrependUint16(proximity_s6)
    builder.PrependUint16(proximity_s5)
    builder.PrependUint16(proximity_s4)
    builder.PrependUint16(proximity_s3)
    builder.PrependUint16(proximity_s2)
    builder.PrependUint16(proximity_s1)
    builder.PrependUint16(proximity_s0)
    return builder.Offset()

try:
    from typing import Optional
except:
    pass

class ProximityLightDataT(object):

    # ProximityLightDataT
    def __init__(
        self,
        proximity = None,
        ambientLight = None,
        timestampOffset = 0,
        padding = 0,
    ):
        self.proximity = proximity  # type: Optional[RingSensorDataT]
        self.ambientLight = ambientLight  # type: Optional[RingSensorDataT]
        self.timestampOffset = timestampOffset  # type: int
        self.padding = padding  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        proximityLightData = ProximityLightData()
        proximityLightData.Init(buf, pos)
        return cls.InitFromObj(proximityLightData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, proximityLightData):
        x = ProximityLightDataT()
        x._UnPack(proximityLightData)
        return x

    # ProximityLightDataT
    def _UnPack(self, proximityLightData):
        if proximityLightData is None:
            return
        if proximityLightData.Proximity(RingSensorData()) is not None:
            self.proximity = RingSensorDataT.InitFromObj(proximityLightData.Proximity(RingSensorData()))
        if proximityLightData.AmbientLight(RingSensorData()) is not None:
            self.ambientLight = RingSensorDataT.InitFromObj(proximityLightData.AmbientLight(RingSensorData()))
        self.timestampOffset = proximityLightData.TimestampOffset()
        self.padding = proximityLightData.Padding()

    # ProximityLightDataT
    def Pack(self, builder):
        return CreateProximityLightData(builder, self.proximity.s0, self.proximity.s1, self.proximity.s2, self.proximity.s3, self.proximity.s4, self.proximity.s5, self.proximity.s6, self.proximity.s7, self.ambientLight.s0, self.ambientLight.s1, self.ambientLight.s2, self.ambientLight.s3, self.ambientLight.s4, self.ambientLight.s5, self.ambientLight.s6, self.ambientLight.s7, self.timestampOffset, self.padding)


class TofData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # TofData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TofData
    def Distance(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TofData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateTofData(builder, distance, timestampOffset):
    builder.Prep(2, 4)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(distance)
    return builder.Offset()


class TofDataT(object):

    # TofDataT
    def __init__(
        self,
        distance = 0,
        timestampOffset = 0,
    ):
        self.distance = distance  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tofData = TofData()
        tofData.Init(buf, pos)
        return cls.InitFromObj(tofData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tofData):
        x = TofDataT()
        x._UnPack(tofData)
        return x

    # TofDataT
    def _UnPack(self, tofData):
        if tofData is None:
            return
        self.distance = tofData.Distance()
        self.timestampOffset = tofData.TimestampOffset()

    # TofDataT
    def Pack(self, builder):
        return CreateTofData(builder, self.distance, self.timestampOffset)


class BatteryData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # BatteryData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatteryData
    def Millivolts(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BatteryData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateBatteryData(builder, millivolts, timestampOffset):
    builder.Prep(2, 4)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(millivolts)
    return builder.Offset()


class BatteryDataT(object):

    # BatteryDataT
    def __init__(
        self,
        millivolts = 0,
        timestampOffset = 0,
    ):
        self.millivolts = millivolts  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        batteryData = BatteryData()
        batteryData.Init(buf, pos)
        return cls.InitFromObj(batteryData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, batteryData):
        x = BatteryDataT()
        x._UnPack(batteryData)
        return x

    # BatteryDataT
    def _UnPack(self, batteryData):
        if batteryData is None:
            return
        self.millivolts = batteryData.Millivolts()
        self.timestampOffset = batteryData.TimestampOffset()

    # BatteryDataT
    def Pack(self, builder):
        return CreateBatteryData(builder, self.millivolts, self.timestampOffset)


class EncoderData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # EncoderData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncoderData
    def LeftSteps(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EncoderData
    def RightSteps(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # EncoderData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EncoderData
    def Padding(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))

def CreateEncoderData(builder, leftSteps, rightSteps, timestampOffset, padding):
    builder.Prep(4, 12)
    builder.PrependUint16(padding)
    builder.PrependUint16(timestampOffset)
    builder.PrependInt32(rightSteps)
    builder.PrependInt32(leftSteps)
    return builder.Offset()


class EncoderDataT(object):

    # EncoderDataT
    def __init__(
        self,
        leftSteps = 0,
        rightSteps = 0,
        timestampOffset = 0,
        padding = 0,
    ):
        self.leftSteps = leftSteps  # type: int
        self.rightSteps = rightSteps  # type: int
        self.timestampOffset = timestampOffset  # type: int
        self.padding = padding  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        encoderData = EncoderData()
        encoderData.Init(buf, pos)
        return cls.InitFromObj(encoderData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, encoderData):
        x = EncoderDataT()
        x._UnPack(encoderData)
        return x

    # EncoderDataT
    def _UnPack(self, encoderData):
        if encoderData is None:
            return
        self.leftSteps = encoderData.LeftSteps()
        self.rightSteps = encoderData.RightSteps()
        self.timestampOffset = encoderData.TimestampOffset()
        self.padding = encoderData.Padding()

    # EncoderDataT
    def Pack(self, builder):
        return CreateEncoderData(builder, self.leftSteps, self.rightSteps, self.timestampOffset, self.padding)


class Vector3D(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 6

    # Vector3D
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vector3D
    def X(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vector3D
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # Vector3D
    def Z(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateVector3D(builder, x, y, z):
    builder.Prep(2, 6)
    builder.PrependInt16(z)
    builder.PrependInt16(y)
    builder.PrependInt16(x)
    return builder.Offset()


class Vector3DT(object):

    # Vector3DT
    def __init__(
        self,
        x = 0,
        y = 0,
        z = 0,
    ):
        self.x = x  # type: int
        self.y = y  # type: int
        self.z = z  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vector3D = Vector3D()
        vector3D.Init(buf, pos)
        return cls.InitFromObj(vector3D)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vector3D):
        x = Vector3DT()
        x._UnPack(vector3D)
        return x

    # Vector3DT
    def _UnPack(self, vector3D):
        if vector3D is None:
            return
        self.x = vector3D.X()
        self.y = vector3D.Y()
        self.z = vector3D.Z()

    # Vector3DT
    def Pack(self, builder):
        return CreateVector3D(builder, self.x, self.y, self.z)


class ImuData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # ImuData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImuData
    def Accelerometer(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # ImuData
    def Gyroscope(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 6)
        return obj

    # ImuData
    def Magnetometer(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

    # ImuData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(18))

def CreateImuData(builder, accelerometer_x, accelerometer_y, accelerometer_z, gyroscope_x, gyroscope_y, gyroscope_z, magnetometer_x, magnetometer_y, magnetometer_z, timestampOffset):
    builder.Prep(2, 20)
    builder.PrependUint16(timestampOffset)
    builder.Prep(2, 6)
    builder.PrependInt16(magnetometer_z)
    builder.PrependInt16(magnetometer_y)
    builder.PrependInt16(magnetometer_x)
    builder.Prep(2, 6)
    builder.PrependInt16(gyroscope_z)
    builder.PrependInt16(gyroscope_y)
    builder.PrependInt16(gyroscope_x)
    builder.Prep(2, 6)
    builder.PrependInt16(accelerometer_z)
    builder.PrependInt16(accelerometer_y)
    builder.PrependInt16(accelerometer_x)
    return builder.Offset()

try:
    from typing import Optional
except:
    pass

class ImuDataT(object):

    # ImuDataT
    def __init__(
        self,
        accelerometer = None,
        gyroscope = None,
        magnetometer = None,
        timestampOffset = 0,
    ):
        self.accelerometer = accelerometer  # type: Optional[Vector3DT]
        self.gyroscope = gyroscope  # type: Optional[Vector3DT]
        self.magnetometer = magnetometer  # type: Optional[Vector3DT]
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        imuData = ImuData()
        imuData.Init(buf, pos)
        return cls.InitFromObj(imuData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, imuData):
        x = ImuDataT()
        x._UnPack(imuData)
        return x

    # ImuDataT
    def _UnPack(self, imuData):
        if imuData is None:
            return
        if imuData.Accelerometer(Vector3D()) is not None:
            self.accelerometer = Vector3DT.InitFromObj(imuData.Accelerometer(Vector3D()))
        if imuData.Gyroscope(Vector3D()) is not None:
            self.gyroscope = Vector3DT.InitFromObj(imuData.Gyroscope(Vector3D()))
        if imuData.Magnetometer(Vector3D()) is not None:
            self.magnetometer = Vector3DT.InitFromObj(imuData.Magnetometer(Vector3D()))
        self.timestampOffset = imuData.TimestampOffset()

    # ImuDataT
    def Pack(self, builder):
        return CreateImuData(builder, self.accelerometer.x, self.accelerometer.y, self.accelerometer.z, self.gyroscope.x, self.gyroscope.y, self.gyroscope.z, self.magnetometer.x, self.magnetometer.y, self.magnetometer.z, self.timestampOffset)


class VolumeData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 10

    # VolumeData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VolumeData
    def M0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VolumeData
    def M1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # VolumeData
    def M2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # VolumeData
    def M3(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # VolumeData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateVolumeData(builder, m0, m1, m2, m3, timestampOffset):
    builder.Prep(2, 10)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(m3)
    builder.PrependUint16(m2)
    builder.PrependUint16(m1)
    builder.PrependUint16(m0)
    return builder.Offset()


class VolumeDataT(object):

    # VolumeDataT
    def __init__(
        self,
        m0 = 0,
        m1 = 0,
        m2 = 0,
        m3 = 0,
        timestampOffset = 0,
    ):
        self.m0 = m0  # type: int
        self.m1 = m1  # type: int
        self.m2 = m2  # type: int
        self.m3 = m3  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        volumeData = VolumeData()
        volumeData.Init(buf, pos)
        return cls.InitFromObj(volumeData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, volumeData):
        x = VolumeDataT()
        x._UnPack(volumeData)
        return x

    # VolumeDataT
    def _UnPack(self, volumeData):
        if volumeData is None:
            return
        self.m0 = volumeData.M0()
        self.m1 = volumeData.M1()
        self.m2 = volumeData.M2()
        self.m3 = volumeData.M3()
        self.timestampOffset = volumeData.TimestampOffset()

    # VolumeDataT
    def Pack(self, builder):
        return CreateVolumeData(builder, self.m0, self.m1, self.m2, self.m3, self.timestampOffset)


class AudioMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # AudioMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioMetadata
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AudioMetadata
    def Length(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # AudioMetadata
    def SampleCount(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # AudioMetadata
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))

def CreateAudioMetadata(builder, offset, length, sampleCount, timestampOffset):
    builder.Prep(2, 8)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(sampleCount)
    builder.PrependUint16(length)
    builder.PrependUint16(offset)
    return builder.Offset()


class AudioMetadataT(object):

    # AudioMetadataT
    def __init__(
        self,
        offset = 0,
        length = 0,
        sampleCount = 0,
        timestampOffset = 0,
    ):
        self.offset = offset  # type: int
        self.length = length  # type: int
        self.sampleCount = sampleCount  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        audioMetadata = AudioMetadata()
        audioMetadata.Init(buf, pos)
        return cls.InitFromObj(audioMetadata)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, audioMetadata):
        x = AudioMetadataT()
        x._UnPack(audioMetadata)
        return x

    # AudioMetadataT
    def _UnPack(self, audioMetadata):
        if audioMetadata is None:
            return
        self.offset = audioMetadata.Offset()
        self.length = audioMetadata.Length()
        self.sampleCount = audioMetadata.SampleCount()
        self.timestampOffset = audioMetadata.TimestampOffset()

    # AudioMetadataT
    def Pack(self, builder):
        return CreateAudioMetadata(builder, self.offset, self.length, self.sampleCount, self.timestampOffset)


class VideoMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # VideoMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VideoMetadata
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VideoMetadata
    def Length(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # VideoMetadata
    def FrameId(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # VideoMetadata
    def FragmentIndex(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # VideoMetadata
    def TotalFragments(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))
    # VideoMetadata
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # VideoMetadata
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))

def CreateVideoMetadata(builder, offset, length, frameId, fragmentIndex, totalFragments, flags, timestampOffset):
    builder.Prep(4, 16)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(flags)
    builder.PrependUint8(totalFragments)
    builder.PrependUint8(fragmentIndex)
    builder.PrependUint16(frameId)
    builder.PrependUint32(length)
    builder.PrependUint32(offset)
    return builder.Offset()


class VideoMetadataT(object):

    # VideoMetadataT
    def __init__(
        self,
        offset = 0,
        length = 0,
        frameId = 0,
        fragmentIndex = 0,
        totalFragments = 0,
        flags = 0,
        timestampOffset = 0,
    ):
        self.offset = offset  # type: int
        self.length = length  # type: int
        self.frameId = frameId  # type: int
        self.fragmentIndex = fragmentIndex  # type: int
        self.totalFragments = totalFragments  # type: int
        self.flags = flags  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        videoMetadata = VideoMetadata()
        videoMetadata.Init(buf, pos)
        return cls.InitFromObj(videoMetadata)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, videoMetadata):
        x = VideoMetadataT()
        x._UnPack(videoMetadata)
        return x

    # VideoMetadataT
    def _UnPack(self, videoMetadata):
        if videoMetadata is None:
            return
        self.offset = videoMetadata.Offset()
        self.length = videoMetadata.Length()
        self.frameId = videoMetadata.FrameId()
        self.fragmentIndex = videoMetadata.FragmentIndex()
        self.totalFragments = videoMetadata.TotalFragments()
        self.flags = videoMetadata.Flags()
        self.timestampOffset = videoMetadata.TimestampOffset()

    # VideoMetadataT
    def Pack(self, builder):
        return CreateVideoMetadata(builder, self.offset, self.length, self.frameId, self.fragmentIndex, self.totalFragments, self.flags, self.timestampOffset)


class SensorBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SensorBatchBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x45\x4E\x53", size_prefixed=size_prefixed)

    # SensorBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorBatch
    def BaseTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorBatch
    def Proximity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 36
            obj = ProximityLightData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def ProximityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def ProximityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SensorBatch
    def Tof(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = TofData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def TofLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def TofIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SensorBatch
    def Battery(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = BatteryData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def BatteryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def BatteryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # SensorBatch
    def Encoder(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = EncoderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def EncoderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def EncoderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # SensorBatch
    def Imu(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            obj = ImuData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def ImuLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def ImuIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # SensorBatch
    def AudioBlob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorBatch
    def AudioBlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorBatch
    def AudioBlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def AudioBlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # SensorBatch
    def AudioMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = AudioMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def AudioMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def AudioMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # SensorBatch
    def VideoBlob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorBatch
    def VideoBlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorBatch
    def VideoBlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def VideoBlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # SensorBatch
    def VideoMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = VideoMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def VideoMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def VideoMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def SensorBatchStart(builder):
    builder.StartObject(10)

def SensorBatchAddBaseTimestamp(builder, baseTimestamp):
    builder.PrependUint64Slot(0, baseTimestamp, 0)

def SensorBatchAddProximity(builder, proximity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(proximity), 0)

def SensorBatchStartProximityVector(builder, numElems):
    return builder.StartVector(36, numElems, 2)

def SensorBatchCreateProximityVector(builder, data):
    data = list(data)
    builder.StartVector(36, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddTof(builder, tof):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tof), 0)

def SensorBatchStartTofVector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def SensorBatchCreateTofVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddBattery(builder, battery):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(battery), 0)

def SensorBatchStartBatteryVector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def SensorBatchCreateBatteryVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddEncoder(builder, encoder):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(encoder), 0)

def SensorBatchStartEncoderVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def SensorBatchCreateEncoderVector(builder, data):
    data = list(data)
    builder.StartVector(12, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddImu(builder, imu):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(imu), 0)

def SensorBatchStartImuVector(builder, numElems):
    return builder.StartVector(20, numElems, 2)

def SensorBatchCreateImuVector(builder, data):
    data = list(data)
    builder.StartVector(20, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddAudioBlob(builder, audioBlob):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(audioBlob), 0)

def SensorBatchStartAudioBlobVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SensorBatchCreateAudioBlobVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def SensorBatchAddAudioMetadata(builder, audioMetadata):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(audioMetadata), 0)

def SensorBatchStartAudioMetadataVector(builder, numElems):
    return builder.StartVector(8, numElems, 2)

def SensorBatchCreateAudioMetadataVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddVideoBlob(builder, videoBlob):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(videoBlob), 0)

def SensorBatchStartVideoBlobVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SensorBatchCreateVideoBlobVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def SensorBatchAddVideoMetadata(builder, videoMetadata):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(videoMetadata), 0)

def SensorBatchStartVideoMetadataVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def SensorBatchCreateVideoMetadataVector(builder, data):
    data = list(data)
    builder.StartVector(16, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchEnd(builder):
    return builder.EndObject()


try:
    from typing import List
except:
    pass

class SensorBatchT(object):

    # SensorBatchT
    def __init__(
        self,
        baseTimestamp = 0,
        proximity = None,
        tof = None,
        battery = None,
        encoder = None,
        imu = None,
        audioBlob = None,
        audioMetadata = None,
        videoBlob = None,
        videoMetadata = None,
    ):
        self.baseTimestamp = baseTimestamp  # type: int
        self.proximity = proximity  # type: Optional[List[ProximityLightDataT]]
        self.tof = tof  # type: Optional[List[TofDataT]]
        self.battery = battery  # type: Optional[List[BatteryDataT]]
        self.encoder = encoder  # type: Optional[List[EncoderDataT]]
        self.imu = imu  # type: Optional[List[ImuDataT]]
        self.audioBlob = audioBlob  # type: Optional[List[int]]
        self.audioMetadata = audioMetadata  # type: Optional[List[AudioMetadataT]]
        self.videoBlob = videoBlob  # type: Optional[List[int]]
        self.videoMetadata = videoMetadata  # type: Optional[List[VideoMetadataT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sensorBatch = SensorBatch()
        sensorBatch.Init(buf, pos)
        return cls.InitFromObj(sensorBatch)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sensorBatch):
        x = SensorBatchT()
        x._UnPack(sensorBatch)
        return x

    # SensorBatchT
    def _UnPack(self, sensorBatch):
        if sensorBatch is None:
            return
        self.baseTimestamp = sensorBatch.BaseTimestamp()
        if not sensorBatch.ProximityIsNone():
            self.proximity = []
            for i in range(sensorBatch.ProximityLength()):
                if sensorBatch.Proximity(i) is None:
                    self.proximity.append(None)
                else:
                    proximityLightData_ = ProximityLightDataT.InitFromObj(sensorBatch.Proximity(i))
                    self.proximity.append(proximityLightData_)
        if not sensorBatch.TofIsNone():
            self.tof = []
            for i in range(sensorBatch.TofLength()):
                if sensorBatch.Tof(i) is None:
                    self.tof.append(None)
                else:
                    tofData_ = TofDataT.InitFromObj(sensorBatch.Tof(i))
                    self.tof.append(tofData_)
        if not sensorBatch.BatteryIsNone():
            self.battery = []
            for i in range(sensorBatch.BatteryLength()):
                if sensorBatch.Battery(i) is None:
                    self.battery.append(None)
                else:
                    batteryData_ = BatteryDataT.InitFromObj(sensorBatch.Battery(i))
                    self.battery.append(batteryData_)
        if not sensorBatch.EncoderIsNone():
            self.encoder = []
            for i in range(sensorBatch.EncoderLength()):
                if sensorBatch.Encoder(i) is None:
                    self.encoder.append(None)
                else:
                    encoderData_ = EncoderDataT.InitFromObj(sensorBatch.Encoder(i))
                    self.encoder.append(encoderData_)
        if not sensorBatch.ImuIsNone():
            self.imu = []
            for i in range(sensorBatch.ImuLength()):
                if sensorBatch.Imu(i) is None:
                    self.imu.append(None)
                else:
                    imuData_ = ImuDataT.InitFromObj(sensorBatch.Imu(i))
                    self.imu.append(imuData_)
        if not sensorBatch.AudioBlobIsNone():
            if np is None:
                self.audioBlob = []
                for i in range(sensorBatch.AudioBlobLength()):
                    self.audioBlob.append(sensorBatch.AudioBlob(i))
            else:
                self.audioBlob = sensorBatch.AudioBlobAsNumpy()
        if not sensorBatch.AudioMetadataIsNone():
            self.audioMetadata = []
            for i in range(sensorBatch.AudioMetadataLength()):
                if sensorBatch.AudioMetadata(i) is None:
                    self.audioMetadata.append(None)
                else:
                    audioMetadata_ = AudioMetadataT.InitFromObj(sensorBatch.AudioMetadata(i))
                    self.audioMetadata.append(audioMetadata_)
        if not sensorBatch.VideoBlobIsNone():
            if np is None:
                self.videoBlob = []
                for i in range(sensorBatch.VideoBlobLength()):
                    self.videoBlob.append(sensorBatch.VideoBlob(i))
            else:
                self.videoBlob = sensorBatch.VideoBlobAsNumpy()
        if not sensorBatch.VideoMetadataIsNone():
            self.videoMetadata = []
            for i in range(sensorBatch.VideoMetadataLength()):
                if sensorBatch.VideoMetadata(i) is None:
                    self.videoMetadata.append(None)
                else:
                    videoMetadata_ = VideoMetadataT.InitFromObj(sensorBatch.VideoMetadata(i))
                    self.videoMetadata.append(videoMetadata_)

    # SensorBatchT
    def Pack(self, builder):
        if self.proximity is not None:
            SensorBatchStartProximityVector(builder, len(self.proximity))
            for i in reversed(range(len(self.proximity))):
                self.proximity[i].Pack(builder)
            proximity = builder.EndVector()
        if self.tof is not None:
            SensorBatchStartTofVector(builder, len(self.tof))
            for i in reversed(range(len(self.tof))):
                self.tof[i].Pack(builder)
            tof = builder.EndVector()
        if self.battery is not None:
            SensorBatchStartBatteryVector(builder, len(self.battery))
            for i in reversed(range(len(self.battery))):
                self.battery[i].Pack(builder)
            battery = builder.EndVector()
        if self.encoder is not None:
            SensorBatchStartEncoderVector(builder, len(self.encoder))
            for i in reversed(range(len(self.encoder))):
                self.encoder[i].Pack(builder)
            encoder = builder.EndVector()
        if self.imu is not None:
            SensorBatchStartImuVector(builder, len(self.imu))
            for i in reversed(range(len(self.imu))):
                self.imu[i].Pack(builder)
            imu = builder.EndVector()
        if self.audioBlob is not None:
            if np is not None and type(self.audioBlob) is np.ndarray:
                audioBlob = builder.CreateNumpyVector(self.audioBlob)
            else:
                SensorBatchStartAudioBlobVector(builder, len(self.audioBlob))
                for i in reversed(range(len(self.audioBlob))):
                    builder.PrependUint8(self.audioBlob[i])
                audioBlob = builder.EndVector()
        if self.audioMetadata is not None:
            SensorBatchStartAudioMetadataVector(builder, len(self.audioMetadata))
            for i in reversed(range(len(self.audioMetadata))):
                self.audioMetadata[i].Pack(builder)
            audioMetadata = builder.EndVector()
        if self.videoBlob is not None:
            if np is not None and type(self.videoBlob) is np.ndarray:
                videoBlob = builder.CreateNumpyVector(self.videoBlob)
            else:
                SensorBatchStartVideoBlobVector(builder, len(self.videoBlob))
                for i in reversed(range(len(self.videoBlob))):
                    builder.PrependUint8(self.videoBlob[i])
                videoBlob = builder.EndVector()
        if self.videoMetadata is not None:
            SensorBatchStartVideoMetadataVector(builder, len(self.videoMetadata))
            for i in reversed(range(len(self.videoMetadata))):
                self.videoMetadata[i].Pack(builder)
            videoMetadata = builder.EndVector()
        SensorBatchStart(builder)
        SensorBatchAddBaseTimestamp(builder, self.baseTimestamp)
        if self.proximity is not None:
            SensorBatchAddProximity(builder, proximity)
        if self.tof is not None:
            SensorBatchAddTof(builder, tof)
        if self.battery is not None:
            SensorBatchAddBattery(builder, battery)
        if self.encoder is not None:
            SensorBatchAddEncoder(builder, encoder)
        if self.imu is not None:
            SensorBatchAddImu(builder, imu)
        if self.audioBlob is not None:
            SensorBatchAddAudioBlob(builder, audioBlob)
        if self.audioMetadata is not None:
            SensorBatchAddAudioMetadata(builder, audioMetadata)
        if self.videoBlob is not None:
            SensorBatchAddVideoBlob(builder, videoBlob)
        if self.videoMetadata is not None:
            SensorBatchAddVideoMetadata(builder, videoMetadata)
        sensorBatch = SensorBatchEnd(builder)
        return sensorBatch


