# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sensors

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Uint16Array8(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Uint16Array8
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Uint16Array8
    def A0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Uint16Array8
    def A1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # Uint16Array8
    def A2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Uint16Array8
    def A3(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # Uint16Array8
    def A4(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Uint16Array8
    def A5(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # Uint16Array8
    def A6(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # Uint16Array8
    def A7(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))

def CreateUint16Array8(builder, a0, a1, a2, a3, a4, a5, a6, a7):
    builder.Prep(2, 16)
    builder.PrependUint16(a7)
    builder.PrependUint16(a6)
    builder.PrependUint16(a5)
    builder.PrependUint16(a4)
    builder.PrependUint16(a3)
    builder.PrependUint16(a2)
    builder.PrependUint16(a1)
    builder.PrependUint16(a0)
    return builder.Offset()


class Uint16Array8T(object):

    # Uint16Array8T
    def __init__(
        self,
        a0 = 0,
        a1 = 0,
        a2 = 0,
        a3 = 0,
        a4 = 0,
        a5 = 0,
        a6 = 0,
        a7 = 0,
    ):
        self.a0 = a0  # type: int
        self.a1 = a1  # type: int
        self.a2 = a2  # type: int
        self.a3 = a3  # type: int
        self.a4 = a4  # type: int
        self.a5 = a5  # type: int
        self.a6 = a6  # type: int
        self.a7 = a7  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uint16Array8 = Uint16Array8()
        uint16Array8.Init(buf, pos)
        return cls.InitFromObj(uint16Array8)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uint16Array8):
        x = Uint16Array8T()
        x._UnPack(uint16Array8)
        return x

    # Uint16Array8T
    def _UnPack(self, uint16Array8):
        if uint16Array8 is None:
            return
        self.a0 = uint16Array8.A0()
        self.a1 = uint16Array8.A1()
        self.a2 = uint16Array8.A2()
        self.a3 = uint16Array8.A3()
        self.a4 = uint16Array8.A4()
        self.a5 = uint16Array8.A5()
        self.a6 = uint16Array8.A6()
        self.a7 = uint16Array8.A7()

    # Uint16Array8T
    def Pack(self, builder):
        return CreateUint16Array8(builder, self.a0, self.a1, self.a2, self.a3, self.a4, self.a5, self.a6, self.a7)


class ProximityData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 36

    # ProximityData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProximityData
    def Proximity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # ProximityData
    def AmbientLight(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # ProximityData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # ProximityData
    def Padding(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(34))

def CreateProximityData(builder, proximity_a0, proximity_a1, proximity_a2, proximity_a3, proximity_a4, proximity_a5, proximity_a6, proximity_a7, ambientLight_a0, ambientLight_a1, ambientLight_a2, ambientLight_a3, ambientLight_a4, ambientLight_a5, ambientLight_a6, ambientLight_a7, timestampOffset, padding):
    builder.Prep(2, 36)
    builder.PrependUint16(padding)
    builder.PrependUint16(timestampOffset)
    builder.Prep(2, 16)
    builder.PrependUint16(ambientLight_a7)
    builder.PrependUint16(ambientLight_a6)
    builder.PrependUint16(ambientLight_a5)
    builder.PrependUint16(ambientLight_a4)
    builder.PrependUint16(ambientLight_a3)
    builder.PrependUint16(ambientLight_a2)
    builder.PrependUint16(ambientLight_a1)
    builder.PrependUint16(ambientLight_a0)
    builder.Prep(2, 16)
    builder.PrependUint16(proximity_a7)
    builder.PrependUint16(proximity_a6)
    builder.PrependUint16(proximity_a5)
    builder.PrependUint16(proximity_a4)
    builder.PrependUint16(proximity_a3)
    builder.PrependUint16(proximity_a2)
    builder.PrependUint16(proximity_a1)
    builder.PrependUint16(proximity_a0)
    return builder.Offset()

try:
    from typing import Optional
except:
    pass

class ProximityDataT(object):

    # ProximityDataT
    def __init__(
        self,
        proximity = None,
        ambientLight = None,
        timestampOffset = 0,
        padding = 0,
    ):
        self.proximity = proximity  # type: Optional[Uint16Array8T]
        self.ambientLight = ambientLight  # type: Optional[Uint16Array8T]
        self.timestampOffset = timestampOffset  # type: int
        self.padding = padding  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        proximityData = ProximityData()
        proximityData.Init(buf, pos)
        return cls.InitFromObj(proximityData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, proximityData):
        x = ProximityDataT()
        x._UnPack(proximityData)
        return x

    # ProximityDataT
    def _UnPack(self, proximityData):
        if proximityData is None:
            return
        if proximityData.Proximity(Uint16Array8()) is not None:
            self.proximity = Uint16Array8T.InitFromObj(proximityData.Proximity(Uint16Array8()))
        if proximityData.AmbientLight(Uint16Array8()) is not None:
            self.ambientLight = Uint16Array8T.InitFromObj(proximityData.AmbientLight(Uint16Array8()))
        self.timestampOffset = proximityData.TimestampOffset()
        self.padding = proximityData.Padding()

    # ProximityDataT
    def Pack(self, builder):
        return CreateProximityData(builder, self.proximity.a0, self.proximity.a1, self.proximity.a2, self.proximity.a3, self.proximity.a4, self.proximity.a5, self.proximity.a6, self.proximity.a7, self.ambientLight.a0, self.ambientLight.a1, self.ambientLight.a2, self.ambientLight.a3, self.ambientLight.a4, self.ambientLight.a5, self.ambientLight.a6, self.ambientLight.a7, self.timestampOffset, self.padding)


class GroundArray(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 10

    # GroundArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroundArray
    def G0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # GroundArray
    def G1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # GroundArray
    def G2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # GroundArray
    def Cliff0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # GroundArray
    def Cliff1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateGroundArray(builder, g0, g1, g2, cliff0, cliff1):
    builder.Prep(2, 10)
    builder.PrependUint16(cliff1)
    builder.PrependUint16(cliff0)
    builder.PrependUint16(g2)
    builder.PrependUint16(g1)
    builder.PrependUint16(g0)
    return builder.Offset()


class GroundArrayT(object):

    # GroundArrayT
    def __init__(
        self,
        g0 = 0,
        g1 = 0,
        g2 = 0,
        cliff0 = 0,
        cliff1 = 0,
    ):
        self.g0 = g0  # type: int
        self.g1 = g1  # type: int
        self.g2 = g2  # type: int
        self.cliff0 = cliff0  # type: int
        self.cliff1 = cliff1  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        groundArray = GroundArray()
        groundArray.Init(buf, pos)
        return cls.InitFromObj(groundArray)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, groundArray):
        x = GroundArrayT()
        x._UnPack(groundArray)
        return x

    # GroundArrayT
    def _UnPack(self, groundArray):
        if groundArray is None:
            return
        self.g0 = groundArray.G0()
        self.g1 = groundArray.G1()
        self.g2 = groundArray.G2()
        self.cliff0 = groundArray.Cliff0()
        self.cliff1 = groundArray.Cliff1()

    # GroundArrayT
    def Pack(self, builder):
        return CreateGroundArray(builder, self.g0, self.g1, self.g2, self.cliff0, self.cliff1)


class GroundData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 22

    # GroundData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroundData
    def Ambient(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # GroundData
    def Delta(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 10)
        return obj

    # GroundData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateGroundData(builder, ambient_g0, ambient_g1, ambient_g2, ambient_cliff0, ambient_cliff1, delta_g0, delta_g1, delta_g2, delta_cliff0, delta_cliff1, timestampOffset):
    builder.Prep(2, 22)
    builder.PrependUint16(timestampOffset)
    builder.Prep(2, 10)
    builder.PrependUint16(delta_cliff1)
    builder.PrependUint16(delta_cliff0)
    builder.PrependUint16(delta_g2)
    builder.PrependUint16(delta_g1)
    builder.PrependUint16(delta_g0)
    builder.Prep(2, 10)
    builder.PrependUint16(ambient_cliff1)
    builder.PrependUint16(ambient_cliff0)
    builder.PrependUint16(ambient_g2)
    builder.PrependUint16(ambient_g1)
    builder.PrependUint16(ambient_g0)
    return builder.Offset()

try:
    from typing import Optional
except:
    pass

class GroundDataT(object):

    # GroundDataT
    def __init__(
        self,
        ambient = None,
        delta = None,
        timestampOffset = 0,
    ):
        self.ambient = ambient  # type: Optional[GroundArrayT]
        self.delta = delta  # type: Optional[GroundArrayT]
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        groundData = GroundData()
        groundData.Init(buf, pos)
        return cls.InitFromObj(groundData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, groundData):
        x = GroundDataT()
        x._UnPack(groundData)
        return x

    # GroundDataT
    def _UnPack(self, groundData):
        if groundData is None:
            return
        if groundData.Ambient(GroundArray()) is not None:
            self.ambient = GroundArrayT.InitFromObj(groundData.Ambient(GroundArray()))
        if groundData.Delta(GroundArray()) is not None:
            self.delta = GroundArrayT.InitFromObj(groundData.Delta(GroundArray()))
        self.timestampOffset = groundData.TimestampOffset()

    # GroundDataT
    def Pack(self, builder):
        return CreateGroundData(builder, self.ambient.g0, self.ambient.g1, self.ambient.g2, self.ambient.cliff0, self.ambient.cliff1, self.delta.g0, self.delta.g1, self.delta.g2, self.delta.cliff0, self.delta.cliff1, self.timestampOffset)


class TofData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # TofData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TofData
    def Distance(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TofData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateTofData(builder, distance, timestampOffset):
    builder.Prep(2, 4)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(distance)
    return builder.Offset()


class TofDataT(object):

    # TofDataT
    def __init__(
        self,
        distance = 0,
        timestampOffset = 0,
    ):
        self.distance = distance  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tofData = TofData()
        tofData.Init(buf, pos)
        return cls.InitFromObj(tofData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tofData):
        x = TofDataT()
        x._UnPack(tofData)
        return x

    # TofDataT
    def _UnPack(self, tofData):
        if tofData is None:
            return
        self.distance = tofData.Distance()
        self.timestampOffset = tofData.TimestampOffset()

    # TofDataT
    def Pack(self, builder):
        return CreateTofData(builder, self.distance, self.timestampOffset)


class BatteryData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # BatteryData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatteryData
    def Millivolts(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # BatteryData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateBatteryData(builder, millivolts, timestampOffset):
    builder.Prep(2, 4)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(millivolts)
    return builder.Offset()


class BatteryDataT(object):

    # BatteryDataT
    def __init__(
        self,
        millivolts = 0,
        timestampOffset = 0,
    ):
        self.millivolts = millivolts  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        batteryData = BatteryData()
        batteryData.Init(buf, pos)
        return cls.InitFromObj(batteryData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, batteryData):
        x = BatteryDataT()
        x._UnPack(batteryData)
        return x

    # BatteryDataT
    def _UnPack(self, batteryData):
        if batteryData is None:
            return
        self.millivolts = batteryData.Millivolts()
        self.timestampOffset = batteryData.TimestampOffset()

    # BatteryDataT
    def Pack(self, builder):
        return CreateBatteryData(builder, self.millivolts, self.timestampOffset)


class EncoderData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # EncoderData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncoderData
    def LeftSteps(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EncoderData
    def RightSteps(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # EncoderData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EncoderData
    def Padding(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))

def CreateEncoderData(builder, leftSteps, rightSteps, timestampOffset, padding):
    builder.Prep(4, 12)
    builder.PrependUint16(padding)
    builder.PrependUint16(timestampOffset)
    builder.PrependInt32(rightSteps)
    builder.PrependInt32(leftSteps)
    return builder.Offset()


class EncoderDataT(object):

    # EncoderDataT
    def __init__(
        self,
        leftSteps = 0,
        rightSteps = 0,
        timestampOffset = 0,
        padding = 0,
    ):
        self.leftSteps = leftSteps  # type: int
        self.rightSteps = rightSteps  # type: int
        self.timestampOffset = timestampOffset  # type: int
        self.padding = padding  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        encoderData = EncoderData()
        encoderData.Init(buf, pos)
        return cls.InitFromObj(encoderData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, encoderData):
        x = EncoderDataT()
        x._UnPack(encoderData)
        return x

    # EncoderDataT
    def _UnPack(self, encoderData):
        if encoderData is None:
            return
        self.leftSteps = encoderData.LeftSteps()
        self.rightSteps = encoderData.RightSteps()
        self.timestampOffset = encoderData.TimestampOffset()
        self.padding = encoderData.Padding()

    # EncoderDataT
    def Pack(self, builder):
        return CreateEncoderData(builder, self.leftSteps, self.rightSteps, self.timestampOffset, self.padding)


class Vector3f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # Vector3f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vector3f
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vector3f
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Vector3f
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateVector3f(builder, x, y, z):
    builder.Prep(4, 12)
    builder.PrependFloat32(z)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class Vector3fT(object):

    # Vector3fT
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.z = z  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vector3f = Vector3f()
        vector3f.Init(buf, pos)
        return cls.InitFromObj(vector3f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vector3f):
        x = Vector3fT()
        x._UnPack(vector3f)
        return x

    # Vector3fT
    def _UnPack(self, vector3f):
        if vector3f is None:
            return
        self.x = vector3f.X()
        self.y = vector3f.Y()
        self.z = vector3f.Z()

    # Vector3fT
    def Pack(self, builder):
        return CreateVector3f(builder, self.x, self.y, self.z)


class ImuData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 44

    # ImuData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImuData
    def Accelerometer(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # ImuData
    def Gyroscope(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

    # ImuData
    def Magnetometer(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # ImuData
    def Temperature(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))
    # ImuData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))

def CreateImuData(builder, accelerometer_x, accelerometer_y, accelerometer_z, gyroscope_x, gyroscope_y, gyroscope_z, magnetometer_x, magnetometer_y, magnetometer_z, temperature, timestampOffset):
    builder.Prep(4, 44)
    builder.Pad(2)
    builder.PrependUint16(timestampOffset)
    builder.PrependFloat32(temperature)
    builder.Prep(4, 12)
    builder.PrependFloat32(magnetometer_z)
    builder.PrependFloat32(magnetometer_y)
    builder.PrependFloat32(magnetometer_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(gyroscope_z)
    builder.PrependFloat32(gyroscope_y)
    builder.PrependFloat32(gyroscope_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(accelerometer_z)
    builder.PrependFloat32(accelerometer_y)
    builder.PrependFloat32(accelerometer_x)
    return builder.Offset()

try:
    from typing import Optional
except:
    pass

class ImuDataT(object):

    # ImuDataT
    def __init__(
        self,
        accelerometer = None,
        gyroscope = None,
        magnetometer = None,
        temperature = 0.0,
        timestampOffset = 0,
    ):
        self.accelerometer = accelerometer  # type: Optional[Vector3fT]
        self.gyroscope = gyroscope  # type: Optional[Vector3fT]
        self.magnetometer = magnetometer  # type: Optional[Vector3fT]
        self.temperature = temperature  # type: float
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        imuData = ImuData()
        imuData.Init(buf, pos)
        return cls.InitFromObj(imuData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, imuData):
        x = ImuDataT()
        x._UnPack(imuData)
        return x

    # ImuDataT
    def _UnPack(self, imuData):
        if imuData is None:
            return
        if imuData.Accelerometer(Vector3f()) is not None:
            self.accelerometer = Vector3fT.InitFromObj(imuData.Accelerometer(Vector3f()))
        if imuData.Gyroscope(Vector3f()) is not None:
            self.gyroscope = Vector3fT.InitFromObj(imuData.Gyroscope(Vector3f()))
        if imuData.Magnetometer(Vector3f()) is not None:
            self.magnetometer = Vector3fT.InitFromObj(imuData.Magnetometer(Vector3f()))
        self.temperature = imuData.Temperature()
        self.timestampOffset = imuData.TimestampOffset()

    # ImuDataT
    def Pack(self, builder):
        return CreateImuData(builder, self.accelerometer.x, self.accelerometer.y, self.accelerometer.z, self.gyroscope.x, self.gyroscope.y, self.gyroscope.z, self.magnetometer.x, self.magnetometer.y, self.magnetometer.z, self.temperature, self.timestampOffset)


class VolumeData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 10

    # VolumeData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VolumeData
    def M0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VolumeData
    def M1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # VolumeData
    def M2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # VolumeData
    def M3(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # VolumeData
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateVolumeData(builder, m0, m1, m2, m3, timestampOffset):
    builder.Prep(2, 10)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(m3)
    builder.PrependUint16(m2)
    builder.PrependUint16(m1)
    builder.PrependUint16(m0)
    return builder.Offset()


class VolumeDataT(object):

    # VolumeDataT
    def __init__(
        self,
        m0 = 0,
        m1 = 0,
        m2 = 0,
        m3 = 0,
        timestampOffset = 0,
    ):
        self.m0 = m0  # type: int
        self.m1 = m1  # type: int
        self.m2 = m2  # type: int
        self.m3 = m3  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        volumeData = VolumeData()
        volumeData.Init(buf, pos)
        return cls.InitFromObj(volumeData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, volumeData):
        x = VolumeDataT()
        x._UnPack(volumeData)
        return x

    # VolumeDataT
    def _UnPack(self, volumeData):
        if volumeData is None:
            return
        self.m0 = volumeData.M0()
        self.m1 = volumeData.M1()
        self.m2 = volumeData.M2()
        self.m3 = volumeData.M3()
        self.timestampOffset = volumeData.TimestampOffset()

    # VolumeDataT
    def Pack(self, builder):
        return CreateVolumeData(builder, self.m0, self.m1, self.m2, self.m3, self.timestampOffset)


class AudioMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # AudioMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioMetadata
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AudioMetadata
    def Length(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # AudioMetadata
    def SampleCount(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # AudioMetadata
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))

def CreateAudioMetadata(builder, offset, length, sampleCount, timestampOffset):
    builder.Prep(2, 8)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(sampleCount)
    builder.PrependUint16(length)
    builder.PrependUint16(offset)
    return builder.Offset()


class AudioMetadataT(object):

    # AudioMetadataT
    def __init__(
        self,
        offset = 0,
        length = 0,
        sampleCount = 0,
        timestampOffset = 0,
    ):
        self.offset = offset  # type: int
        self.length = length  # type: int
        self.sampleCount = sampleCount  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        audioMetadata = AudioMetadata()
        audioMetadata.Init(buf, pos)
        return cls.InitFromObj(audioMetadata)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, audioMetadata):
        x = AudioMetadataT()
        x._UnPack(audioMetadata)
        return x

    # AudioMetadataT
    def _UnPack(self, audioMetadata):
        if audioMetadata is None:
            return
        self.offset = audioMetadata.Offset()
        self.length = audioMetadata.Length()
        self.sampleCount = audioMetadata.SampleCount()
        self.timestampOffset = audioMetadata.TimestampOffset()

    # AudioMetadataT
    def Pack(self, builder):
        return CreateAudioMetadata(builder, self.offset, self.length, self.sampleCount, self.timestampOffset)


class VideoMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # VideoMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VideoMetadata
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VideoMetadata
    def Length(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # VideoMetadata
    def FrameId(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # VideoMetadata
    def FragmentIndex(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # VideoMetadata
    def TotalFragments(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))
    # VideoMetadata
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # VideoMetadata
    def TimestampOffset(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))

def CreateVideoMetadata(builder, offset, length, frameId, fragmentIndex, totalFragments, flags, timestampOffset):
    builder.Prep(4, 16)
    builder.PrependUint16(timestampOffset)
    builder.PrependUint16(flags)
    builder.PrependUint8(totalFragments)
    builder.PrependUint8(fragmentIndex)
    builder.PrependUint16(frameId)
    builder.PrependUint32(length)
    builder.PrependUint32(offset)
    return builder.Offset()


class VideoMetadataT(object):

    # VideoMetadataT
    def __init__(
        self,
        offset = 0,
        length = 0,
        frameId = 0,
        fragmentIndex = 0,
        totalFragments = 0,
        flags = 0,
        timestampOffset = 0,
    ):
        self.offset = offset  # type: int
        self.length = length  # type: int
        self.frameId = frameId  # type: int
        self.fragmentIndex = fragmentIndex  # type: int
        self.totalFragments = totalFragments  # type: int
        self.flags = flags  # type: int
        self.timestampOffset = timestampOffset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        videoMetadata = VideoMetadata()
        videoMetadata.Init(buf, pos)
        return cls.InitFromObj(videoMetadata)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, videoMetadata):
        x = VideoMetadataT()
        x._UnPack(videoMetadata)
        return x

    # VideoMetadataT
    def _UnPack(self, videoMetadata):
        if videoMetadata is None:
            return
        self.offset = videoMetadata.Offset()
        self.length = videoMetadata.Length()
        self.frameId = videoMetadata.FrameId()
        self.fragmentIndex = videoMetadata.FragmentIndex()
        self.totalFragments = videoMetadata.TotalFragments()
        self.flags = videoMetadata.Flags()
        self.timestampOffset = videoMetadata.TimestampOffset()

    # VideoMetadataT
    def Pack(self, builder):
        return CreateVideoMetadata(builder, self.offset, self.length, self.frameId, self.fragmentIndex, self.totalFragments, self.flags, self.timestampOffset)


class SensorBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SensorBatchBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x45\x4E\x53", size_prefixed=size_prefixed)

    # SensorBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorBatch
    def BaseTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorBatch
    def Proximity(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 36
            obj = ProximityData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def ProximityLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def ProximityIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SensorBatch
    def Ground(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 22
            obj = GroundData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def GroundLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def GroundIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SensorBatch
    def Tof(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = TofData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def TofLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def TofIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # SensorBatch
    def Battery(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = BatteryData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def BatteryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def BatteryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # SensorBatch
    def Encoder(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = EncoderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def EncoderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def EncoderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # SensorBatch
    def Imu(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 44
            obj = ImuData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def ImuLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def ImuIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # SensorBatch
    def AudioBlob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorBatch
    def AudioBlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorBatch
    def AudioBlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def AudioBlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # SensorBatch
    def AudioMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            obj = AudioMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def AudioMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def AudioMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # SensorBatch
    def VideoBlob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SensorBatch
    def VideoBlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SensorBatch
    def VideoBlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def VideoBlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # SensorBatch
    def VideoMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = VideoMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def VideoMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def VideoMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def SensorBatchStart(builder):
    builder.StartObject(11)

def SensorBatchAddBaseTimestamp(builder, baseTimestamp):
    builder.PrependUint64Slot(0, baseTimestamp, 0)

def SensorBatchAddProximity(builder, proximity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(proximity), 0)

def SensorBatchStartProximityVector(builder, numElems):
    return builder.StartVector(36, numElems, 2)

def SensorBatchCreateProximityVector(builder, data):
    data = list(data)
    builder.StartVector(36, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddGround(builder, ground):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ground), 0)

def SensorBatchStartGroundVector(builder, numElems):
    return builder.StartVector(22, numElems, 2)

def SensorBatchCreateGroundVector(builder, data):
    data = list(data)
    builder.StartVector(22, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddTof(builder, tof):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(tof), 0)

def SensorBatchStartTofVector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def SensorBatchCreateTofVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddBattery(builder, battery):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(battery), 0)

def SensorBatchStartBatteryVector(builder, numElems):
    return builder.StartVector(4, numElems, 2)

def SensorBatchCreateBatteryVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddEncoder(builder, encoder):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(encoder), 0)

def SensorBatchStartEncoderVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def SensorBatchCreateEncoderVector(builder, data):
    data = list(data)
    builder.StartVector(12, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddImu(builder, imu):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(imu), 0)

def SensorBatchStartImuVector(builder, numElems):
    return builder.StartVector(44, numElems, 4)

def SensorBatchCreateImuVector(builder, data):
    data = list(data)
    builder.StartVector(44, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddAudioBlob(builder, audioBlob):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(audioBlob), 0)

def SensorBatchStartAudioBlobVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SensorBatchCreateAudioBlobVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def SensorBatchAddAudioMetadata(builder, audioMetadata):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(audioMetadata), 0)

def SensorBatchStartAudioMetadataVector(builder, numElems):
    return builder.StartVector(8, numElems, 2)

def SensorBatchCreateAudioMetadataVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 2)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchAddVideoBlob(builder, videoBlob):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(videoBlob), 0)

def SensorBatchStartVideoBlobVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SensorBatchCreateVideoBlobVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def SensorBatchAddVideoMetadata(builder, videoMetadata):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(videoMetadata), 0)

def SensorBatchStartVideoMetadataVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def SensorBatchCreateVideoMetadataVector(builder, data):
    data = list(data)
    builder.StartVector(16, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def SensorBatchEnd(builder):
    return builder.EndObject()


try:
    from typing import List
except:
    pass

class SensorBatchT(object):

    # SensorBatchT
    def __init__(
        self,
        baseTimestamp = 0,
        proximity = None,
        ground = None,
        tof = None,
        battery = None,
        encoder = None,
        imu = None,
        audioBlob = None,
        audioMetadata = None,
        videoBlob = None,
        videoMetadata = None,
    ):
        self.baseTimestamp = baseTimestamp  # type: int
        self.proximity = proximity  # type: Optional[List[ProximityDataT]]
        self.ground = ground  # type: Optional[List[GroundDataT]]
        self.tof = tof  # type: Optional[List[TofDataT]]
        self.battery = battery  # type: Optional[List[BatteryDataT]]
        self.encoder = encoder  # type: Optional[List[EncoderDataT]]
        self.imu = imu  # type: Optional[List[ImuDataT]]
        self.audioBlob = audioBlob  # type: Optional[List[int]]
        self.audioMetadata = audioMetadata  # type: Optional[List[AudioMetadataT]]
        self.videoBlob = videoBlob  # type: Optional[List[int]]
        self.videoMetadata = videoMetadata  # type: Optional[List[VideoMetadataT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sensorBatch = SensorBatch()
        sensorBatch.Init(buf, pos)
        return cls.InitFromObj(sensorBatch)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sensorBatch):
        x = SensorBatchT()
        x._UnPack(sensorBatch)
        return x

    # SensorBatchT
    def _UnPack(self, sensorBatch):
        if sensorBatch is None:
            return
        self.baseTimestamp = sensorBatch.BaseTimestamp()
        if not sensorBatch.ProximityIsNone():
            self.proximity = []
            for i in range(sensorBatch.ProximityLength()):
                if sensorBatch.Proximity(i) is None:
                    self.proximity.append(None)
                else:
                    proximityData_ = ProximityDataT.InitFromObj(sensorBatch.Proximity(i))
                    self.proximity.append(proximityData_)
        if not sensorBatch.GroundIsNone():
            self.ground = []
            for i in range(sensorBatch.GroundLength()):
                if sensorBatch.Ground(i) is None:
                    self.ground.append(None)
                else:
                    groundData_ = GroundDataT.InitFromObj(sensorBatch.Ground(i))
                    self.ground.append(groundData_)
        if not sensorBatch.TofIsNone():
            self.tof = []
            for i in range(sensorBatch.TofLength()):
                if sensorBatch.Tof(i) is None:
                    self.tof.append(None)
                else:
                    tofData_ = TofDataT.InitFromObj(sensorBatch.Tof(i))
                    self.tof.append(tofData_)
        if not sensorBatch.BatteryIsNone():
            self.battery = []
            for i in range(sensorBatch.BatteryLength()):
                if sensorBatch.Battery(i) is None:
                    self.battery.append(None)
                else:
                    batteryData_ = BatteryDataT.InitFromObj(sensorBatch.Battery(i))
                    self.battery.append(batteryData_)
        if not sensorBatch.EncoderIsNone():
            self.encoder = []
            for i in range(sensorBatch.EncoderLength()):
                if sensorBatch.Encoder(i) is None:
                    self.encoder.append(None)
                else:
                    encoderData_ = EncoderDataT.InitFromObj(sensorBatch.Encoder(i))
                    self.encoder.append(encoderData_)
        if not sensorBatch.ImuIsNone():
            self.imu = []
            for i in range(sensorBatch.ImuLength()):
                if sensorBatch.Imu(i) is None:
                    self.imu.append(None)
                else:
                    imuData_ = ImuDataT.InitFromObj(sensorBatch.Imu(i))
                    self.imu.append(imuData_)
        if not sensorBatch.AudioBlobIsNone():
            if np is None:
                self.audioBlob = []
                for i in range(sensorBatch.AudioBlobLength()):
                    self.audioBlob.append(sensorBatch.AudioBlob(i))
            else:
                self.audioBlob = sensorBatch.AudioBlobAsNumpy()
        if not sensorBatch.AudioMetadataIsNone():
            self.audioMetadata = []
            for i in range(sensorBatch.AudioMetadataLength()):
                if sensorBatch.AudioMetadata(i) is None:
                    self.audioMetadata.append(None)
                else:
                    audioMetadata_ = AudioMetadataT.InitFromObj(sensorBatch.AudioMetadata(i))
                    self.audioMetadata.append(audioMetadata_)
        if not sensorBatch.VideoBlobIsNone():
            if np is None:
                self.videoBlob = []
                for i in range(sensorBatch.VideoBlobLength()):
                    self.videoBlob.append(sensorBatch.VideoBlob(i))
            else:
                self.videoBlob = sensorBatch.VideoBlobAsNumpy()
        if not sensorBatch.VideoMetadataIsNone():
            self.videoMetadata = []
            for i in range(sensorBatch.VideoMetadataLength()):
                if sensorBatch.VideoMetadata(i) is None:
                    self.videoMetadata.append(None)
                else:
                    videoMetadata_ = VideoMetadataT.InitFromObj(sensorBatch.VideoMetadata(i))
                    self.videoMetadata.append(videoMetadata_)

    # SensorBatchT
    def Pack(self, builder):
        if self.proximity is not None:
            SensorBatchStartProximityVector(builder, len(self.proximity))
            for i in reversed(range(len(self.proximity))):
                self.proximity[i].Pack(builder)
            proximity = builder.EndVector()
        if self.ground is not None:
            SensorBatchStartGroundVector(builder, len(self.ground))
            for i in reversed(range(len(self.ground))):
                self.ground[i].Pack(builder)
            ground = builder.EndVector()
        if self.tof is not None:
            SensorBatchStartTofVector(builder, len(self.tof))
            for i in reversed(range(len(self.tof))):
                self.tof[i].Pack(builder)
            tof = builder.EndVector()
        if self.battery is not None:
            SensorBatchStartBatteryVector(builder, len(self.battery))
            for i in reversed(range(len(self.battery))):
                self.battery[i].Pack(builder)
            battery = builder.EndVector()
        if self.encoder is not None:
            SensorBatchStartEncoderVector(builder, len(self.encoder))
            for i in reversed(range(len(self.encoder))):
                self.encoder[i].Pack(builder)
            encoder = builder.EndVector()
        if self.imu is not None:
            SensorBatchStartImuVector(builder, len(self.imu))
            for i in reversed(range(len(self.imu))):
                self.imu[i].Pack(builder)
            imu = builder.EndVector()
        if self.audioBlob is not None:
            if np is not None and type(self.audioBlob) is np.ndarray:
                audioBlob = builder.CreateNumpyVector(self.audioBlob)
            else:
                SensorBatchStartAudioBlobVector(builder, len(self.audioBlob))
                for i in reversed(range(len(self.audioBlob))):
                    builder.PrependUint8(self.audioBlob[i])
                audioBlob = builder.EndVector()
        if self.audioMetadata is not None:
            SensorBatchStartAudioMetadataVector(builder, len(self.audioMetadata))
            for i in reversed(range(len(self.audioMetadata))):
                self.audioMetadata[i].Pack(builder)
            audioMetadata = builder.EndVector()
        if self.videoBlob is not None:
            if np is not None and type(self.videoBlob) is np.ndarray:
                videoBlob = builder.CreateNumpyVector(self.videoBlob)
            else:
                SensorBatchStartVideoBlobVector(builder, len(self.videoBlob))
                for i in reversed(range(len(self.videoBlob))):
                    builder.PrependUint8(self.videoBlob[i])
                videoBlob = builder.EndVector()
        if self.videoMetadata is not None:
            SensorBatchStartVideoMetadataVector(builder, len(self.videoMetadata))
            for i in reversed(range(len(self.videoMetadata))):
                self.videoMetadata[i].Pack(builder)
            videoMetadata = builder.EndVector()
        SensorBatchStart(builder)
        SensorBatchAddBaseTimestamp(builder, self.baseTimestamp)
        if self.proximity is not None:
            SensorBatchAddProximity(builder, proximity)
        if self.ground is not None:
            SensorBatchAddGround(builder, ground)
        if self.tof is not None:
            SensorBatchAddTof(builder, tof)
        if self.battery is not None:
            SensorBatchAddBattery(builder, battery)
        if self.encoder is not None:
            SensorBatchAddEncoder(builder, encoder)
        if self.imu is not None:
            SensorBatchAddImu(builder, imu)
        if self.audioBlob is not None:
            SensorBatchAddAudioBlob(builder, audioBlob)
        if self.audioMetadata is not None:
            SensorBatchAddAudioMetadata(builder, audioMetadata)
        if self.videoBlob is not None:
            SensorBatchAddVideoBlob(builder, videoBlob)
        if self.videoMetadata is not None:
            SensorBatchAddVideoMetadata(builder, videoMetadata)
        sensorBatch = SensorBatchEnd(builder)
        return sensorBatch


