# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Batch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Batch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Batch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Batch
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FripuckProtocol.Commands.Command import Command
            obj = Command()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Batch
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Batch
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BatchStart(builder):
    builder.StartObject(1)

def Start(builder):
    BatchStart(builder)

def BatchAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

def AddEntries(builder, entries):
    BatchAddEntries(builder, entries)

def BatchStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntriesVector(builder, numElems):
    return BatchStartEntriesVector(builder, numElems)

def BatchCreateEntriesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateEntriesVector(builder, data):
    return BatchCreateEntriesVector(builder, data)

def BatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return BatchEnd(builder)

import FripuckProtocol.Commands.Command
try:
    from typing import List
except:
    pass

class BatchT(object):

    # BatchT
    def __init__(
        self,
        entries = None,
    ):
        self.entries = entries  # type: Optional[List[FripuckProtocol.Commands.Command.CommandT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        batch = Batch()
        batch.Init(buf, pos)
        return cls.InitFromObj(batch)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, batch):
        x = BatchT()
        x._UnPack(batch)
        return x

    # BatchT
    def _UnPack(self, batch):
        if batch is None:
            return
        if not batch.EntriesIsNone():
            self.entries = []
            for i in range(batch.EntriesLength()):
                if batch.Entries(i) is None:
                    self.entries.append(None)
                else:
                    command_ = FripuckProtocol.Commands.Command.CommandT.InitFromObj(batch.Entries(i))
                    self.entries.append(command_)

    # BatchT
    def Pack(self, builder):
        if self.entries is not None:
            entrieslist = []
            for i in range(len(self.entries)):
                entrieslist.append(self.entries[i].Pack(builder))
            BatchStartEntriesVector(builder, len(self.entries))
            for i in reversed(range(len(self.entries))):
                builder.PrependUOffsetTRelative(entrieslist[i])
            entries = builder.EndVector()
        BatchStart(builder)
        if self.entries is not None:
            BatchAddEntries(builder, entries)
        batch = BatchEnd(builder)
        return batch
