# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Command(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Command()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Command
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Command
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Command
    def ContentType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Command
    def Content(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CommandStart(builder):
    builder.StartObject(3)

def Start(builder):
    CommandStart(builder)

def CommandAddTimestamp(builder, timestamp):
    builder.PrependUint16Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    CommandAddTimestamp(builder, timestamp)

def CommandAddContentType(builder, contentType):
    builder.PrependUint8Slot(1, contentType, 0)

def AddContentType(builder, contentType):
    CommandAddContentType(builder, contentType)

def CommandAddContent(builder, content):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder, content):
    CommandAddContent(builder, content)

def CommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandEnd(builder)

import FripuckProtocol.Commands.DummyConfig
import FripuckProtocol.Commands.InfoMessage
import FripuckProtocol.Commands.Instruction
try:
    from typing import Union
except:
    pass

class CommandT(object):

    # CommandT
    def __init__(
        self,
        timestamp = 0,
        contentType = 0,
        content = None,
    ):
        self.timestamp = timestamp  # type: int
        self.contentType = contentType  # type: int
        self.content = content  # type: Union[None, 'FripuckProtocol.Commands.DummyConfig.DummyConfigT', 'FripuckProtocol.Commands.InfoMessage.InfoMessageT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        command = Command()
        command.Init(buf, pos)
        return cls.InitFromObj(command)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, command):
        x = CommandT()
        x._UnPack(command)
        return x

    # CommandT
    def _UnPack(self, command):
        if command is None:
            return
        self.timestamp = command.Timestamp()
        self.contentType = command.ContentType()
        self.content = FripuckProtocol.Commands.Instruction.InstructionCreator(self.contentType, command.Content())

    # CommandT
    def Pack(self, builder):
        if self.content is not None:
            content = self.content.Pack(builder)
        CommandStart(builder)
        CommandAddTimestamp(builder, self.timestamp)
        CommandAddContentType(builder, self.contentType)
        if self.content is not None:
            CommandAddContent(builder, content)
        command = CommandEnd(builder)
        return command
