# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DummyConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DummyConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDummyConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DummyConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DummyConfig
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def DummyConfigStart(builder):
    builder.StartObject(1)

def Start(builder):
    DummyConfigStart(builder)

def DummyConfigAddValue(builder, value):
    builder.PrependUint32Slot(0, value, 0)

def AddValue(builder, value):
    DummyConfigAddValue(builder, value)

def DummyConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return DummyConfigEnd(builder)


class DummyConfigT(object):

    # DummyConfigT
    def __init__(
        self,
        value = 0,
    ):
        self.value = value  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dummyConfig = DummyConfig()
        dummyConfig.Init(buf, pos)
        return cls.InitFromObj(dummyConfig)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dummyConfig):
        x = DummyConfigT()
        x._UnPack(dummyConfig)
        return x

    # DummyConfigT
    def _UnPack(self, dummyConfig):
        if dummyConfig is None:
            return
        self.value = dummyConfig.Value()

    # DummyConfigT
    def Pack(self, builder):
        DummyConfigStart(builder)
        DummyConfigAddValue(builder, self.value)
        dummyConfig = DummyConfigEnd(builder)
        return dummyConfig
