# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InfoMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InfoMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInfoMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InfoMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InfoMessage
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InfoMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    InfoMessageStart(builder)

def InfoMessageAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder, text):
    InfoMessageAddText(builder, text)

def InfoMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return InfoMessageEnd(builder)


class InfoMessageT(object):

    # InfoMessageT
    def __init__(
        self,
        text = None,
    ):
        self.text = text  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        infoMessage = InfoMessage()
        infoMessage.Init(buf, pos)
        return cls.InitFromObj(infoMessage)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, infoMessage):
        x = InfoMessageT()
        x._UnPack(infoMessage)
        return x

    # InfoMessageT
    def _UnPack(self, infoMessage):
        if infoMessage is None:
            return
        self.text = infoMessage.Text()

    # InfoMessageT
    def Pack(self, builder):
        if self.text is not None:
            text = builder.CreateString(self.text)
        InfoMessageStart(builder)
        if self.text is not None:
            InfoMessageAddText(builder, text)
        infoMessage = InfoMessageEnd(builder)
        return infoMessage
