# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Commands

class Instruction(object):
    NONE = 0
    DummyConfig = 1
    InfoMessage = 2

def InstructionCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Instruction.DummyConfig:
        import FripuckProtocol.Commands.DummyConfig
        return FripuckProtocol.Commands.DummyConfig.DummyConfigT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Instruction.InfoMessage:
        import FripuckProtocol.Commands.InfoMessage
        return FripuckProtocol.Commands.InfoMessage.InfoMessageT.InitFromBuf(table.Bytes, table.Pos)
    return None
