# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Telemetry

class Data(object):
    NONE = 0
    InfoMessage = 1

def DataCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Data.InfoMessage:
        import FripuckProtocol.Telemetry.InfoMessage
        return FripuckProtocol.Telemetry.InfoMessage.InfoMessageT.InitFromBuf(table.Bytes, table.Pos)
    return None
