# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Telemetry

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Entry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Entry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x46\x52\x49\x32", size_prefixed=size_prefixed)

    # Entry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Entry
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Entry
    def ContentType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Entry
    def Content(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EntryStart(builder):
    builder.StartObject(3)

def Start(builder):
    EntryStart(builder)

def EntryAddTimestamp(builder, timestamp):
    builder.PrependUint16Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    EntryAddTimestamp(builder, timestamp)

def EntryAddContentType(builder, contentType):
    builder.PrependUint8Slot(1, contentType, 0)

def AddContentType(builder, contentType):
    EntryAddContentType(builder, contentType)

def EntryAddContent(builder, content):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder, content):
    EntryAddContent(builder, content)

def EntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntryEnd(builder)

import FripuckProtocol.Telemetry.Data
import FripuckProtocol.Telemetry.InfoMessage
try:
    from typing import Union
except:
    pass

class EntryT(object):

    # EntryT
    def __init__(
        self,
        timestamp = 0,
        contentType = 0,
        content = None,
    ):
        self.timestamp = timestamp  # type: int
        self.contentType = contentType  # type: int
        self.content = content  # type: Union[None, 'FripuckProtocol.Telemetry.InfoMessage.InfoMessageT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        entry = Entry()
        entry.Init(buf, pos)
        return cls.InitFromObj(entry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, entry):
        x = EntryT()
        x._UnPack(entry)
        return x

    # EntryT
    def _UnPack(self, entry):
        if entry is None:
            return
        self.timestamp = entry.Timestamp()
        self.contentType = entry.ContentType()
        self.content = FripuckProtocol.Telemetry.Data.DataCreator(self.contentType, entry.Content())

    # EntryT
    def Pack(self, builder):
        if self.content is not None:
            content = self.content.Pack(builder)
        EntryStart(builder)
        EntryAddTimestamp(builder, self.timestamp)
        EntryAddContentType(builder, self.contentType)
        if self.content is not None:
            EntryAddContent(builder, content)
        entry = EntryEnd(builder)
        return entry
