// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandT struct {
	Timestamp uint16 `json:"timestamp"`
	Content *InstructionT `json:"content"`
}

func (t *CommandT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	contentOffset := t.Content.Pack(builder)

	CommandStart(builder)
	CommandAddTimestamp(builder, t.Timestamp)
	if t.Content != nil {
		CommandAddContentType(builder, t.Content.Type)
	}
	CommandAddContent(builder, contentOffset)
	return CommandEnd(builder)
}

func (rcv *Command) UnPackTo(t *CommandT) {
	t.Timestamp = rcv.Timestamp()
	contentTable := flatbuffers.Table{}
	if rcv.Content(&contentTable) {
		t.Content = rcv.ContentType().UnPack(contentTable)
	}
}

func (rcv *Command) UnPack() *CommandT {
	if rcv == nil {
		return nil
	}
	t := &CommandT{}
	rcv.UnPackTo(t)
	return t
}

type Command struct {
	_tab flatbuffers.Table
}

func GetRootAsCommand(buf []byte, offset flatbuffers.UOffsetT) *Command {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Command{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommand(buf []byte, offset flatbuffers.UOffsetT) *Command {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Command{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Command) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Command) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Command) Timestamp() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Command) MutateTimestamp(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Command) ContentType() Instruction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Instruction(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Command) MutateContentType(n Instruction) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Command) Content(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CommandAddTimestamp(builder *flatbuffers.Builder, timestamp uint16) {
	builder.PrependUint16Slot(0, timestamp, 0)
}
func CommandAddContentType(builder *flatbuffers.Builder, contentType Instruction) {
	builder.PrependByteSlot(1, byte(contentType), 0)
}
func CommandAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(content), 0)
}
func CommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
