// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Commands

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DummyConfigT struct {
	Value uint32 `json:"value"`
}

func (t *DummyConfigT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	DummyConfigStart(builder)
	DummyConfigAddValue(builder, t.Value)
	return DummyConfigEnd(builder)
}

func (rcv *DummyConfig) UnPackTo(t *DummyConfigT) {
	t.Value = rcv.Value()
}

func (rcv *DummyConfig) UnPack() *DummyConfigT {
	if rcv == nil {
		return nil
	}
	t := &DummyConfigT{}
	rcv.UnPackTo(t)
	return t
}

type DummyConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsDummyConfig(buf []byte, offset flatbuffers.UOffsetT) *DummyConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DummyConfig{}
	x.Init(buf, n+offset)
	return x
}

func FinishDummyConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDummyConfig(buf []byte, offset flatbuffers.UOffsetT) *DummyConfig {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DummyConfig{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDummyConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DummyConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DummyConfig) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DummyConfig) Value() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DummyConfig) MutateValue(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func DummyConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DummyConfigAddValue(builder *flatbuffers.Builder, value uint32) {
	builder.PrependUint32Slot(0, value, 0)
}
func DummyConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
