// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EntryT struct {
	Timestamp uint16 `json:"timestamp"`
	Content *DataT `json:"content"`
}

func (t *EntryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	contentOffset := t.Content.Pack(builder)

	EntryStart(builder)
	EntryAddTimestamp(builder, t.Timestamp)
	if t.Content != nil {
		EntryAddContentType(builder, t.Content.Type)
	}
	EntryAddContent(builder, contentOffset)
	return EntryEnd(builder)
}

func (rcv *Entry) UnPackTo(t *EntryT) {
	t.Timestamp = rcv.Timestamp()
	contentTable := flatbuffers.Table{}
	if rcv.Content(&contentTable) {
		t.Content = rcv.ContentType().UnPack(contentTable)
	}
}

func (rcv *Entry) UnPack() *EntryT {
	if rcv == nil {
		return nil
	}
	t := &EntryT{}
	rcv.UnPackTo(t)
	return t
}

type Entry struct {
	_tab flatbuffers.Table
}

func GetRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Entry{}
	x.Init(buf, n+offset)
	return x
}

func FinishEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEntry(buf []byte, offset flatbuffers.UOffsetT) *Entry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Entry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Entry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Entry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Entry) Timestamp() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Entry) MutateTimestamp(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Entry) ContentType() Data {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Data(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Entry) MutateContentType(n Data) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Entry) Content(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func EntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EntryAddTimestamp(builder *flatbuffers.Builder, timestamp uint16) {
	builder.PrependUint16Slot(0, timestamp, 0)
}
func EntryAddContentType(builder *flatbuffers.Builder, contentType Data) {
	builder.PrependByteSlot(1, byte(contentType), 0)
}
func EntryAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(content), 0)
}
func EntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
