// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AudioMetadataT struct {
	Offset uint16 `json:"offset"`
	Length uint16 `json:"length"`
	SampleCount uint16 `json:"sample_count"`
	TimestampOffset uint16 `json:"timestamp_offset"`
}

func (t *AudioMetadataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateAudioMetadata(builder, t.Offset, t.Length, t.SampleCount, t.TimestampOffset)
}
func (rcv *AudioMetadata) UnPackTo(t *AudioMetadataT) {
	t.Offset = rcv.Offset()
	t.Length = rcv.Length()
	t.SampleCount = rcv.SampleCount()
	t.TimestampOffset = rcv.TimestampOffset()
}

func (rcv *AudioMetadata) UnPack() *AudioMetadataT {
	if rcv == nil {
		return nil
	}
	t := &AudioMetadataT{}
	rcv.UnPackTo(t)
	return t
}

type AudioMetadata struct {
	_tab flatbuffers.Struct
}

func (rcv *AudioMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AudioMetadata) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *AudioMetadata) Offset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *AudioMetadata) MutateOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *AudioMetadata) Length() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *AudioMetadata) MutateLength(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *AudioMetadata) SampleCount() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *AudioMetadata) MutateSampleCount(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *AudioMetadata) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *AudioMetadata) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func CreateAudioMetadata(builder *flatbuffers.Builder, offset uint16, length uint16, sampleCount uint16, timestampOffset uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 8)
	builder.PrependUint16(timestampOffset)
	builder.PrependUint16(sampleCount)
	builder.PrependUint16(length)
	builder.PrependUint16(offset)
	return builder.Offset()
}
