// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EncoderDataT struct {
	LeftSteps int32 `json:"left_steps"`
	RightSteps int32 `json:"right_steps"`
	TimestampOffset uint16 `json:"timestamp_offset"`
	Padding uint16 `json:"padding"`
}

func (t *EncoderDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateEncoderData(builder, t.LeftSteps, t.RightSteps, t.TimestampOffset, t.Padding)
}
func (rcv *EncoderData) UnPackTo(t *EncoderDataT) {
	t.LeftSteps = rcv.LeftSteps()
	t.RightSteps = rcv.RightSteps()
	t.TimestampOffset = rcv.TimestampOffset()
	t.Padding = rcv.Padding()
}

func (rcv *EncoderData) UnPack() *EncoderDataT {
	if rcv == nil {
		return nil
	}
	t := &EncoderDataT{}
	rcv.UnPackTo(t)
	return t
}

type EncoderData struct {
	_tab flatbuffers.Struct
}

func (rcv *EncoderData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EncoderData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *EncoderData) LeftSteps() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *EncoderData) MutateLeftSteps(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *EncoderData) RightSteps() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *EncoderData) MutateRightSteps(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *EncoderData) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *EncoderData) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *EncoderData) Padding() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *EncoderData) MutatePadding(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func CreateEncoderData(builder *flatbuffers.Builder, leftSteps int32, rightSteps int32, timestampOffset uint16, padding uint16) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependUint16(padding)
	builder.PrependUint16(timestampOffset)
	builder.PrependInt32(rightSteps)
	builder.PrependInt32(leftSteps)
	return builder.Offset()
}
