// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GroundDataT struct {
	Ambient *GroundArrayT `json:"ambient"`
	Delta *GroundArrayT `json:"delta"`
	TimestampOffset uint16 `json:"timestamp_offset"`
}

func (t *GroundDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateGroundData(builder, t.Ambient.G0, t.Ambient.G1, t.Ambient.G2, t.Ambient.Cliff0, t.Ambient.Cliff1, t.Delta.G0, t.Delta.G1, t.Delta.G2, t.Delta.Cliff0, t.Delta.Cliff1, t.TimestampOffset)
}
func (rcv *GroundData) UnPackTo(t *GroundDataT) {
	t.Ambient = rcv.Ambient(nil).UnPack()
	t.Delta = rcv.Delta(nil).UnPack()
	t.TimestampOffset = rcv.TimestampOffset()
}

func (rcv *GroundData) UnPack() *GroundDataT {
	if rcv == nil {
		return nil
	}
	t := &GroundDataT{}
	rcv.UnPackTo(t)
	return t
}

type GroundData struct {
	_tab flatbuffers.Struct
}

func (rcv *GroundData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GroundData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *GroundData) Ambient(obj *GroundArray) *GroundArray {
	if obj == nil {
		obj = new(GroundArray)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *GroundData) Delta(obj *GroundArray) *GroundArray {
	if obj == nil {
		obj = new(GroundArray)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+10)
	return obj
}
func (rcv *GroundData) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(20))
}
func (rcv *GroundData) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(20), n)
}

func CreateGroundData(builder *flatbuffers.Builder, ambient_g0 uint16, ambient_g1 uint16, ambient_g2 uint16, ambient_cliff0 uint16, ambient_cliff1 uint16, delta_g0 uint16, delta_g1 uint16, delta_g2 uint16, delta_cliff0 uint16, delta_cliff1 uint16, timestampOffset uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 22)
	builder.PrependUint16(timestampOffset)
	builder.Prep(2, 10)
	builder.PrependUint16(delta_cliff1)
	builder.PrependUint16(delta_cliff0)
	builder.PrependUint16(delta_g2)
	builder.PrependUint16(delta_g1)
	builder.PrependUint16(delta_g0)
	builder.Prep(2, 10)
	builder.PrependUint16(ambient_cliff1)
	builder.PrependUint16(ambient_cliff0)
	builder.PrependUint16(ambient_g2)
	builder.PrependUint16(ambient_g1)
	builder.PrependUint16(ambient_g0)
	return builder.Offset()
}
