// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GroundArrayT struct {
	G0 uint16 `json:"g0"`
	G1 uint16 `json:"g1"`
	G2 uint16 `json:"g2"`
	Cliff0 uint16 `json:"cliff0"`
	Cliff1 uint16 `json:"cliff1"`
}

func (t *GroundArrayT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateGroundArray(builder, t.G0, t.G1, t.G2, t.Cliff0, t.Cliff1)
}
func (rcv *GroundArray) UnPackTo(t *GroundArrayT) {
	t.G0 = rcv.G0()
	t.G1 = rcv.G1()
	t.G2 = rcv.G2()
	t.Cliff0 = rcv.Cliff0()
	t.Cliff1 = rcv.Cliff1()
}

func (rcv *GroundArray) UnPack() *GroundArrayT {
	if rcv == nil {
		return nil
	}
	t := &GroundArrayT{}
	rcv.UnPackTo(t)
	return t
}

type GroundArray struct {
	_tab flatbuffers.Struct
}

func (rcv *GroundArray) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GroundArray) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *GroundArray) G0() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *GroundArray) MutateG0(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *GroundArray) G1() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *GroundArray) MutateG1(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *GroundArray) G2() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *GroundArray) MutateG2(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *GroundArray) Cliff0() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *GroundArray) MutateCliff0(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *GroundArray) Cliff1() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *GroundArray) MutateCliff1(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateGroundArray(builder *flatbuffers.Builder, g0 uint16, g1 uint16, g2 uint16, cliff0 uint16, cliff1 uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 10)
	builder.PrependUint16(cliff1)
	builder.PrependUint16(cliff0)
	builder.PrependUint16(g2)
	builder.PrependUint16(g1)
	builder.PrependUint16(g0)
	return builder.Offset()
}
