// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ImuDataT struct {
	Accelerometer *Vector3DT `json:"accelerometer"`
	Gyroscope *Vector3DT `json:"gyroscope"`
	Magnetometer *Vector3DT `json:"magnetometer"`
	TimestampOffset uint16 `json:"timestamp_offset"`
}

func (t *ImuDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateImuData(builder, t.Accelerometer.X, t.Accelerometer.Y, t.Accelerometer.Z, t.Gyroscope.X, t.Gyroscope.Y, t.Gyroscope.Z, t.Magnetometer.X, t.Magnetometer.Y, t.Magnetometer.Z, t.TimestampOffset)
}
func (rcv *ImuData) UnPackTo(t *ImuDataT) {
	t.Accelerometer = rcv.Accelerometer(nil).UnPack()
	t.Gyroscope = rcv.Gyroscope(nil).UnPack()
	t.Magnetometer = rcv.Magnetometer(nil).UnPack()
	t.TimestampOffset = rcv.TimestampOffset()
}

func (rcv *ImuData) UnPack() *ImuDataT {
	if rcv == nil {
		return nil
	}
	t := &ImuDataT{}
	rcv.UnPackTo(t)
	return t
}

type ImuData struct {
	_tab flatbuffers.Struct
}

func (rcv *ImuData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ImuData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ImuData) Accelerometer(obj *Vector3D) *Vector3D {
	if obj == nil {
		obj = new(Vector3D)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *ImuData) Gyroscope(obj *Vector3D) *Vector3D {
	if obj == nil {
		obj = new(Vector3D)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+6)
	return obj
}
func (rcv *ImuData) Magnetometer(obj *Vector3D) *Vector3D {
	if obj == nil {
		obj = new(Vector3D)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+12)
	return obj
}
func (rcv *ImuData) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(18))
}
func (rcv *ImuData) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(18), n)
}

func CreateImuData(builder *flatbuffers.Builder, accelerometer_x int16, accelerometer_y int16, accelerometer_z int16, gyroscope_x int16, gyroscope_y int16, gyroscope_z int16, magnetometer_x int16, magnetometer_y int16, magnetometer_z int16, timestampOffset uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 20)
	builder.PrependUint16(timestampOffset)
	builder.Prep(2, 6)
	builder.PrependInt16(magnetometer_z)
	builder.PrependInt16(magnetometer_y)
	builder.PrependInt16(magnetometer_x)
	builder.Prep(2, 6)
	builder.PrependInt16(gyroscope_z)
	builder.PrependInt16(gyroscope_y)
	builder.PrependInt16(gyroscope_x)
	builder.Prep(2, 6)
	builder.PrependInt16(accelerometer_z)
	builder.PrependInt16(accelerometer_y)
	builder.PrependInt16(accelerometer_x)
	return builder.Offset()
}
