// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProximityDataT struct {
	Proximity *Uint16Array8T `json:"proximity"`
	AmbientLight *Uint16Array8T `json:"ambient_light"`
	TimestampOffset uint16 `json:"timestamp_offset"`
	Padding uint16 `json:"padding"`
}

func (t *ProximityDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateProximityData(builder, t.Proximity.A0, t.Proximity.A1, t.Proximity.A2, t.Proximity.A3, t.Proximity.A4, t.Proximity.A5, t.Proximity.A6, t.Proximity.A7, t.AmbientLight.A0, t.AmbientLight.A1, t.AmbientLight.A2, t.AmbientLight.A3, t.AmbientLight.A4, t.AmbientLight.A5, t.AmbientLight.A6, t.AmbientLight.A7, t.TimestampOffset, t.Padding)
}
func (rcv *ProximityData) UnPackTo(t *ProximityDataT) {
	t.Proximity = rcv.Proximity(nil).UnPack()
	t.AmbientLight = rcv.AmbientLight(nil).UnPack()
	t.TimestampOffset = rcv.TimestampOffset()
	t.Padding = rcv.Padding()
}

func (rcv *ProximityData) UnPack() *ProximityDataT {
	if rcv == nil {
		return nil
	}
	t := &ProximityDataT{}
	rcv.UnPackTo(t)
	return t
}

type ProximityData struct {
	_tab flatbuffers.Struct
}

func (rcv *ProximityData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProximityData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ProximityData) Proximity(obj *Uint16Array8) *Uint16Array8 {
	if obj == nil {
		obj = new(Uint16Array8)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *ProximityData) AmbientLight(obj *Uint16Array8) *Uint16Array8 {
	if obj == nil {
		obj = new(Uint16Array8)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+16)
	return obj
}
func (rcv *ProximityData) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *ProximityData) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func (rcv *ProximityData) Padding() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(34))
}
func (rcv *ProximityData) MutatePadding(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(34), n)
}

func CreateProximityData(builder *flatbuffers.Builder, proximity_a0 uint16, proximity_a1 uint16, proximity_a2 uint16, proximity_a3 uint16, proximity_a4 uint16, proximity_a5 uint16, proximity_a6 uint16, proximity_a7 uint16, ambient_light_a0 uint16, ambient_light_a1 uint16, ambient_light_a2 uint16, ambient_light_a3 uint16, ambient_light_a4 uint16, ambient_light_a5 uint16, ambient_light_a6 uint16, ambient_light_a7 uint16, timestampOffset uint16, padding uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 36)
	builder.PrependUint16(padding)
	builder.PrependUint16(timestampOffset)
	builder.Prep(2, 16)
	builder.PrependUint16(ambient_light_a7)
	builder.PrependUint16(ambient_light_a6)
	builder.PrependUint16(ambient_light_a5)
	builder.PrependUint16(ambient_light_a4)
	builder.PrependUint16(ambient_light_a3)
	builder.PrependUint16(ambient_light_a2)
	builder.PrependUint16(ambient_light_a1)
	builder.PrependUint16(ambient_light_a0)
	builder.Prep(2, 16)
	builder.PrependUint16(proximity_a7)
	builder.PrependUint16(proximity_a6)
	builder.PrependUint16(proximity_a5)
	builder.PrependUint16(proximity_a4)
	builder.PrependUint16(proximity_a3)
	builder.PrependUint16(proximity_a2)
	builder.PrependUint16(proximity_a1)
	builder.PrependUint16(proximity_a0)
	return builder.Offset()
}
