// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RingSensorDataT struct {
	S0 uint16 `json:"s0"`
	S1 uint16 `json:"s1"`
	S2 uint16 `json:"s2"`
	S3 uint16 `json:"s3"`
	S4 uint16 `json:"s4"`
	S5 uint16 `json:"s5"`
	S6 uint16 `json:"s6"`
	S7 uint16 `json:"s7"`
}

func (t *RingSensorDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateRingSensorData(builder, t.S0, t.S1, t.S2, t.S3, t.S4, t.S5, t.S6, t.S7)
}
func (rcv *RingSensorData) UnPackTo(t *RingSensorDataT) {
	t.S0 = rcv.S0()
	t.S1 = rcv.S1()
	t.S2 = rcv.S2()
	t.S3 = rcv.S3()
	t.S4 = rcv.S4()
	t.S5 = rcv.S5()
	t.S6 = rcv.S6()
	t.S7 = rcv.S7()
}

func (rcv *RingSensorData) UnPack() *RingSensorDataT {
	if rcv == nil {
		return nil
	}
	t := &RingSensorDataT{}
	rcv.UnPackTo(t)
	return t
}

type RingSensorData struct {
	_tab flatbuffers.Struct
}

func (rcv *RingSensorData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RingSensorData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RingSensorData) S0() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *RingSensorData) MutateS0(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *RingSensorData) S1() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *RingSensorData) MutateS1(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *RingSensorData) S2() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *RingSensorData) MutateS2(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *RingSensorData) S3() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *RingSensorData) MutateS3(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *RingSensorData) S4() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *RingSensorData) MutateS4(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *RingSensorData) S5() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *RingSensorData) MutateS5(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func (rcv *RingSensorData) S6() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *RingSensorData) MutateS6(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *RingSensorData) S7() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(14))
}
func (rcv *RingSensorData) MutateS7(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(14), n)
}

func CreateRingSensorData(builder *flatbuffers.Builder, s0 uint16, s1 uint16, s2 uint16, s3 uint16, s4 uint16, s5 uint16, s6 uint16, s7 uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 16)
	builder.PrependUint16(s7)
	builder.PrependUint16(s6)
	builder.PrependUint16(s5)
	builder.PrependUint16(s4)
	builder.PrependUint16(s3)
	builder.PrependUint16(s2)
	builder.PrependUint16(s1)
	builder.PrependUint16(s0)
	return builder.Offset()
}
