// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SensorBatchT struct {
	BaseTimestamp uint64 `json:"base_timestamp"`
	Proximity []*ProximityDataT `json:"proximity"`
	Tof []*TofDataT `json:"tof"`
	Battery []*BatteryDataT `json:"battery"`
	Encoder []*EncoderDataT `json:"encoder"`
	Imu []*ImuDataT `json:"imu"`
	AudioBlob []byte `json:"audio_blob"`
	AudioMetadata []*AudioMetadataT `json:"audio_metadata"`
	VideoBlob []byte `json:"video_blob"`
	VideoMetadata []*VideoMetadataT `json:"video_metadata"`
}

func (t *SensorBatchT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	proximityOffset := flatbuffers.UOffsetT(0)
	if t.Proximity != nil {
		proximityLength := len(t.Proximity)
		SensorBatchStartProximityVector(builder, proximityLength)
		for j := proximityLength - 1; j >= 0; j-- {
			t.Proximity[j].Pack(builder)
		}
		proximityOffset = builder.EndVector(proximityLength)
	}
	tofOffset := flatbuffers.UOffsetT(0)
	if t.Tof != nil {
		tofLength := len(t.Tof)
		SensorBatchStartTofVector(builder, tofLength)
		for j := tofLength - 1; j >= 0; j-- {
			t.Tof[j].Pack(builder)
		}
		tofOffset = builder.EndVector(tofLength)
	}
	batteryOffset := flatbuffers.UOffsetT(0)
	if t.Battery != nil {
		batteryLength := len(t.Battery)
		SensorBatchStartBatteryVector(builder, batteryLength)
		for j := batteryLength - 1; j >= 0; j-- {
			t.Battery[j].Pack(builder)
		}
		batteryOffset = builder.EndVector(batteryLength)
	}
	encoderOffset := flatbuffers.UOffsetT(0)
	if t.Encoder != nil {
		encoderLength := len(t.Encoder)
		SensorBatchStartEncoderVector(builder, encoderLength)
		for j := encoderLength - 1; j >= 0; j-- {
			t.Encoder[j].Pack(builder)
		}
		encoderOffset = builder.EndVector(encoderLength)
	}
	imuOffset := flatbuffers.UOffsetT(0)
	if t.Imu != nil {
		imuLength := len(t.Imu)
		SensorBatchStartImuVector(builder, imuLength)
		for j := imuLength - 1; j >= 0; j-- {
			t.Imu[j].Pack(builder)
		}
		imuOffset = builder.EndVector(imuLength)
	}
	audioBlobOffset := flatbuffers.UOffsetT(0)
	if t.AudioBlob != nil {
		audioBlobOffset = builder.CreateByteString(t.AudioBlob)
	}
	audioMetadataOffset := flatbuffers.UOffsetT(0)
	if t.AudioMetadata != nil {
		audioMetadataLength := len(t.AudioMetadata)
		SensorBatchStartAudioMetadataVector(builder, audioMetadataLength)
		for j := audioMetadataLength - 1; j >= 0; j-- {
			t.AudioMetadata[j].Pack(builder)
		}
		audioMetadataOffset = builder.EndVector(audioMetadataLength)
	}
	videoBlobOffset := flatbuffers.UOffsetT(0)
	if t.VideoBlob != nil {
		videoBlobOffset = builder.CreateByteString(t.VideoBlob)
	}
	videoMetadataOffset := flatbuffers.UOffsetT(0)
	if t.VideoMetadata != nil {
		videoMetadataLength := len(t.VideoMetadata)
		SensorBatchStartVideoMetadataVector(builder, videoMetadataLength)
		for j := videoMetadataLength - 1; j >= 0; j-- {
			t.VideoMetadata[j].Pack(builder)
		}
		videoMetadataOffset = builder.EndVector(videoMetadataLength)
	}
	SensorBatchStart(builder)
	SensorBatchAddBaseTimestamp(builder, t.BaseTimestamp)
	SensorBatchAddProximity(builder, proximityOffset)
	SensorBatchAddTof(builder, tofOffset)
	SensorBatchAddBattery(builder, batteryOffset)
	SensorBatchAddEncoder(builder, encoderOffset)
	SensorBatchAddImu(builder, imuOffset)
	SensorBatchAddAudioBlob(builder, audioBlobOffset)
	SensorBatchAddAudioMetadata(builder, audioMetadataOffset)
	SensorBatchAddVideoBlob(builder, videoBlobOffset)
	SensorBatchAddVideoMetadata(builder, videoMetadataOffset)
	return SensorBatchEnd(builder)
}

func (rcv *SensorBatch) UnPackTo(t *SensorBatchT) {
	t.BaseTimestamp = rcv.BaseTimestamp()
	proximityLength := rcv.ProximityLength()
	t.Proximity = make([]*ProximityDataT, proximityLength)
	for j := 0; j < proximityLength; j++ {
		x := ProximityData{}
		rcv.Proximity(&x, j)
		t.Proximity[j] = x.UnPack()
	}
	tofLength := rcv.TofLength()
	t.Tof = make([]*TofDataT, tofLength)
	for j := 0; j < tofLength; j++ {
		x := TofData{}
		rcv.Tof(&x, j)
		t.Tof[j] = x.UnPack()
	}
	batteryLength := rcv.BatteryLength()
	t.Battery = make([]*BatteryDataT, batteryLength)
	for j := 0; j < batteryLength; j++ {
		x := BatteryData{}
		rcv.Battery(&x, j)
		t.Battery[j] = x.UnPack()
	}
	encoderLength := rcv.EncoderLength()
	t.Encoder = make([]*EncoderDataT, encoderLength)
	for j := 0; j < encoderLength; j++ {
		x := EncoderData{}
		rcv.Encoder(&x, j)
		t.Encoder[j] = x.UnPack()
	}
	imuLength := rcv.ImuLength()
	t.Imu = make([]*ImuDataT, imuLength)
	for j := 0; j < imuLength; j++ {
		x := ImuData{}
		rcv.Imu(&x, j)
		t.Imu[j] = x.UnPack()
	}
	t.AudioBlob = rcv.AudioBlobBytes()
	audioMetadataLength := rcv.AudioMetadataLength()
	t.AudioMetadata = make([]*AudioMetadataT, audioMetadataLength)
	for j := 0; j < audioMetadataLength; j++ {
		x := AudioMetadata{}
		rcv.AudioMetadata(&x, j)
		t.AudioMetadata[j] = x.UnPack()
	}
	t.VideoBlob = rcv.VideoBlobBytes()
	videoMetadataLength := rcv.VideoMetadataLength()
	t.VideoMetadata = make([]*VideoMetadataT, videoMetadataLength)
	for j := 0; j < videoMetadataLength; j++ {
		x := VideoMetadata{}
		rcv.VideoMetadata(&x, j)
		t.VideoMetadata[j] = x.UnPack()
	}
}

func (rcv *SensorBatch) UnPack() *SensorBatchT {
	if rcv == nil {
		return nil
	}
	t := &SensorBatchT{}
	rcv.UnPackTo(t)
	return t
}

type SensorBatch struct {
	_tab flatbuffers.Table
}

const SensorBatchIdentifier = "SENS"

func GetRootAsSensorBatch(buf []byte, offset flatbuffers.UOffsetT) *SensorBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SensorBatch{}
	x.Init(buf, n+offset)
	return x
}

func FinishSensorBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(SensorBatchIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func SensorBatchBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, SensorBatchIdentifier)
}

func GetSizePrefixedRootAsSensorBatch(buf []byte, offset flatbuffers.UOffsetT) *SensorBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SensorBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSensorBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(SensorBatchIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedSensorBatchBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, SensorBatchIdentifier)
}

func (rcv *SensorBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SensorBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SensorBatch) BaseTimestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SensorBatch) MutateBaseTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SensorBatch) Proximity(obj *ProximityData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 36
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) ProximityLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) Tof(obj *TofData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) TofLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) Battery(obj *BatteryData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) BatteryLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) Encoder(obj *EncoderData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 12
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) EncoderLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) Imu(obj *ImuData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 20
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) ImuLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) AudioBlob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SensorBatch) AudioBlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) AudioBlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SensorBatch) MutateAudioBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SensorBatch) AudioMetadata(obj *AudioMetadata, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 8
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) AudioMetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) VideoBlob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SensorBatch) VideoBlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SensorBatch) VideoBlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SensorBatch) MutateVideoBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SensorBatch) VideoMetadata(obj *VideoMetadata, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SensorBatch) VideoMetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SensorBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func SensorBatchAddBaseTimestamp(builder *flatbuffers.Builder, baseTimestamp uint64) {
	builder.PrependUint64Slot(0, baseTimestamp, 0)
}
func SensorBatchAddProximity(builder *flatbuffers.Builder, proximity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(proximity), 0)
}
func SensorBatchStartProximityVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(36, numElems, 2)
}
func SensorBatchAddTof(builder *flatbuffers.Builder, tof flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(tof), 0)
}
func SensorBatchStartTofVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 2)
}
func SensorBatchAddBattery(builder *flatbuffers.Builder, battery flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(battery), 0)
}
func SensorBatchStartBatteryVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 2)
}
func SensorBatchAddEncoder(builder *flatbuffers.Builder, encoder flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(encoder), 0)
}
func SensorBatchStartEncoderVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(12, numElems, 4)
}
func SensorBatchAddImu(builder *flatbuffers.Builder, imu flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(imu), 0)
}
func SensorBatchStartImuVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(20, numElems, 2)
}
func SensorBatchAddAudioBlob(builder *flatbuffers.Builder, audioBlob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(audioBlob), 0)
}
func SensorBatchStartAudioBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SensorBatchAddAudioMetadata(builder *flatbuffers.Builder, audioMetadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(audioMetadata), 0)
}
func SensorBatchStartAudioMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 2)
}
func SensorBatchAddVideoBlob(builder *flatbuffers.Builder, videoBlob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(videoBlob), 0)
}
func SensorBatchStartVideoBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SensorBatchAddVideoMetadata(builder *flatbuffers.Builder, videoMetadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(videoMetadata), 0)
}
func SensorBatchStartVideoMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 4)
}
func SensorBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
