// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TofDataT struct {
	Distance uint16 `json:"distance"`
	TimestampOffset uint16 `json:"timestamp_offset"`
}

func (t *TofDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateTofData(builder, t.Distance, t.TimestampOffset)
}
func (rcv *TofData) UnPackTo(t *TofDataT) {
	t.Distance = rcv.Distance()
	t.TimestampOffset = rcv.TimestampOffset()
}

func (rcv *TofData) UnPack() *TofDataT {
	if rcv == nil {
		return nil
	}
	t := &TofDataT{}
	rcv.UnPackTo(t)
	return t
}

type TofData struct {
	_tab flatbuffers.Struct
}

func (rcv *TofData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TofData) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TofData) Distance() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TofData) MutateDistance(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TofData) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *TofData) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateTofData(builder *flatbuffers.Builder, distance uint16, timestampOffset uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 4)
	builder.PrependUint16(timestampOffset)
	builder.PrependUint16(distance)
	return builder.Offset()
}
