// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Uint16Array8T struct {
	A0 uint16 `json:"a0"`
	A1 uint16 `json:"a1"`
	A2 uint16 `json:"a2"`
	A3 uint16 `json:"a3"`
	A4 uint16 `json:"a4"`
	A5 uint16 `json:"a5"`
	A6 uint16 `json:"a6"`
	A7 uint16 `json:"a7"`
}

func (t *Uint16Array8T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateUint16Array8(builder, t.A0, t.A1, t.A2, t.A3, t.A4, t.A5, t.A6, t.A7)
}
func (rcv *Uint16Array8) UnPackTo(t *Uint16Array8T) {
	t.A0 = rcv.A0()
	t.A1 = rcv.A1()
	t.A2 = rcv.A2()
	t.A3 = rcv.A3()
	t.A4 = rcv.A4()
	t.A5 = rcv.A5()
	t.A6 = rcv.A6()
	t.A7 = rcv.A7()
}

func (rcv *Uint16Array8) UnPack() *Uint16Array8T {
	if rcv == nil {
		return nil
	}
	t := &Uint16Array8T{}
	rcv.UnPackTo(t)
	return t
}

type Uint16Array8 struct {
	_tab flatbuffers.Struct
}

func (rcv *Uint16Array8) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Uint16Array8) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Uint16Array8) A0() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Uint16Array8) MutateA0(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Uint16Array8) A1() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *Uint16Array8) MutateA1(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *Uint16Array8) A2() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Uint16Array8) MutateA2(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *Uint16Array8) A3() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
func (rcv *Uint16Array8) MutateA3(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *Uint16Array8) A4() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *Uint16Array8) MutateA4(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *Uint16Array8) A5() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *Uint16Array8) MutateA5(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func (rcv *Uint16Array8) A6() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *Uint16Array8) MutateA6(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *Uint16Array8) A7() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(14))
}
func (rcv *Uint16Array8) MutateA7(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(14), n)
}

func CreateUint16Array8(builder *flatbuffers.Builder, a0 uint16, a1 uint16, a2 uint16, a3 uint16, a4 uint16, a5 uint16, a6 uint16, a7 uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 16)
	builder.PrependUint16(a7)
	builder.PrependUint16(a6)
	builder.PrependUint16(a5)
	builder.PrependUint16(a4)
	builder.PrependUint16(a3)
	builder.PrependUint16(a2)
	builder.PrependUint16(a1)
	builder.PrependUint16(a0)
	return builder.Offset()
}
