// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vector3DT struct {
	X int16 `json:"x"`
	Y int16 `json:"y"`
	Z int16 `json:"z"`
}

func (t *Vector3DT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateVector3D(builder, t.X, t.Y, t.Z)
}
func (rcv *Vector3D) UnPackTo(t *Vector3DT) {
	t.X = rcv.X()
	t.Y = rcv.Y()
	t.Z = rcv.Z()
}

func (rcv *Vector3D) UnPack() *Vector3DT {
	if rcv == nil {
		return nil
	}
	t := &Vector3DT{}
	rcv.UnPackTo(t)
	return t
}

type Vector3D struct {
	_tab flatbuffers.Struct
}

func (rcv *Vector3D) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vector3D) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Vector3D) X() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vector3D) MutateX(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vector3D) Y() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *Vector3D) MutateY(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *Vector3D) Z() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Vector3D) MutateZ(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateVector3D(builder *flatbuffers.Builder, x int16, y int16, z int16) flatbuffers.UOffsetT {
	builder.Prep(2, 6)
	builder.PrependInt16(z)
	builder.PrependInt16(y)
	builder.PrependInt16(x)
	return builder.Offset()
}
