// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sensors

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VideoMetadataT struct {
	Offset uint32 `json:"offset"`
	Length uint32 `json:"length"`
	FrameId uint16 `json:"frame_id"`
	FragmentIndex byte `json:"fragment_index"`
	TotalFragments byte `json:"total_fragments"`
	Flags uint16 `json:"flags"`
	TimestampOffset uint16 `json:"timestamp_offset"`
}

func (t *VideoMetadataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	return CreateVideoMetadata(builder, t.Offset, t.Length, t.FrameId, t.FragmentIndex, t.TotalFragments, t.Flags, t.TimestampOffset)
}
func (rcv *VideoMetadata) UnPackTo(t *VideoMetadataT) {
	t.Offset = rcv.Offset()
	t.Length = rcv.Length()
	t.FrameId = rcv.FrameId()
	t.FragmentIndex = rcv.FragmentIndex()
	t.TotalFragments = rcv.TotalFragments()
	t.Flags = rcv.Flags()
	t.TimestampOffset = rcv.TimestampOffset()
}

func (rcv *VideoMetadata) UnPack() *VideoMetadataT {
	if rcv == nil {
		return nil
	}
	t := &VideoMetadataT{}
	rcv.UnPackTo(t)
	return t
}

type VideoMetadata struct {
	_tab flatbuffers.Struct
}

func (rcv *VideoMetadata) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VideoMetadata) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *VideoMetadata) Offset() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *VideoMetadata) MutateOffset(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *VideoMetadata) Length() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *VideoMetadata) MutateLength(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *VideoMetadata) FrameId() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *VideoMetadata) MutateFrameId(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *VideoMetadata) FragmentIndex() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(10))
}
func (rcv *VideoMetadata) MutateFragmentIndex(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(10), n)
}

func (rcv *VideoMetadata) TotalFragments() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(11))
}
func (rcv *VideoMetadata) MutateTotalFragments(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(11), n)
}

func (rcv *VideoMetadata) Flags() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *VideoMetadata) MutateFlags(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *VideoMetadata) TimestampOffset() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(14))
}
func (rcv *VideoMetadata) MutateTimestampOffset(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(14), n)
}

func CreateVideoMetadata(builder *flatbuffers.Builder, offset uint32, length uint32, frameId uint16, fragmentIndex byte, totalFragments byte, flags uint16, timestampOffset uint16) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependUint16(timestampOffset)
	builder.PrependUint16(flags)
	builder.PrependByte(totalFragments)
	builder.PrependByte(fragmentIndex)
	builder.PrependUint16(frameId)
	builder.PrependUint32(length)
	builder.PrependUint32(offset)
	return builder.Offset()
}
