// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type Data byte

const (
	DataNONE        Data = 0
	DataInfoMessage Data = 1
)

var EnumNamesData = map[Data]string{
	DataNONE:        "NONE",
	DataInfoMessage: "InfoMessage",
}

var EnumValuesData = map[string]Data{
	"NONE":        DataNONE,
	"InfoMessage": DataInfoMessage,
}

func (v Data) String() string {
	if s, ok := EnumNamesData[v]; ok {
		return s
	}
	return "Data(" + strconv.FormatInt(int64(v), 10) + ")"
}

type DataT struct {
	Type Data
	Value interface{}
}

func (t *DataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case DataInfoMessage:
		return t.Value.(*InfoMessageT).Pack(builder)
	}
	return 0
}

func (rcv Data) UnPack(table flatbuffers.Table) *DataT {
	switch rcv {
	case DataInfoMessage:
		var x InfoMessage
		x.Init(table.Bytes, table.Pos)
		return &DataT{Type: DataInfoMessage, Value: x.UnPack()}
	}
	return nil
}
