// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InfoMessageT struct {
	Text string `json:"text"`
}

func (t *InfoMessageT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	textOffset := flatbuffers.UOffsetT(0)
	if t.Text != "" {
		textOffset = builder.CreateString(t.Text)
	}
	InfoMessageStart(builder)
	InfoMessageAddText(builder, textOffset)
	return InfoMessageEnd(builder)
}

func (rcv *InfoMessage) UnPackTo(t *InfoMessageT) {
	t.Text = string(rcv.Text())
}

func (rcv *InfoMessage) UnPack() *InfoMessageT {
	if rcv == nil {
		return nil
	}
	t := &InfoMessageT{}
	rcv.UnPackTo(t)
	return t
}

type InfoMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsInfoMessage(buf []byte, offset flatbuffers.UOffsetT) *InfoMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InfoMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishInfoMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInfoMessage(buf []byte, offset flatbuffers.UOffsetT) *InfoMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InfoMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInfoMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InfoMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InfoMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InfoMessage) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func InfoMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InfoMessageAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(text), 0)
}
func InfoMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
