#ifndef COMMANDS_BUILDER_H
#define COMMANDS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef COMMANDS_READER_H
#include "commands_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef flatbuffers_union_ref_t FripuckProtocol_Commands_Instruction_union_ref_t;
typedef flatbuffers_union_vec_ref_t FripuckProtocol_Commands_Instruction_union_vec_ref_t;
static FripuckProtocol_Commands_Instruction_union_ref_t FripuckProtocol_Commands_Instruction_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Instruction_union_t t);

static const flatbuffers_voffset_t __FripuckProtocol_Commands_InfoMessage_required[] = { 0 };
typedef flatbuffers_ref_t FripuckProtocol_Commands_InfoMessage_ref_t;
static FripuckProtocol_Commands_InfoMessage_ref_t FripuckProtocol_Commands_InfoMessage_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_InfoMessage_table_t t);
__flatbuffers_build_table(flatbuffers_, FripuckProtocol_Commands_InfoMessage, 1)

static const flatbuffers_voffset_t __FripuckProtocol_Commands_DummyConfig_required[] = { 0 };
typedef flatbuffers_ref_t FripuckProtocol_Commands_DummyConfig_ref_t;
static FripuckProtocol_Commands_DummyConfig_ref_t FripuckProtocol_Commands_DummyConfig_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_DummyConfig_table_t t);
__flatbuffers_build_table(flatbuffers_, FripuckProtocol_Commands_DummyConfig, 1)

static const flatbuffers_voffset_t __FripuckProtocol_Commands_Command_required[] = { 0 };
typedef flatbuffers_ref_t FripuckProtocol_Commands_Command_ref_t;
static FripuckProtocol_Commands_Command_ref_t FripuckProtocol_Commands_Command_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Command_table_t t);
__flatbuffers_build_table(flatbuffers_, FripuckProtocol_Commands_Command, 3)

static const flatbuffers_voffset_t __FripuckProtocol_Commands_Batch_required[] = { 0 };
typedef flatbuffers_ref_t FripuckProtocol_Commands_Batch_ref_t;
static FripuckProtocol_Commands_Batch_ref_t FripuckProtocol_Commands_Batch_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Batch_table_t t);
__flatbuffers_build_table(flatbuffers_, FripuckProtocol_Commands_Batch, 1)

#define __FripuckProtocol_Commands_InfoMessage_formal_args , flatbuffers_string_ref_t v0
#define __FripuckProtocol_Commands_InfoMessage_call_args , v0
static inline FripuckProtocol_Commands_InfoMessage_ref_t FripuckProtocol_Commands_InfoMessage_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_InfoMessage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, FripuckProtocol_Commands_InfoMessage, FripuckProtocol_Commands_InfoMessage_file_identifier, FripuckProtocol_Commands_InfoMessage_type_identifier)

#define __FripuckProtocol_Commands_DummyConfig_formal_args , uint32_t v0
#define __FripuckProtocol_Commands_DummyConfig_call_args , v0
static inline FripuckProtocol_Commands_DummyConfig_ref_t FripuckProtocol_Commands_DummyConfig_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_DummyConfig_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, FripuckProtocol_Commands_DummyConfig, FripuckProtocol_Commands_DummyConfig_file_identifier, FripuckProtocol_Commands_DummyConfig_type_identifier)

#define __FripuckProtocol_Commands_Command_formal_args , uint16_t v0, FripuckProtocol_Commands_Instruction_union_ref_t v2
#define __FripuckProtocol_Commands_Command_call_args , v0, v2
static inline FripuckProtocol_Commands_Command_ref_t FripuckProtocol_Commands_Command_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_Command_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, FripuckProtocol_Commands_Command, FripuckProtocol_Commands_Command_file_identifier, FripuckProtocol_Commands_Command_type_identifier)

#define __FripuckProtocol_Commands_Batch_formal_args , FripuckProtocol_Commands_Command_vec_ref_t v0
#define __FripuckProtocol_Commands_Batch_call_args , v0
static inline FripuckProtocol_Commands_Batch_ref_t FripuckProtocol_Commands_Batch_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_Batch_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, FripuckProtocol_Commands_Batch, FripuckProtocol_Commands_Batch_file_identifier, FripuckProtocol_Commands_Batch_type_identifier)

static inline FripuckProtocol_Commands_Instruction_union_ref_t FripuckProtocol_Commands_Instruction_as_NONE(void)
{ FripuckProtocol_Commands_Instruction_union_ref_t uref; uref.type = FripuckProtocol_Commands_Instruction_NONE; uref.value = 0; return uref; }
static inline FripuckProtocol_Commands_Instruction_union_ref_t FripuckProtocol_Commands_Instruction_as_DummyConfig(FripuckProtocol_Commands_DummyConfig_ref_t ref)
{ FripuckProtocol_Commands_Instruction_union_ref_t uref; uref.type = FripuckProtocol_Commands_Instruction_DummyConfig; uref.value = ref; return uref; }
static inline FripuckProtocol_Commands_Instruction_union_ref_t FripuckProtocol_Commands_Instruction_as_InfoMessage(FripuckProtocol_Commands_InfoMessage_ref_t ref)
{ FripuckProtocol_Commands_Instruction_union_ref_t uref; uref.type = FripuckProtocol_Commands_Instruction_InfoMessage; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, FripuckProtocol_Commands_Instruction)

static FripuckProtocol_Commands_Instruction_union_ref_t FripuckProtocol_Commands_Instruction_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Instruction_union_t u)
{
    switch (u.type) {
    case 1: return FripuckProtocol_Commands_Instruction_as_DummyConfig(FripuckProtocol_Commands_DummyConfig_clone(B, (FripuckProtocol_Commands_DummyConfig_table_t)u.value));
    case 2: return FripuckProtocol_Commands_Instruction_as_InfoMessage(FripuckProtocol_Commands_InfoMessage_clone(B, (FripuckProtocol_Commands_InfoMessage_table_t)u.value));
    default: return FripuckProtocol_Commands_Instruction_as_NONE();
    }
}

__flatbuffers_build_string_field(0, flatbuffers_, FripuckProtocol_Commands_InfoMessage_text, FripuckProtocol_Commands_InfoMessage)

static inline FripuckProtocol_Commands_InfoMessage_ref_t FripuckProtocol_Commands_InfoMessage_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_InfoMessage_formal_args)
{
    if (FripuckProtocol_Commands_InfoMessage_start(B)
        || FripuckProtocol_Commands_InfoMessage_text_add(B, v0)) {
        return 0;
    }
    return FripuckProtocol_Commands_InfoMessage_end(B);
}

static FripuckProtocol_Commands_InfoMessage_ref_t FripuckProtocol_Commands_InfoMessage_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_InfoMessage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (FripuckProtocol_Commands_InfoMessage_start(B)
        || FripuckProtocol_Commands_InfoMessage_text_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, FripuckProtocol_Commands_InfoMessage_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, FripuckProtocol_Commands_DummyConfig_value, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), FripuckProtocol_Commands_DummyConfig)

static inline FripuckProtocol_Commands_DummyConfig_ref_t FripuckProtocol_Commands_DummyConfig_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_DummyConfig_formal_args)
{
    if (FripuckProtocol_Commands_DummyConfig_start(B)
        || FripuckProtocol_Commands_DummyConfig_value_add(B, v0)) {
        return 0;
    }
    return FripuckProtocol_Commands_DummyConfig_end(B);
}

static FripuckProtocol_Commands_DummyConfig_ref_t FripuckProtocol_Commands_DummyConfig_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_DummyConfig_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (FripuckProtocol_Commands_DummyConfig_start(B)
        || FripuckProtocol_Commands_DummyConfig_value_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, FripuckProtocol_Commands_DummyConfig_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, FripuckProtocol_Commands_Command_timestamp, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), FripuckProtocol_Commands_Command)
__flatbuffers_build_union_field(2, flatbuffers_, FripuckProtocol_Commands_Command_content, FripuckProtocol_Commands_Instruction, FripuckProtocol_Commands_Command)
__flatbuffers_build_union_table_value_field(flatbuffers_, FripuckProtocol_Commands_Command_content, FripuckProtocol_Commands_Instruction, DummyConfig, FripuckProtocol_Commands_DummyConfig)
__flatbuffers_build_union_table_value_field(flatbuffers_, FripuckProtocol_Commands_Command_content, FripuckProtocol_Commands_Instruction, InfoMessage, FripuckProtocol_Commands_InfoMessage)

static inline FripuckProtocol_Commands_Command_ref_t FripuckProtocol_Commands_Command_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_Command_formal_args)
{
    if (FripuckProtocol_Commands_Command_start(B)
        || FripuckProtocol_Commands_Command_content_add_value(B, v2)
        || FripuckProtocol_Commands_Command_timestamp_add(B, v0)
        || FripuckProtocol_Commands_Command_content_add_type(B, v2.type)) {
        return 0;
    }
    return FripuckProtocol_Commands_Command_end(B);
}

static FripuckProtocol_Commands_Command_ref_t FripuckProtocol_Commands_Command_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Command_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (FripuckProtocol_Commands_Command_start(B)
        || FripuckProtocol_Commands_Command_content_pick(B, t)
        || FripuckProtocol_Commands_Command_timestamp_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, FripuckProtocol_Commands_Command_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, FripuckProtocol_Commands_Batch_entries, FripuckProtocol_Commands_Command, FripuckProtocol_Commands_Batch)

static inline FripuckProtocol_Commands_Batch_ref_t FripuckProtocol_Commands_Batch_create(flatbuffers_builder_t *B __FripuckProtocol_Commands_Batch_formal_args)
{
    if (FripuckProtocol_Commands_Batch_start(B)
        || FripuckProtocol_Commands_Batch_entries_add(B, v0)) {
        return 0;
    }
    return FripuckProtocol_Commands_Batch_end(B);
}

static FripuckProtocol_Commands_Batch_ref_t FripuckProtocol_Commands_Batch_clone(flatbuffers_builder_t *B, FripuckProtocol_Commands_Batch_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (FripuckProtocol_Commands_Batch_start(B)
        || FripuckProtocol_Commands_Batch_entries_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, FripuckProtocol_Commands_Batch_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* COMMANDS_BUILDER_H */
