#ifndef COMMANDS_VERIFIER_H
#define COMMANDS_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef COMMANDS_READER_H
#include "commands_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int FripuckProtocol_Commands_InfoMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int FripuckProtocol_Commands_DummyConfig_verify_table(flatcc_table_verifier_descriptor_t *td);
static int FripuckProtocol_Commands_Command_verify_table(flatcc_table_verifier_descriptor_t *td);
static int FripuckProtocol_Commands_Batch_verify_table(flatcc_table_verifier_descriptor_t *td);

static int FripuckProtocol_Commands_Instruction_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, FripuckProtocol_Commands_DummyConfig_verify_table); /* DummyConfig */
    case 2: return flatcc_verify_union_table(ud, FripuckProtocol_Commands_InfoMessage_verify_table); /* InfoMessage */
    default: return flatcc_verify_ok;
    }
}

static int FripuckProtocol_Commands_InfoMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_InfoMessage_identifier, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_InfoMessage_identifier, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_InfoMessage_type_identifier, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_InfoMessage_type_identifier, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static inline int FripuckProtocol_Commands_InfoMessage_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &FripuckProtocol_Commands_InfoMessage_verify_table);
}

static int FripuckProtocol_Commands_DummyConfig_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* value */)) return ret;
    return flatcc_verify_ok;
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_DummyConfig_identifier, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_DummyConfig_identifier, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_DummyConfig_type_identifier, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_DummyConfig_type_identifier, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static inline int FripuckProtocol_Commands_DummyConfig_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &FripuckProtocol_Commands_DummyConfig_verify_table);
}

static int FripuckProtocol_Commands_Command_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* timestamp */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &FripuckProtocol_Commands_Instruction_union_verifier) /* content */)) return ret;
    return flatcc_verify_ok;
}

static inline int FripuckProtocol_Commands_Command_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_Command_identifier, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_Command_identifier, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_Command_type_identifier, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_Command_type_identifier, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &FripuckProtocol_Commands_Command_verify_table);
}

static inline int FripuckProtocol_Commands_Command_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &FripuckProtocol_Commands_Command_verify_table);
}

static int FripuckProtocol_Commands_Batch_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &FripuckProtocol_Commands_Command_verify_table) /* entries */)) return ret;
    return flatcc_verify_ok;
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_Batch_identifier, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_Batch_identifier, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Commands_Batch_type_identifier, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Commands_Batch_type_identifier, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &FripuckProtocol_Commands_Batch_verify_table);
}

static inline int FripuckProtocol_Commands_Batch_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &FripuckProtocol_Commands_Batch_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* COMMANDS_VERIFIER_H */
