#ifndef COMMANDS_READER_H
#define COMMANDS_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct FripuckProtocol_Commands_InfoMessage_table *FripuckProtocol_Commands_InfoMessage_table_t;
typedef struct FripuckProtocol_Commands_InfoMessage_table *FripuckProtocol_Commands_InfoMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *FripuckProtocol_Commands_InfoMessage_vec_t;
typedef flatbuffers_uoffset_t *FripuckProtocol_Commands_InfoMessage_mutable_vec_t;
typedef const struct FripuckProtocol_Commands_DummyConfig_table *FripuckProtocol_Commands_DummyConfig_table_t;
typedef struct FripuckProtocol_Commands_DummyConfig_table *FripuckProtocol_Commands_DummyConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *FripuckProtocol_Commands_DummyConfig_vec_t;
typedef flatbuffers_uoffset_t *FripuckProtocol_Commands_DummyConfig_mutable_vec_t;
typedef const struct FripuckProtocol_Commands_Command_table *FripuckProtocol_Commands_Command_table_t;
typedef struct FripuckProtocol_Commands_Command_table *FripuckProtocol_Commands_Command_mutable_table_t;
typedef const flatbuffers_uoffset_t *FripuckProtocol_Commands_Command_vec_t;
typedef flatbuffers_uoffset_t *FripuckProtocol_Commands_Command_mutable_vec_t;
typedef const struct FripuckProtocol_Commands_Batch_table *FripuckProtocol_Commands_Batch_table_t;
typedef struct FripuckProtocol_Commands_Batch_table *FripuckProtocol_Commands_Batch_mutable_table_t;
typedef const flatbuffers_uoffset_t *FripuckProtocol_Commands_Batch_vec_t;
typedef flatbuffers_uoffset_t *FripuckProtocol_Commands_Batch_mutable_vec_t;
#ifndef FripuckProtocol_Commands_InfoMessage_file_identifier
#define FripuckProtocol_Commands_InfoMessage_file_identifier 0
#endif
/* deprecated, use FripuckProtocol_Commands_InfoMessage_file_identifier */
#ifndef FripuckProtocol_Commands_InfoMessage_identifier
#define FripuckProtocol_Commands_InfoMessage_identifier 0
#endif
#define FripuckProtocol_Commands_InfoMessage_type_hash ((flatbuffers_thash_t)0xf2ef584e)
#define FripuckProtocol_Commands_InfoMessage_type_identifier "\x4e\x58\xef\xf2"
#ifndef FripuckProtocol_Commands_InfoMessage_file_extension
#define FripuckProtocol_Commands_InfoMessage_file_extension "bin"
#endif
#ifndef FripuckProtocol_Commands_DummyConfig_file_identifier
#define FripuckProtocol_Commands_DummyConfig_file_identifier 0
#endif
/* deprecated, use FripuckProtocol_Commands_DummyConfig_file_identifier */
#ifndef FripuckProtocol_Commands_DummyConfig_identifier
#define FripuckProtocol_Commands_DummyConfig_identifier 0
#endif
#define FripuckProtocol_Commands_DummyConfig_type_hash ((flatbuffers_thash_t)0x9678b39f)
#define FripuckProtocol_Commands_DummyConfig_type_identifier "\x9f\xb3\x78\x96"
#ifndef FripuckProtocol_Commands_DummyConfig_file_extension
#define FripuckProtocol_Commands_DummyConfig_file_extension "bin"
#endif
#ifndef FripuckProtocol_Commands_Command_file_identifier
#define FripuckProtocol_Commands_Command_file_identifier 0
#endif
/* deprecated, use FripuckProtocol_Commands_Command_file_identifier */
#ifndef FripuckProtocol_Commands_Command_identifier
#define FripuckProtocol_Commands_Command_identifier 0
#endif
#define FripuckProtocol_Commands_Command_type_hash ((flatbuffers_thash_t)0xd1c0ccc8)
#define FripuckProtocol_Commands_Command_type_identifier "\xc8\xcc\xc0\xd1"
#ifndef FripuckProtocol_Commands_Command_file_extension
#define FripuckProtocol_Commands_Command_file_extension "bin"
#endif
#ifndef FripuckProtocol_Commands_Batch_file_identifier
#define FripuckProtocol_Commands_Batch_file_identifier 0
#endif
/* deprecated, use FripuckProtocol_Commands_Batch_file_identifier */
#ifndef FripuckProtocol_Commands_Batch_identifier
#define FripuckProtocol_Commands_Batch_identifier 0
#endif
#define FripuckProtocol_Commands_Batch_type_hash ((flatbuffers_thash_t)0x3efb123d)
#define FripuckProtocol_Commands_Batch_type_identifier "\x3d\x12\xfb\x3e"
#ifndef FripuckProtocol_Commands_Batch_file_extension
#define FripuckProtocol_Commands_Batch_file_extension "bin"
#endif



struct FripuckProtocol_Commands_InfoMessage_table { uint8_t unused__; };

static inline size_t FripuckProtocol_Commands_InfoMessage_vec_len(FripuckProtocol_Commands_InfoMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline FripuckProtocol_Commands_InfoMessage_table_t FripuckProtocol_Commands_InfoMessage_vec_at(FripuckProtocol_Commands_InfoMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(FripuckProtocol_Commands_InfoMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(FripuckProtocol_Commands_InfoMessage)

__flatbuffers_define_string_field(0, FripuckProtocol_Commands_InfoMessage, text, 0)

struct FripuckProtocol_Commands_DummyConfig_table { uint8_t unused__; };

static inline size_t FripuckProtocol_Commands_DummyConfig_vec_len(FripuckProtocol_Commands_DummyConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline FripuckProtocol_Commands_DummyConfig_table_t FripuckProtocol_Commands_DummyConfig_vec_at(FripuckProtocol_Commands_DummyConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(FripuckProtocol_Commands_DummyConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(FripuckProtocol_Commands_DummyConfig)

__flatbuffers_define_scalar_field(0, FripuckProtocol_Commands_DummyConfig, value, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t FripuckProtocol_Commands_Instruction_union_type_t;
__flatbuffers_define_integer_type(FripuckProtocol_Commands_Instruction, FripuckProtocol_Commands_Instruction_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, FripuckProtocol_Commands_Instruction)
#define FripuckProtocol_Commands_Instruction_NONE ((FripuckProtocol_Commands_Instruction_union_type_t)UINT8_C(0))
#define FripuckProtocol_Commands_Instruction_DummyConfig ((FripuckProtocol_Commands_Instruction_union_type_t)UINT8_C(1))
#define FripuckProtocol_Commands_Instruction_InfoMessage ((FripuckProtocol_Commands_Instruction_union_type_t)UINT8_C(2))

static inline const char *FripuckProtocol_Commands_Instruction_type_name(FripuckProtocol_Commands_Instruction_union_type_t type)
{
    switch (type) {
    case FripuckProtocol_Commands_Instruction_NONE: return "NONE";
    case FripuckProtocol_Commands_Instruction_DummyConfig: return "DummyConfig";
    case FripuckProtocol_Commands_Instruction_InfoMessage: return "InfoMessage";
    default: return "";
    }
}

static inline int FripuckProtocol_Commands_Instruction_is_known_type(FripuckProtocol_Commands_Instruction_union_type_t type)
{
    switch (type) {
    case FripuckProtocol_Commands_Instruction_NONE: return 1;
    case FripuckProtocol_Commands_Instruction_DummyConfig: return 1;
    case FripuckProtocol_Commands_Instruction_InfoMessage: return 1;
    default: return 0;
    }
}


struct FripuckProtocol_Commands_Command_table { uint8_t unused__; };

static inline size_t FripuckProtocol_Commands_Command_vec_len(FripuckProtocol_Commands_Command_vec_t vec)
__flatbuffers_vec_len(vec)
static inline FripuckProtocol_Commands_Command_table_t FripuckProtocol_Commands_Command_vec_at(FripuckProtocol_Commands_Command_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(FripuckProtocol_Commands_Command_table_t, vec, i, 0)
__flatbuffers_table_as_root(FripuckProtocol_Commands_Command)

__flatbuffers_define_scalar_field(0, FripuckProtocol_Commands_Command, timestamp, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, FripuckProtocol_Commands_Command, content, FripuckProtocol_Commands_Instruction, 0)

struct FripuckProtocol_Commands_Batch_table { uint8_t unused__; };

static inline size_t FripuckProtocol_Commands_Batch_vec_len(FripuckProtocol_Commands_Batch_vec_t vec)
__flatbuffers_vec_len(vec)
static inline FripuckProtocol_Commands_Batch_table_t FripuckProtocol_Commands_Batch_vec_at(FripuckProtocol_Commands_Batch_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(FripuckProtocol_Commands_Batch_table_t, vec, i, 0)
__flatbuffers_table_as_root(FripuckProtocol_Commands_Batch)

__flatbuffers_define_vector_field(0, FripuckProtocol_Commands_Batch, entries, FripuckProtocol_Commands_Command_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* COMMANDS_READER_H */
