#ifndef COMMANDS_BUILDER_H
#define COMMANDS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef COMMANDS_READER_H
#include "commands_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef flatbuffers_union_ref_t Fripuck2_Commands_Instruction_union_ref_t;
typedef flatbuffers_union_vec_ref_t Fripuck2_Commands_Instruction_union_vec_ref_t;
static Fripuck2_Commands_Instruction_union_ref_t Fripuck2_Commands_Instruction_clone(flatbuffers_builder_t *B, Fripuck2_Commands_Instruction_union_t t);

static const flatbuffers_voffset_t __Fripuck2_Commands_InfoMessage_required[] = { 0 };
typedef flatbuffers_ref_t Fripuck2_Commands_InfoMessage_ref_t;
static Fripuck2_Commands_InfoMessage_ref_t Fripuck2_Commands_InfoMessage_clone(flatbuffers_builder_t *B, Fripuck2_Commands_InfoMessage_table_t t);
__flatbuffers_build_table(flatbuffers_, Fripuck2_Commands_InfoMessage, 1)

static const flatbuffers_voffset_t __Fripuck2_Commands_DummyConfig_required[] = { 0 };
typedef flatbuffers_ref_t Fripuck2_Commands_DummyConfig_ref_t;
static Fripuck2_Commands_DummyConfig_ref_t Fripuck2_Commands_DummyConfig_clone(flatbuffers_builder_t *B, Fripuck2_Commands_DummyConfig_table_t t);
__flatbuffers_build_table(flatbuffers_, Fripuck2_Commands_DummyConfig, 1)

static const flatbuffers_voffset_t __Fripuck2_Commands_Batch_required[] = { 0 };
typedef flatbuffers_ref_t Fripuck2_Commands_Batch_ref_t;
static Fripuck2_Commands_Batch_ref_t Fripuck2_Commands_Batch_clone(flatbuffers_builder_t *B, Fripuck2_Commands_Batch_table_t t);
__flatbuffers_build_table(flatbuffers_, Fripuck2_Commands_Batch, 2)

#define __Fripuck2_Commands_InfoMessage_formal_args , flatbuffers_string_ref_t v0
#define __Fripuck2_Commands_InfoMessage_call_args , v0
static inline Fripuck2_Commands_InfoMessage_ref_t Fripuck2_Commands_InfoMessage_create(flatbuffers_builder_t *B __Fripuck2_Commands_InfoMessage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Fripuck2_Commands_InfoMessage, Fripuck2_Commands_InfoMessage_file_identifier, Fripuck2_Commands_InfoMessage_type_identifier)

#define __Fripuck2_Commands_DummyConfig_formal_args , uint32_t v0
#define __Fripuck2_Commands_DummyConfig_call_args , v0
static inline Fripuck2_Commands_DummyConfig_ref_t Fripuck2_Commands_DummyConfig_create(flatbuffers_builder_t *B __Fripuck2_Commands_DummyConfig_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Fripuck2_Commands_DummyConfig, Fripuck2_Commands_DummyConfig_file_identifier, Fripuck2_Commands_DummyConfig_type_identifier)

#define __Fripuck2_Commands_Batch_formal_args , Fripuck2_Commands_Instruction_union_vec_ref_t v1
#define __Fripuck2_Commands_Batch_call_args , v1
static inline Fripuck2_Commands_Batch_ref_t Fripuck2_Commands_Batch_create(flatbuffers_builder_t *B __Fripuck2_Commands_Batch_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Fripuck2_Commands_Batch, Fripuck2_Commands_Batch_file_identifier, Fripuck2_Commands_Batch_type_identifier)

static inline Fripuck2_Commands_Instruction_union_ref_t Fripuck2_Commands_Instruction_as_NONE(void)
{ Fripuck2_Commands_Instruction_union_ref_t uref; uref.type = Fripuck2_Commands_Instruction_NONE; uref.value = 0; return uref; }
static inline Fripuck2_Commands_Instruction_union_ref_t Fripuck2_Commands_Instruction_as_DummyConfig(Fripuck2_Commands_DummyConfig_ref_t ref)
{ Fripuck2_Commands_Instruction_union_ref_t uref; uref.type = Fripuck2_Commands_Instruction_DummyConfig; uref.value = ref; return uref; }
static inline Fripuck2_Commands_Instruction_union_ref_t Fripuck2_Commands_Instruction_as_InfoMessage(Fripuck2_Commands_InfoMessage_ref_t ref)
{ Fripuck2_Commands_Instruction_union_ref_t uref; uref.type = Fripuck2_Commands_Instruction_InfoMessage; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, Fripuck2_Commands_Instruction)

static Fripuck2_Commands_Instruction_union_ref_t Fripuck2_Commands_Instruction_clone(flatbuffers_builder_t *B, Fripuck2_Commands_Instruction_union_t u)
{
    switch (u.type) {
    case 1: return Fripuck2_Commands_Instruction_as_DummyConfig(Fripuck2_Commands_DummyConfig_clone(B, (Fripuck2_Commands_DummyConfig_table_t)u.value));
    case 2: return Fripuck2_Commands_Instruction_as_InfoMessage(Fripuck2_Commands_InfoMessage_clone(B, (Fripuck2_Commands_InfoMessage_table_t)u.value));
    default: return Fripuck2_Commands_Instruction_as_NONE();
    }
}

__flatbuffers_build_string_field(0, flatbuffers_, Fripuck2_Commands_InfoMessage_text, Fripuck2_Commands_InfoMessage)

static inline Fripuck2_Commands_InfoMessage_ref_t Fripuck2_Commands_InfoMessage_create(flatbuffers_builder_t *B __Fripuck2_Commands_InfoMessage_formal_args)
{
    if (Fripuck2_Commands_InfoMessage_start(B)
        || Fripuck2_Commands_InfoMessage_text_add(B, v0)) {
        return 0;
    }
    return Fripuck2_Commands_InfoMessage_end(B);
}

static Fripuck2_Commands_InfoMessage_ref_t Fripuck2_Commands_InfoMessage_clone(flatbuffers_builder_t *B, Fripuck2_Commands_InfoMessage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Fripuck2_Commands_InfoMessage_start(B)
        || Fripuck2_Commands_InfoMessage_text_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Fripuck2_Commands_InfoMessage_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, Fripuck2_Commands_DummyConfig_value, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), Fripuck2_Commands_DummyConfig)

static inline Fripuck2_Commands_DummyConfig_ref_t Fripuck2_Commands_DummyConfig_create(flatbuffers_builder_t *B __Fripuck2_Commands_DummyConfig_formal_args)
{
    if (Fripuck2_Commands_DummyConfig_start(B)
        || Fripuck2_Commands_DummyConfig_value_add(B, v0)) {
        return 0;
    }
    return Fripuck2_Commands_DummyConfig_end(B);
}

static Fripuck2_Commands_DummyConfig_ref_t Fripuck2_Commands_DummyConfig_clone(flatbuffers_builder_t *B, Fripuck2_Commands_DummyConfig_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Fripuck2_Commands_DummyConfig_start(B)
        || Fripuck2_Commands_DummyConfig_value_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Fripuck2_Commands_DummyConfig_end(B));
}

__flatbuffers_build_union_vector_field(1, flatbuffers_, Fripuck2_Commands_Batch_entries, Fripuck2_Commands_Instruction, Fripuck2_Commands_Batch)
__flatbuffers_build_union_table_vector_value_field(flatbuffers_, Fripuck2_Commands_Batch_entries, Fripuck2_Commands_Instruction, DummyConfig, Fripuck2_Commands_DummyConfig)
__flatbuffers_build_union_table_vector_value_field(flatbuffers_, Fripuck2_Commands_Batch_entries, Fripuck2_Commands_Instruction, InfoMessage, Fripuck2_Commands_InfoMessage)

static inline Fripuck2_Commands_Batch_ref_t Fripuck2_Commands_Batch_create(flatbuffers_builder_t *B __Fripuck2_Commands_Batch_formal_args)
{
    if (Fripuck2_Commands_Batch_start(B)
        || Fripuck2_Commands_Batch_entries_add(B, v1)) {
        return 0;
    }
    return Fripuck2_Commands_Batch_end(B);
}

static Fripuck2_Commands_Batch_ref_t Fripuck2_Commands_Batch_clone(flatbuffers_builder_t *B, Fripuck2_Commands_Batch_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Fripuck2_Commands_Batch_start(B)
        || Fripuck2_Commands_Batch_entries_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Fripuck2_Commands_Batch_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* COMMANDS_BUILDER_H */
