#ifndef SENSORS_READER_H
#define SENSORS_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "SENS"
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef struct FripuckProtocol_Sensors_Uint16Array8 FripuckProtocol_Sensors_Uint16Array8_t;
typedef const FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_struct_t;
typedef FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_mutable_struct_t;
typedef const FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_vec_t;
typedef FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_ProximityData FripuckProtocol_Sensors_ProximityData_t;
typedef const FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_struct_t;
typedef FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_vec_t;
typedef FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_TofData FripuckProtocol_Sensors_TofData_t;
typedef const FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_struct_t;
typedef FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_vec_t;
typedef FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_BatteryData FripuckProtocol_Sensors_BatteryData_t;
typedef const FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_struct_t;
typedef FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_vec_t;
typedef FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_EncoderData FripuckProtocol_Sensors_EncoderData_t;
typedef const FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_struct_t;
typedef FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_vec_t;
typedef FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_Vector3f FripuckProtocol_Sensors_Vector3f_t;
typedef const FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f_struct_t;
typedef FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f_mutable_struct_t;
typedef const FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f_vec_t;
typedef FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_ImuData FripuckProtocol_Sensors_ImuData_t;
typedef const FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_struct_t;
typedef FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_vec_t;
typedef FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_VolumeData FripuckProtocol_Sensors_VolumeData_t;
typedef const FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_struct_t;
typedef FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_mutable_struct_t;
typedef const FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_vec_t;
typedef FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_AudioMetadata FripuckProtocol_Sensors_AudioMetadata_t;
typedef const FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_struct_t;
typedef FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_mutable_struct_t;
typedef const FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_vec_t;
typedef FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_mutable_vec_t;
typedef struct FripuckProtocol_Sensors_VideoMetadata FripuckProtocol_Sensors_VideoMetadata_t;
typedef const FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_struct_t;
typedef FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_mutable_struct_t;
typedef const FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_vec_t;
typedef FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_mutable_vec_t;

typedef const struct FripuckProtocol_Sensors_SensorBatch_table *FripuckProtocol_Sensors_SensorBatch_table_t;
typedef struct FripuckProtocol_Sensors_SensorBatch_table *FripuckProtocol_Sensors_SensorBatch_mutable_table_t;
typedef const flatbuffers_uoffset_t *FripuckProtocol_Sensors_SensorBatch_vec_t;
typedef flatbuffers_uoffset_t *FripuckProtocol_Sensors_SensorBatch_mutable_vec_t;
#ifndef FripuckProtocol_Sensors_Uint16Array8_file_identifier
#define FripuckProtocol_Sensors_Uint16Array8_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_Uint16Array8_file_identifier */
#ifndef FripuckProtocol_Sensors_Uint16Array8_identifier
#define FripuckProtocol_Sensors_Uint16Array8_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_Uint16Array8_type_hash ((flatbuffers_thash_t)0x67e690b2)
#define FripuckProtocol_Sensors_Uint16Array8_type_identifier "\xb2\x90\xe6\x67"
#ifndef FripuckProtocol_Sensors_Uint16Array8_file_extension
#define FripuckProtocol_Sensors_Uint16Array8_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_ProximityData_file_identifier
#define FripuckProtocol_Sensors_ProximityData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_ProximityData_file_identifier */
#ifndef FripuckProtocol_Sensors_ProximityData_identifier
#define FripuckProtocol_Sensors_ProximityData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_ProximityData_type_hash ((flatbuffers_thash_t)0xbf7407d3)
#define FripuckProtocol_Sensors_ProximityData_type_identifier "\xd3\x07\x74\xbf"
#ifndef FripuckProtocol_Sensors_ProximityData_file_extension
#define FripuckProtocol_Sensors_ProximityData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_TofData_file_identifier
#define FripuckProtocol_Sensors_TofData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_TofData_file_identifier */
#ifndef FripuckProtocol_Sensors_TofData_identifier
#define FripuckProtocol_Sensors_TofData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_TofData_type_hash ((flatbuffers_thash_t)0x59a5bb67)
#define FripuckProtocol_Sensors_TofData_type_identifier "\x67\xbb\xa5\x59"
#ifndef FripuckProtocol_Sensors_TofData_file_extension
#define FripuckProtocol_Sensors_TofData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_BatteryData_file_identifier
#define FripuckProtocol_Sensors_BatteryData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_BatteryData_file_identifier */
#ifndef FripuckProtocol_Sensors_BatteryData_identifier
#define FripuckProtocol_Sensors_BatteryData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_BatteryData_type_hash ((flatbuffers_thash_t)0x7075aecf)
#define FripuckProtocol_Sensors_BatteryData_type_identifier "\xcf\xae\x75\x70"
#ifndef FripuckProtocol_Sensors_BatteryData_file_extension
#define FripuckProtocol_Sensors_BatteryData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_EncoderData_file_identifier
#define FripuckProtocol_Sensors_EncoderData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_EncoderData_file_identifier */
#ifndef FripuckProtocol_Sensors_EncoderData_identifier
#define FripuckProtocol_Sensors_EncoderData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_EncoderData_type_hash ((flatbuffers_thash_t)0x7be7eafa)
#define FripuckProtocol_Sensors_EncoderData_type_identifier "\xfa\xea\xe7\x7b"
#ifndef FripuckProtocol_Sensors_EncoderData_file_extension
#define FripuckProtocol_Sensors_EncoderData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_Vector3f_file_identifier
#define FripuckProtocol_Sensors_Vector3f_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_Vector3f_file_identifier */
#ifndef FripuckProtocol_Sensors_Vector3f_identifier
#define FripuckProtocol_Sensors_Vector3f_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_Vector3f_type_hash ((flatbuffers_thash_t)0x26f6a01c)
#define FripuckProtocol_Sensors_Vector3f_type_identifier "\x1c\xa0\xf6\x26"
#ifndef FripuckProtocol_Sensors_Vector3f_file_extension
#define FripuckProtocol_Sensors_Vector3f_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_ImuData_file_identifier
#define FripuckProtocol_Sensors_ImuData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_ImuData_file_identifier */
#ifndef FripuckProtocol_Sensors_ImuData_identifier
#define FripuckProtocol_Sensors_ImuData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_ImuData_type_hash ((flatbuffers_thash_t)0x688ac56f)
#define FripuckProtocol_Sensors_ImuData_type_identifier "\x6f\xc5\x8a\x68"
#ifndef FripuckProtocol_Sensors_ImuData_file_extension
#define FripuckProtocol_Sensors_ImuData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_VolumeData_file_identifier
#define FripuckProtocol_Sensors_VolumeData_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_VolumeData_file_identifier */
#ifndef FripuckProtocol_Sensors_VolumeData_identifier
#define FripuckProtocol_Sensors_VolumeData_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_VolumeData_type_hash ((flatbuffers_thash_t)0x6c2b61c8)
#define FripuckProtocol_Sensors_VolumeData_type_identifier "\xc8\x61\x2b\x6c"
#ifndef FripuckProtocol_Sensors_VolumeData_file_extension
#define FripuckProtocol_Sensors_VolumeData_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_AudioMetadata_file_identifier
#define FripuckProtocol_Sensors_AudioMetadata_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_AudioMetadata_file_identifier */
#ifndef FripuckProtocol_Sensors_AudioMetadata_identifier
#define FripuckProtocol_Sensors_AudioMetadata_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_AudioMetadata_type_hash ((flatbuffers_thash_t)0xef91fadd)
#define FripuckProtocol_Sensors_AudioMetadata_type_identifier "\xdd\xfa\x91\xef"
#ifndef FripuckProtocol_Sensors_AudioMetadata_file_extension
#define FripuckProtocol_Sensors_AudioMetadata_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_VideoMetadata_file_identifier
#define FripuckProtocol_Sensors_VideoMetadata_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_VideoMetadata_file_identifier */
#ifndef FripuckProtocol_Sensors_VideoMetadata_identifier
#define FripuckProtocol_Sensors_VideoMetadata_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_VideoMetadata_type_hash ((flatbuffers_thash_t)0xc788c2a8)
#define FripuckProtocol_Sensors_VideoMetadata_type_identifier "\xa8\xc2\x88\xc7"
#ifndef FripuckProtocol_Sensors_VideoMetadata_file_extension
#define FripuckProtocol_Sensors_VideoMetadata_file_extension "bin"
#endif
#ifndef FripuckProtocol_Sensors_SensorBatch_file_identifier
#define FripuckProtocol_Sensors_SensorBatch_file_identifier "SENS"
#endif
/* deprecated, use FripuckProtocol_Sensors_SensorBatch_file_identifier */
#ifndef FripuckProtocol_Sensors_SensorBatch_identifier
#define FripuckProtocol_Sensors_SensorBatch_identifier "SENS"
#endif
#define FripuckProtocol_Sensors_SensorBatch_type_hash ((flatbuffers_thash_t)0x20d41500)
#define FripuckProtocol_Sensors_SensorBatch_type_identifier "\x00\x15\xd4\x20"
#ifndef FripuckProtocol_Sensors_SensorBatch_file_extension
#define FripuckProtocol_Sensors_SensorBatch_file_extension "bin"
#endif


struct FripuckProtocol_Sensors_Uint16Array8 {
    alignas(2) uint16_t a0;
    alignas(2) uint16_t a1;
    alignas(2) uint16_t a2;
    alignas(2) uint16_t a3;
    alignas(2) uint16_t a4;
    alignas(2) uint16_t a5;
    alignas(2) uint16_t a6;
    alignas(2) uint16_t a7;
};
static_assert(sizeof(FripuckProtocol_Sensors_Uint16Array8_t) == 16, "struct size mismatch");

static inline const FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8__const_ptr_add(const FripuckProtocol_Sensors_Uint16Array8_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8__ptr_add(FripuckProtocol_Sensors_Uint16Array8_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_Uint16Array8_struct_t FripuckProtocol_Sensors_Uint16Array8_vec_at(FripuckProtocol_Sensors_Uint16Array8_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_Uint16Array8__size(void) { return 16; }
static inline size_t FripuckProtocol_Sensors_Uint16Array8_vec_len(FripuckProtocol_Sensors_Uint16Array8_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_Uint16Array8)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a0, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a1, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a2, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a3, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a4, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a5, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a6, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Uint16Array8, a7, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_ProximityData {
    alignas(2) FripuckProtocol_Sensors_Uint16Array8_t proximity;
    alignas(2) FripuckProtocol_Sensors_Uint16Array8_t ambient_light;
    alignas(2) uint16_t timestamp_offset;
    alignas(2) uint16_t padding;
};
static_assert(sizeof(FripuckProtocol_Sensors_ProximityData_t) == 36, "struct size mismatch");

static inline const FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData__const_ptr_add(const FripuckProtocol_Sensors_ProximityData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData__ptr_add(FripuckProtocol_Sensors_ProximityData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_ProximityData_struct_t FripuckProtocol_Sensors_ProximityData_vec_at(FripuckProtocol_Sensors_ProximityData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_ProximityData__size(void) { return 36; }
static inline size_t FripuckProtocol_Sensors_ProximityData_vec_len(FripuckProtocol_Sensors_ProximityData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_ProximityData)

__flatbuffers_define_struct_struct_field(FripuckProtocol_Sensors_ProximityData, proximity, FripuckProtocol_Sensors_Uint16Array8_struct_t)
__flatbuffers_define_struct_struct_field(FripuckProtocol_Sensors_ProximityData, ambient_light, FripuckProtocol_Sensors_Uint16Array8_struct_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_ProximityData, timestamp_offset, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_ProximityData, padding, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_TofData {
    alignas(2) uint16_t distance;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_TofData_t) == 4, "struct size mismatch");

static inline const FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData__const_ptr_add(const FripuckProtocol_Sensors_TofData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData__ptr_add(FripuckProtocol_Sensors_TofData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_TofData_struct_t FripuckProtocol_Sensors_TofData_vec_at(FripuckProtocol_Sensors_TofData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_TofData__size(void) { return 4; }
static inline size_t FripuckProtocol_Sensors_TofData_vec_len(FripuckProtocol_Sensors_TofData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_TofData)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_TofData, distance, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_TofData, timestamp_offset, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_BatteryData {
    alignas(2) uint16_t millivolts;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_BatteryData_t) == 4, "struct size mismatch");

static inline const FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData__const_ptr_add(const FripuckProtocol_Sensors_BatteryData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData__ptr_add(FripuckProtocol_Sensors_BatteryData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_BatteryData_struct_t FripuckProtocol_Sensors_BatteryData_vec_at(FripuckProtocol_Sensors_BatteryData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_BatteryData__size(void) { return 4; }
static inline size_t FripuckProtocol_Sensors_BatteryData_vec_len(FripuckProtocol_Sensors_BatteryData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_BatteryData)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_BatteryData, millivolts, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_BatteryData, timestamp_offset, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_EncoderData {
    alignas(4) int32_t left_steps;
    alignas(4) int32_t right_steps;
    alignas(2) uint16_t timestamp_offset;
    alignas(2) uint16_t padding;
};
static_assert(sizeof(FripuckProtocol_Sensors_EncoderData_t) == 12, "struct size mismatch");

static inline const FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData__const_ptr_add(const FripuckProtocol_Sensors_EncoderData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData__ptr_add(FripuckProtocol_Sensors_EncoderData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_EncoderData_struct_t FripuckProtocol_Sensors_EncoderData_vec_at(FripuckProtocol_Sensors_EncoderData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_EncoderData__size(void) { return 12; }
static inline size_t FripuckProtocol_Sensors_EncoderData_vec_len(FripuckProtocol_Sensors_EncoderData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_EncoderData)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_EncoderData, left_steps, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_EncoderData, right_steps, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_EncoderData, timestamp_offset, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_EncoderData, padding, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_Vector3f {
    alignas(4) float x;
    alignas(4) float y;
    alignas(4) float z;
};
static_assert(sizeof(FripuckProtocol_Sensors_Vector3f_t) == 12, "struct size mismatch");

static inline const FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f__const_ptr_add(const FripuckProtocol_Sensors_Vector3f_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_Vector3f_t *FripuckProtocol_Sensors_Vector3f__ptr_add(FripuckProtocol_Sensors_Vector3f_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_Vector3f_struct_t FripuckProtocol_Sensors_Vector3f_vec_at(FripuckProtocol_Sensors_Vector3f_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_Vector3f__size(void) { return 12; }
static inline size_t FripuckProtocol_Sensors_Vector3f_vec_len(FripuckProtocol_Sensors_Vector3f_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_Vector3f)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Vector3f, x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Vector3f, y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_Vector3f, z, flatbuffers_float, float)

struct FripuckProtocol_Sensors_ImuData {
    alignas(4) FripuckProtocol_Sensors_Vector3f_t accelerometer;
    alignas(4) FripuckProtocol_Sensors_Vector3f_t gyroscope;
    alignas(4) FripuckProtocol_Sensors_Vector3f_t magnetometer;
    alignas(4) float temperature;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_ImuData_t) == 44, "struct size mismatch");

static inline const FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData__const_ptr_add(const FripuckProtocol_Sensors_ImuData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData__ptr_add(FripuckProtocol_Sensors_ImuData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_ImuData_struct_t FripuckProtocol_Sensors_ImuData_vec_at(FripuckProtocol_Sensors_ImuData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_ImuData__size(void) { return 44; }
static inline size_t FripuckProtocol_Sensors_ImuData_vec_len(FripuckProtocol_Sensors_ImuData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_ImuData)

__flatbuffers_define_struct_struct_field(FripuckProtocol_Sensors_ImuData, accelerometer, FripuckProtocol_Sensors_Vector3f_struct_t)
__flatbuffers_define_struct_struct_field(FripuckProtocol_Sensors_ImuData, gyroscope, FripuckProtocol_Sensors_Vector3f_struct_t)
__flatbuffers_define_struct_struct_field(FripuckProtocol_Sensors_ImuData, magnetometer, FripuckProtocol_Sensors_Vector3f_struct_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_ImuData, temperature, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_ImuData, timestamp_offset, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_VolumeData {
    alignas(2) uint16_t m0;
    alignas(2) uint16_t m1;
    alignas(2) uint16_t m2;
    alignas(2) uint16_t m3;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_VolumeData_t) == 10, "struct size mismatch");

static inline const FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData__const_ptr_add(const FripuckProtocol_Sensors_VolumeData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData__ptr_add(FripuckProtocol_Sensors_VolumeData_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_VolumeData_struct_t FripuckProtocol_Sensors_VolumeData_vec_at(FripuckProtocol_Sensors_VolumeData_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_VolumeData__size(void) { return 10; }
static inline size_t FripuckProtocol_Sensors_VolumeData_vec_len(FripuckProtocol_Sensors_VolumeData_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_VolumeData)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VolumeData, m0, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VolumeData, m1, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VolumeData, m2, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VolumeData, m3, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VolumeData, timestamp_offset, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_AudioMetadata {
    alignas(2) uint16_t offset;
    alignas(2) uint16_t length;
    alignas(2) uint16_t sample_count;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_AudioMetadata_t) == 8, "struct size mismatch");

static inline const FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata__const_ptr_add(const FripuckProtocol_Sensors_AudioMetadata_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata__ptr_add(FripuckProtocol_Sensors_AudioMetadata_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_AudioMetadata_struct_t FripuckProtocol_Sensors_AudioMetadata_vec_at(FripuckProtocol_Sensors_AudioMetadata_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_AudioMetadata__size(void) { return 8; }
static inline size_t FripuckProtocol_Sensors_AudioMetadata_vec_len(FripuckProtocol_Sensors_AudioMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_AudioMetadata)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_AudioMetadata, offset, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_AudioMetadata, length, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_AudioMetadata, sample_count, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_AudioMetadata, timestamp_offset, flatbuffers_uint16, uint16_t)

struct FripuckProtocol_Sensors_VideoMetadata {
    alignas(4) uint32_t offset;
    alignas(4) uint32_t length;
    alignas(2) uint16_t frame_id;
    alignas(1) uint8_t fragment_index;
    alignas(1) uint8_t total_fragments;
    alignas(2) uint16_t flags;
    alignas(2) uint16_t timestamp_offset;
};
static_assert(sizeof(FripuckProtocol_Sensors_VideoMetadata_t) == 16, "struct size mismatch");

static inline const FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata__const_ptr_add(const FripuckProtocol_Sensors_VideoMetadata_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata__ptr_add(FripuckProtocol_Sensors_VideoMetadata_t *p, size_t i) { return p + i; }
static inline FripuckProtocol_Sensors_VideoMetadata_struct_t FripuckProtocol_Sensors_VideoMetadata_vec_at(FripuckProtocol_Sensors_VideoMetadata_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t FripuckProtocol_Sensors_VideoMetadata__size(void) { return 16; }
static inline size_t FripuckProtocol_Sensors_VideoMetadata_vec_len(FripuckProtocol_Sensors_VideoMetadata_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(FripuckProtocol_Sensors_VideoMetadata)

__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, offset, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, length, flatbuffers_uint32, uint32_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, frame_id, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, fragment_index, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, total_fragments, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, flags, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(FripuckProtocol_Sensors_VideoMetadata, timestamp_offset, flatbuffers_uint16, uint16_t)


struct FripuckProtocol_Sensors_SensorBatch_table { uint8_t unused__; };

static inline size_t FripuckProtocol_Sensors_SensorBatch_vec_len(FripuckProtocol_Sensors_SensorBatch_vec_t vec)
__flatbuffers_vec_len(vec)
static inline FripuckProtocol_Sensors_SensorBatch_table_t FripuckProtocol_Sensors_SensorBatch_vec_at(FripuckProtocol_Sensors_SensorBatch_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(FripuckProtocol_Sensors_SensorBatch_table_t, vec, i, 0)
__flatbuffers_table_as_root(FripuckProtocol_Sensors_SensorBatch)

__flatbuffers_define_scalar_field(0, FripuckProtocol_Sensors_SensorBatch, base_timestamp, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(1, FripuckProtocol_Sensors_SensorBatch, proximity, FripuckProtocol_Sensors_ProximityData_vec_t, 0)
__flatbuffers_define_vector_field(2, FripuckProtocol_Sensors_SensorBatch, tof, FripuckProtocol_Sensors_TofData_vec_t, 0)
__flatbuffers_define_vector_field(3, FripuckProtocol_Sensors_SensorBatch, battery, FripuckProtocol_Sensors_BatteryData_vec_t, 0)
__flatbuffers_define_vector_field(4, FripuckProtocol_Sensors_SensorBatch, encoder, FripuckProtocol_Sensors_EncoderData_vec_t, 0)
__flatbuffers_define_vector_field(5, FripuckProtocol_Sensors_SensorBatch, imu, FripuckProtocol_Sensors_ImuData_vec_t, 0)
__flatbuffers_define_vector_field(6, FripuckProtocol_Sensors_SensorBatch, audio_blob, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(7, FripuckProtocol_Sensors_SensorBatch, audio_metadata, FripuckProtocol_Sensors_AudioMetadata_vec_t, 0)
__flatbuffers_define_vector_field(8, FripuckProtocol_Sensors_SensorBatch, video_blob, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(9, FripuckProtocol_Sensors_SensorBatch, video_metadata, FripuckProtocol_Sensors_VideoMetadata_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* SENSORS_READER_H */
