#ifndef SENSORS_BUILDER_H
#define SENSORS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef SENSORS_READER_H
#include "sensors_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "SENS"
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __FripuckProtocol_Sensors_Uint16Array8_formal_args ,\
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,\
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7
#define __FripuckProtocol_Sensors_Uint16Array8_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_assign(FripuckProtocol_Sensors_Uint16Array8_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ p->a0 = v0; p->a1 = v1; p->a2 = v2; p->a3 = v3;
  p->a4 = v4; p->a5 = v5; p->a6 = v6; p->a7 = v7;
  return p; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_copy(FripuckProtocol_Sensors_Uint16Array8_t *p, const FripuckProtocol_Sensors_Uint16Array8_t *p2)
{ p->a0 = p2->a0; p->a1 = p2->a1; p->a2 = p2->a2; p->a3 = p2->a3;
  p->a4 = p2->a4; p->a5 = p2->a5; p->a6 = p2->a6; p->a7 = p2->a7;
  return p; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_assign_to_pe(FripuckProtocol_Sensors_Uint16Array8_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ flatbuffers_uint16_assign_to_pe(&p->a0, v0); flatbuffers_uint16_assign_to_pe(&p->a1, v1); flatbuffers_uint16_assign_to_pe(&p->a2, v2); flatbuffers_uint16_assign_to_pe(&p->a3, v3);
  flatbuffers_uint16_assign_to_pe(&p->a4, v4); flatbuffers_uint16_assign_to_pe(&p->a5, v5); flatbuffers_uint16_assign_to_pe(&p->a6, v6); flatbuffers_uint16_assign_to_pe(&p->a7, v7);
  return p; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_copy_to_pe(FripuckProtocol_Sensors_Uint16Array8_t *p, const FripuckProtocol_Sensors_Uint16Array8_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->a0, &p2->a0); flatbuffers_uint16_copy_to_pe(&p->a1, &p2->a1); flatbuffers_uint16_copy_to_pe(&p->a2, &p2->a2); flatbuffers_uint16_copy_to_pe(&p->a3, &p2->a3);
  flatbuffers_uint16_copy_to_pe(&p->a4, &p2->a4); flatbuffers_uint16_copy_to_pe(&p->a5, &p2->a5); flatbuffers_uint16_copy_to_pe(&p->a6, &p2->a6); flatbuffers_uint16_copy_to_pe(&p->a7, &p2->a7);
  return p; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_assign_from_pe(FripuckProtocol_Sensors_Uint16Array8_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7)
{ flatbuffers_uint16_assign_from_pe(&p->a0, v0); flatbuffers_uint16_assign_from_pe(&p->a1, v1); flatbuffers_uint16_assign_from_pe(&p->a2, v2); flatbuffers_uint16_assign_from_pe(&p->a3, v3);
  flatbuffers_uint16_assign_from_pe(&p->a4, v4); flatbuffers_uint16_assign_from_pe(&p->a5, v5); flatbuffers_uint16_assign_from_pe(&p->a6, v6); flatbuffers_uint16_assign_from_pe(&p->a7, v7);
  return p; }
static inline FripuckProtocol_Sensors_Uint16Array8_t *FripuckProtocol_Sensors_Uint16Array8_copy_from_pe(FripuckProtocol_Sensors_Uint16Array8_t *p, const FripuckProtocol_Sensors_Uint16Array8_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->a0, &p2->a0); flatbuffers_uint16_copy_from_pe(&p->a1, &p2->a1); flatbuffers_uint16_copy_from_pe(&p->a2, &p2->a2); flatbuffers_uint16_copy_from_pe(&p->a3, &p2->a3);
  flatbuffers_uint16_copy_from_pe(&p->a4, &p2->a4); flatbuffers_uint16_copy_from_pe(&p->a5, &p2->a5); flatbuffers_uint16_copy_from_pe(&p->a6, &p2->a6); flatbuffers_uint16_copy_from_pe(&p->a7, &p2->a7);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_Uint16Array8, 16, 2, FripuckProtocol_Sensors_Uint16Array8_file_identifier, FripuckProtocol_Sensors_Uint16Array8_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_Uint16Array8, FripuckProtocol_Sensors_Uint16Array8_t)

#define __FripuckProtocol_Sensors_ProximityData_formal_args ,\
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,\
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7,\
  uint16_t v8, uint16_t v9, uint16_t v10, uint16_t v11,\
  uint16_t v12, uint16_t v13, uint16_t v14, uint16_t v15, uint16_t v16, uint16_t v17
#define __FripuckProtocol_Sensors_ProximityData_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15, v16, v17
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_assign(FripuckProtocol_Sensors_ProximityData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7,
  uint16_t v8, uint16_t v9, uint16_t v10, uint16_t v11,
  uint16_t v12, uint16_t v13, uint16_t v14, uint16_t v15, uint16_t v16, uint16_t v17)
{ FripuckProtocol_Sensors_Uint16Array8_assign(&p->proximity,
  v0, v1, v2, v3,
  v4, v5, v6, v7);
  FripuckProtocol_Sensors_Uint16Array8_assign(&p->ambient_light,
  v8, v9, v10, v11,
  v12, v13, v14, v15);
  p->timestamp_offset = v16; p->padding = v17;
  return p; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_copy(FripuckProtocol_Sensors_ProximityData_t *p, const FripuckProtocol_Sensors_ProximityData_t *p2)
{ FripuckProtocol_Sensors_Uint16Array8_copy(&p->proximity, &p2->proximity); FripuckProtocol_Sensors_Uint16Array8_copy(&p->ambient_light, &p2->ambient_light); p->timestamp_offset = p2->timestamp_offset; p->padding = p2->padding;
  return p; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_assign_to_pe(FripuckProtocol_Sensors_ProximityData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7,
  uint16_t v8, uint16_t v9, uint16_t v10, uint16_t v11,
  uint16_t v12, uint16_t v13, uint16_t v14, uint16_t v15, uint16_t v16, uint16_t v17)
{ FripuckProtocol_Sensors_Uint16Array8_assign_to_pe(&p->proximity,
  v0, v1, v2, v3,
  v4, v5, v6, v7);
  FripuckProtocol_Sensors_Uint16Array8_assign_to_pe(&p->ambient_light,
  v8, v9, v10, v11,
  v12, v13, v14, v15);
  flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v16); flatbuffers_uint16_assign_to_pe(&p->padding, v17);
  return p; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_copy_to_pe(FripuckProtocol_Sensors_ProximityData_t *p, const FripuckProtocol_Sensors_ProximityData_t *p2)
{ FripuckProtocol_Sensors_Uint16Array8_copy_to_pe(&p->proximity, &p2->proximity); FripuckProtocol_Sensors_Uint16Array8_copy_to_pe(&p->ambient_light, &p2->ambient_light); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset); flatbuffers_uint16_copy_to_pe(&p->padding, &p2->padding);
  return p; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_assign_from_pe(FripuckProtocol_Sensors_ProximityData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3,
  uint16_t v4, uint16_t v5, uint16_t v6, uint16_t v7,
  uint16_t v8, uint16_t v9, uint16_t v10, uint16_t v11,
  uint16_t v12, uint16_t v13, uint16_t v14, uint16_t v15, uint16_t v16, uint16_t v17)
{ FripuckProtocol_Sensors_Uint16Array8_assign_from_pe(&p->proximity,
  v0, v1, v2, v3,
  v4, v5, v6, v7);
  FripuckProtocol_Sensors_Uint16Array8_assign_from_pe(&p->ambient_light,
  v8, v9, v10, v11,
  v12, v13, v14, v15);
  flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v16); flatbuffers_uint16_assign_from_pe(&p->padding, v17);
  return p; }
static inline FripuckProtocol_Sensors_ProximityData_t *FripuckProtocol_Sensors_ProximityData_copy_from_pe(FripuckProtocol_Sensors_ProximityData_t *p, const FripuckProtocol_Sensors_ProximityData_t *p2)
{ FripuckProtocol_Sensors_Uint16Array8_copy_from_pe(&p->proximity, &p2->proximity); FripuckProtocol_Sensors_Uint16Array8_copy_from_pe(&p->ambient_light, &p2->ambient_light); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset); flatbuffers_uint16_copy_from_pe(&p->padding, &p2->padding);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_ProximityData, 36, 2, FripuckProtocol_Sensors_ProximityData_file_identifier, FripuckProtocol_Sensors_ProximityData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_ProximityData, FripuckProtocol_Sensors_ProximityData_t)

#define __FripuckProtocol_Sensors_TofData_formal_args , uint16_t v0, uint16_t v1
#define __FripuckProtocol_Sensors_TofData_call_args , v0, v1
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_assign(FripuckProtocol_Sensors_TofData_t *p, uint16_t v0, uint16_t v1)
{ p->distance = v0; p->timestamp_offset = v1;
  return p; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_copy(FripuckProtocol_Sensors_TofData_t *p, const FripuckProtocol_Sensors_TofData_t *p2)
{ p->distance = p2->distance; p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_assign_to_pe(FripuckProtocol_Sensors_TofData_t *p, uint16_t v0, uint16_t v1)
{ flatbuffers_uint16_assign_to_pe(&p->distance, v0); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v1);
  return p; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_copy_to_pe(FripuckProtocol_Sensors_TofData_t *p, const FripuckProtocol_Sensors_TofData_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->distance, &p2->distance); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_assign_from_pe(FripuckProtocol_Sensors_TofData_t *p, uint16_t v0, uint16_t v1)
{ flatbuffers_uint16_assign_from_pe(&p->distance, v0); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v1);
  return p; }
static inline FripuckProtocol_Sensors_TofData_t *FripuckProtocol_Sensors_TofData_copy_from_pe(FripuckProtocol_Sensors_TofData_t *p, const FripuckProtocol_Sensors_TofData_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->distance, &p2->distance); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_TofData, 4, 2, FripuckProtocol_Sensors_TofData_file_identifier, FripuckProtocol_Sensors_TofData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_TofData, FripuckProtocol_Sensors_TofData_t)

#define __FripuckProtocol_Sensors_BatteryData_formal_args , uint16_t v0, uint16_t v1
#define __FripuckProtocol_Sensors_BatteryData_call_args , v0, v1
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_assign(FripuckProtocol_Sensors_BatteryData_t *p, uint16_t v0, uint16_t v1)
{ p->millivolts = v0; p->timestamp_offset = v1;
  return p; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_copy(FripuckProtocol_Sensors_BatteryData_t *p, const FripuckProtocol_Sensors_BatteryData_t *p2)
{ p->millivolts = p2->millivolts; p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_assign_to_pe(FripuckProtocol_Sensors_BatteryData_t *p, uint16_t v0, uint16_t v1)
{ flatbuffers_uint16_assign_to_pe(&p->millivolts, v0); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v1);
  return p; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_copy_to_pe(FripuckProtocol_Sensors_BatteryData_t *p, const FripuckProtocol_Sensors_BatteryData_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->millivolts, &p2->millivolts); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_assign_from_pe(FripuckProtocol_Sensors_BatteryData_t *p, uint16_t v0, uint16_t v1)
{ flatbuffers_uint16_assign_from_pe(&p->millivolts, v0); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v1);
  return p; }
static inline FripuckProtocol_Sensors_BatteryData_t *FripuckProtocol_Sensors_BatteryData_copy_from_pe(FripuckProtocol_Sensors_BatteryData_t *p, const FripuckProtocol_Sensors_BatteryData_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->millivolts, &p2->millivolts); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_BatteryData, 4, 2, FripuckProtocol_Sensors_BatteryData_file_identifier, FripuckProtocol_Sensors_BatteryData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_BatteryData, FripuckProtocol_Sensors_BatteryData_t)

#define __FripuckProtocol_Sensors_EncoderData_formal_args , int32_t v0, int32_t v1, uint16_t v2, uint16_t v3
#define __FripuckProtocol_Sensors_EncoderData_call_args , v0, v1, v2, v3
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_assign(FripuckProtocol_Sensors_EncoderData_t *p, int32_t v0, int32_t v1, uint16_t v2, uint16_t v3)
{ p->left_steps = v0; p->right_steps = v1; p->timestamp_offset = v2; p->padding = v3;
  return p; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_copy(FripuckProtocol_Sensors_EncoderData_t *p, const FripuckProtocol_Sensors_EncoderData_t *p2)
{ p->left_steps = p2->left_steps; p->right_steps = p2->right_steps; p->timestamp_offset = p2->timestamp_offset; p->padding = p2->padding;
  return p; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_assign_to_pe(FripuckProtocol_Sensors_EncoderData_t *p, int32_t v0, int32_t v1, uint16_t v2, uint16_t v3)
{ flatbuffers_int32_assign_to_pe(&p->left_steps, v0); flatbuffers_int32_assign_to_pe(&p->right_steps, v1); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v2); flatbuffers_uint16_assign_to_pe(&p->padding, v3);
  return p; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_copy_to_pe(FripuckProtocol_Sensors_EncoderData_t *p, const FripuckProtocol_Sensors_EncoderData_t *p2)
{ flatbuffers_int32_copy_to_pe(&p->left_steps, &p2->left_steps); flatbuffers_int32_copy_to_pe(&p->right_steps, &p2->right_steps); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset); flatbuffers_uint16_copy_to_pe(&p->padding, &p2->padding);
  return p; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_assign_from_pe(FripuckProtocol_Sensors_EncoderData_t *p, int32_t v0, int32_t v1, uint16_t v2, uint16_t v3)
{ flatbuffers_int32_assign_from_pe(&p->left_steps, v0); flatbuffers_int32_assign_from_pe(&p->right_steps, v1); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v2); flatbuffers_uint16_assign_from_pe(&p->padding, v3);
  return p; }
static inline FripuckProtocol_Sensors_EncoderData_t *FripuckProtocol_Sensors_EncoderData_copy_from_pe(FripuckProtocol_Sensors_EncoderData_t *p, const FripuckProtocol_Sensors_EncoderData_t *p2)
{ flatbuffers_int32_copy_from_pe(&p->left_steps, &p2->left_steps); flatbuffers_int32_copy_from_pe(&p->right_steps, &p2->right_steps); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset); flatbuffers_uint16_copy_from_pe(&p->padding, &p2->padding);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_EncoderData, 12, 4, FripuckProtocol_Sensors_EncoderData_file_identifier, FripuckProtocol_Sensors_EncoderData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_EncoderData, FripuckProtocol_Sensors_EncoderData_t)

#define __FripuckProtocol_Sensors_Vector3D_formal_args , int16_t v0, int16_t v1, int16_t v2
#define __FripuckProtocol_Sensors_Vector3D_call_args , v0, v1, v2
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_assign(FripuckProtocol_Sensors_Vector3D_t *p, int16_t v0, int16_t v1, int16_t v2)
{ p->x = v0; p->y = v1; p->z = v2;
  return p; }
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_copy(FripuckProtocol_Sensors_Vector3D_t *p, const FripuckProtocol_Sensors_Vector3D_t *p2)
{ p->x = p2->x; p->y = p2->y; p->z = p2->z;
  return p; }
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_assign_to_pe(FripuckProtocol_Sensors_Vector3D_t *p, int16_t v0, int16_t v1, int16_t v2)
{ flatbuffers_int16_assign_to_pe(&p->x, v0); flatbuffers_int16_assign_to_pe(&p->y, v1); flatbuffers_int16_assign_to_pe(&p->z, v2);
  return p; }
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_copy_to_pe(FripuckProtocol_Sensors_Vector3D_t *p, const FripuckProtocol_Sensors_Vector3D_t *p2)
{ flatbuffers_int16_copy_to_pe(&p->x, &p2->x); flatbuffers_int16_copy_to_pe(&p->y, &p2->y); flatbuffers_int16_copy_to_pe(&p->z, &p2->z);
  return p; }
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_assign_from_pe(FripuckProtocol_Sensors_Vector3D_t *p, int16_t v0, int16_t v1, int16_t v2)
{ flatbuffers_int16_assign_from_pe(&p->x, v0); flatbuffers_int16_assign_from_pe(&p->y, v1); flatbuffers_int16_assign_from_pe(&p->z, v2);
  return p; }
static inline FripuckProtocol_Sensors_Vector3D_t *FripuckProtocol_Sensors_Vector3D_copy_from_pe(FripuckProtocol_Sensors_Vector3D_t *p, const FripuckProtocol_Sensors_Vector3D_t *p2)
{ flatbuffers_int16_copy_from_pe(&p->x, &p2->x); flatbuffers_int16_copy_from_pe(&p->y, &p2->y); flatbuffers_int16_copy_from_pe(&p->z, &p2->z);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_Vector3D, 6, 2, FripuckProtocol_Sensors_Vector3D_file_identifier, FripuckProtocol_Sensors_Vector3D_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_Vector3D, FripuckProtocol_Sensors_Vector3D_t)

#define __FripuckProtocol_Sensors_ImuData_formal_args ,\
  int16_t v0, int16_t v1, int16_t v2, int16_t v3,\
  int16_t v4, int16_t v5, int16_t v6, int16_t v7, int16_t v8, uint16_t v9
#define __FripuckProtocol_Sensors_ImuData_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8, v9
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_assign(FripuckProtocol_Sensors_ImuData_t *p,
  int16_t v0, int16_t v1, int16_t v2, int16_t v3,
  int16_t v4, int16_t v5, int16_t v6, int16_t v7, int16_t v8, uint16_t v9)
{ FripuckProtocol_Sensors_Vector3D_assign(&p->accelerometer,
  v0, v1, v2); FripuckProtocol_Sensors_Vector3D_assign(&p->gyroscope,
  v3, v4, v5); FripuckProtocol_Sensors_Vector3D_assign(&p->magnetometer,
  v6, v7, v8); p->timestamp_offset = v9;
  return p; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_copy(FripuckProtocol_Sensors_ImuData_t *p, const FripuckProtocol_Sensors_ImuData_t *p2)
{ FripuckProtocol_Sensors_Vector3D_copy(&p->accelerometer, &p2->accelerometer); FripuckProtocol_Sensors_Vector3D_copy(&p->gyroscope, &p2->gyroscope); FripuckProtocol_Sensors_Vector3D_copy(&p->magnetometer, &p2->magnetometer); p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_assign_to_pe(FripuckProtocol_Sensors_ImuData_t *p,
  int16_t v0, int16_t v1, int16_t v2, int16_t v3,
  int16_t v4, int16_t v5, int16_t v6, int16_t v7, int16_t v8, uint16_t v9)
{ FripuckProtocol_Sensors_Vector3D_assign_to_pe(&p->accelerometer,
  v0, v1, v2); FripuckProtocol_Sensors_Vector3D_assign_to_pe(&p->gyroscope,
  v3, v4, v5); FripuckProtocol_Sensors_Vector3D_assign_to_pe(&p->magnetometer,
  v6, v7, v8); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v9);
  return p; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_copy_to_pe(FripuckProtocol_Sensors_ImuData_t *p, const FripuckProtocol_Sensors_ImuData_t *p2)
{ FripuckProtocol_Sensors_Vector3D_copy_to_pe(&p->accelerometer, &p2->accelerometer); FripuckProtocol_Sensors_Vector3D_copy_to_pe(&p->gyroscope, &p2->gyroscope); FripuckProtocol_Sensors_Vector3D_copy_to_pe(&p->magnetometer, &p2->magnetometer); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_assign_from_pe(FripuckProtocol_Sensors_ImuData_t *p,
  int16_t v0, int16_t v1, int16_t v2, int16_t v3,
  int16_t v4, int16_t v5, int16_t v6, int16_t v7, int16_t v8, uint16_t v9)
{ FripuckProtocol_Sensors_Vector3D_assign_from_pe(&p->accelerometer,
  v0, v1, v2); FripuckProtocol_Sensors_Vector3D_assign_from_pe(&p->gyroscope,
  v3, v4, v5); FripuckProtocol_Sensors_Vector3D_assign_from_pe(&p->magnetometer,
  v6, v7, v8); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v9);
  return p; }
static inline FripuckProtocol_Sensors_ImuData_t *FripuckProtocol_Sensors_ImuData_copy_from_pe(FripuckProtocol_Sensors_ImuData_t *p, const FripuckProtocol_Sensors_ImuData_t *p2)
{ FripuckProtocol_Sensors_Vector3D_copy_from_pe(&p->accelerometer, &p2->accelerometer); FripuckProtocol_Sensors_Vector3D_copy_from_pe(&p->gyroscope, &p2->gyroscope); FripuckProtocol_Sensors_Vector3D_copy_from_pe(&p->magnetometer, &p2->magnetometer); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_ImuData, 20, 2, FripuckProtocol_Sensors_ImuData_file_identifier, FripuckProtocol_Sensors_ImuData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_ImuData, FripuckProtocol_Sensors_ImuData_t)

#define __FripuckProtocol_Sensors_VolumeData_formal_args ,\
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3, uint16_t v4
#define __FripuckProtocol_Sensors_VolumeData_call_args ,\
  v0, v1, v2, v3, v4
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_assign(FripuckProtocol_Sensors_VolumeData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3, uint16_t v4)
{ p->m0 = v0; p->m1 = v1; p->m2 = v2; p->m3 = v3;
  p->timestamp_offset = v4;
  return p; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_copy(FripuckProtocol_Sensors_VolumeData_t *p, const FripuckProtocol_Sensors_VolumeData_t *p2)
{ p->m0 = p2->m0; p->m1 = p2->m1; p->m2 = p2->m2; p->m3 = p2->m3;
  p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_assign_to_pe(FripuckProtocol_Sensors_VolumeData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3, uint16_t v4)
{ flatbuffers_uint16_assign_to_pe(&p->m0, v0); flatbuffers_uint16_assign_to_pe(&p->m1, v1); flatbuffers_uint16_assign_to_pe(&p->m2, v2); flatbuffers_uint16_assign_to_pe(&p->m3, v3);
  flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v4);
  return p; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_copy_to_pe(FripuckProtocol_Sensors_VolumeData_t *p, const FripuckProtocol_Sensors_VolumeData_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->m0, &p2->m0); flatbuffers_uint16_copy_to_pe(&p->m1, &p2->m1); flatbuffers_uint16_copy_to_pe(&p->m2, &p2->m2); flatbuffers_uint16_copy_to_pe(&p->m3, &p2->m3);
  flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_assign_from_pe(FripuckProtocol_Sensors_VolumeData_t *p,
  uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3, uint16_t v4)
{ flatbuffers_uint16_assign_from_pe(&p->m0, v0); flatbuffers_uint16_assign_from_pe(&p->m1, v1); flatbuffers_uint16_assign_from_pe(&p->m2, v2); flatbuffers_uint16_assign_from_pe(&p->m3, v3);
  flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v4);
  return p; }
static inline FripuckProtocol_Sensors_VolumeData_t *FripuckProtocol_Sensors_VolumeData_copy_from_pe(FripuckProtocol_Sensors_VolumeData_t *p, const FripuckProtocol_Sensors_VolumeData_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->m0, &p2->m0); flatbuffers_uint16_copy_from_pe(&p->m1, &p2->m1); flatbuffers_uint16_copy_from_pe(&p->m2, &p2->m2); flatbuffers_uint16_copy_from_pe(&p->m3, &p2->m3);
  flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_VolumeData, 10, 2, FripuckProtocol_Sensors_VolumeData_file_identifier, FripuckProtocol_Sensors_VolumeData_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_VolumeData, FripuckProtocol_Sensors_VolumeData_t)

#define __FripuckProtocol_Sensors_AudioMetadata_formal_args , uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3
#define __FripuckProtocol_Sensors_AudioMetadata_call_args , v0, v1, v2, v3
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_assign(FripuckProtocol_Sensors_AudioMetadata_t *p, uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3)
{ p->offset = v0; p->length = v1; p->sample_count = v2; p->timestamp_offset = v3;
  return p; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_copy(FripuckProtocol_Sensors_AudioMetadata_t *p, const FripuckProtocol_Sensors_AudioMetadata_t *p2)
{ p->offset = p2->offset; p->length = p2->length; p->sample_count = p2->sample_count; p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_assign_to_pe(FripuckProtocol_Sensors_AudioMetadata_t *p, uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3)
{ flatbuffers_uint16_assign_to_pe(&p->offset, v0); flatbuffers_uint16_assign_to_pe(&p->length, v1); flatbuffers_uint16_assign_to_pe(&p->sample_count, v2); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v3);
  return p; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_copy_to_pe(FripuckProtocol_Sensors_AudioMetadata_t *p, const FripuckProtocol_Sensors_AudioMetadata_t *p2)
{ flatbuffers_uint16_copy_to_pe(&p->offset, &p2->offset); flatbuffers_uint16_copy_to_pe(&p->length, &p2->length); flatbuffers_uint16_copy_to_pe(&p->sample_count, &p2->sample_count); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_assign_from_pe(FripuckProtocol_Sensors_AudioMetadata_t *p, uint16_t v0, uint16_t v1, uint16_t v2, uint16_t v3)
{ flatbuffers_uint16_assign_from_pe(&p->offset, v0); flatbuffers_uint16_assign_from_pe(&p->length, v1); flatbuffers_uint16_assign_from_pe(&p->sample_count, v2); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v3);
  return p; }
static inline FripuckProtocol_Sensors_AudioMetadata_t *FripuckProtocol_Sensors_AudioMetadata_copy_from_pe(FripuckProtocol_Sensors_AudioMetadata_t *p, const FripuckProtocol_Sensors_AudioMetadata_t *p2)
{ flatbuffers_uint16_copy_from_pe(&p->offset, &p2->offset); flatbuffers_uint16_copy_from_pe(&p->length, &p2->length); flatbuffers_uint16_copy_from_pe(&p->sample_count, &p2->sample_count); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_AudioMetadata, 8, 2, FripuckProtocol_Sensors_AudioMetadata_file_identifier, FripuckProtocol_Sensors_AudioMetadata_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_AudioMetadata, FripuckProtocol_Sensors_AudioMetadata_t)

#define __FripuckProtocol_Sensors_VideoMetadata_formal_args ,\
  uint32_t v0, uint32_t v1, uint16_t v2, uint8_t v3,\
  uint8_t v4, uint16_t v5, uint16_t v6
#define __FripuckProtocol_Sensors_VideoMetadata_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_assign(FripuckProtocol_Sensors_VideoMetadata_t *p,
  uint32_t v0, uint32_t v1, uint16_t v2, uint8_t v3,
  uint8_t v4, uint16_t v5, uint16_t v6)
{ p->offset = v0; p->length = v1; p->frame_id = v2; p->fragment_index = v3;
  p->total_fragments = v4; p->flags = v5; p->timestamp_offset = v6;
  return p; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_copy(FripuckProtocol_Sensors_VideoMetadata_t *p, const FripuckProtocol_Sensors_VideoMetadata_t *p2)
{ p->offset = p2->offset; p->length = p2->length; p->frame_id = p2->frame_id; p->fragment_index = p2->fragment_index;
  p->total_fragments = p2->total_fragments; p->flags = p2->flags; p->timestamp_offset = p2->timestamp_offset;
  return p; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_assign_to_pe(FripuckProtocol_Sensors_VideoMetadata_t *p,
  uint32_t v0, uint32_t v1, uint16_t v2, uint8_t v3,
  uint8_t v4, uint16_t v5, uint16_t v6)
{ flatbuffers_uint32_assign_to_pe(&p->offset, v0); flatbuffers_uint32_assign_to_pe(&p->length, v1); flatbuffers_uint16_assign_to_pe(&p->frame_id, v2); p->fragment_index = v3;
  p->total_fragments = v4; flatbuffers_uint16_assign_to_pe(&p->flags, v5); flatbuffers_uint16_assign_to_pe(&p->timestamp_offset, v6);
  return p; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_copy_to_pe(FripuckProtocol_Sensors_VideoMetadata_t *p, const FripuckProtocol_Sensors_VideoMetadata_t *p2)
{ flatbuffers_uint32_copy_to_pe(&p->offset, &p2->offset); flatbuffers_uint32_copy_to_pe(&p->length, &p2->length); flatbuffers_uint16_copy_to_pe(&p->frame_id, &p2->frame_id); p->fragment_index = p2->fragment_index;
  p->total_fragments = p2->total_fragments; flatbuffers_uint16_copy_to_pe(&p->flags, &p2->flags); flatbuffers_uint16_copy_to_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_assign_from_pe(FripuckProtocol_Sensors_VideoMetadata_t *p,
  uint32_t v0, uint32_t v1, uint16_t v2, uint8_t v3,
  uint8_t v4, uint16_t v5, uint16_t v6)
{ flatbuffers_uint32_assign_from_pe(&p->offset, v0); flatbuffers_uint32_assign_from_pe(&p->length, v1); flatbuffers_uint16_assign_from_pe(&p->frame_id, v2); p->fragment_index = v3;
  p->total_fragments = v4; flatbuffers_uint16_assign_from_pe(&p->flags, v5); flatbuffers_uint16_assign_from_pe(&p->timestamp_offset, v6);
  return p; }
static inline FripuckProtocol_Sensors_VideoMetadata_t *FripuckProtocol_Sensors_VideoMetadata_copy_from_pe(FripuckProtocol_Sensors_VideoMetadata_t *p, const FripuckProtocol_Sensors_VideoMetadata_t *p2)
{ flatbuffers_uint32_copy_from_pe(&p->offset, &p2->offset); flatbuffers_uint32_copy_from_pe(&p->length, &p2->length); flatbuffers_uint16_copy_from_pe(&p->frame_id, &p2->frame_id); p->fragment_index = p2->fragment_index;
  p->total_fragments = p2->total_fragments; flatbuffers_uint16_copy_from_pe(&p->flags, &p2->flags); flatbuffers_uint16_copy_from_pe(&p->timestamp_offset, &p2->timestamp_offset);
  return p; }
__flatbuffers_build_struct(flatbuffers_, FripuckProtocol_Sensors_VideoMetadata, 16, 4, FripuckProtocol_Sensors_VideoMetadata_file_identifier, FripuckProtocol_Sensors_VideoMetadata_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, FripuckProtocol_Sensors_VideoMetadata, FripuckProtocol_Sensors_VideoMetadata_t)

static const flatbuffers_voffset_t __FripuckProtocol_Sensors_SensorBatch_required[] = { 0 };
typedef flatbuffers_ref_t FripuckProtocol_Sensors_SensorBatch_ref_t;
static FripuckProtocol_Sensors_SensorBatch_ref_t FripuckProtocol_Sensors_SensorBatch_clone(flatbuffers_builder_t *B, FripuckProtocol_Sensors_SensorBatch_table_t t);
__flatbuffers_build_table(flatbuffers_, FripuckProtocol_Sensors_SensorBatch, 10)

#define __FripuckProtocol_Sensors_SensorBatch_formal_args ,\
  uint64_t v0, FripuckProtocol_Sensors_ProximityData_vec_ref_t v1, FripuckProtocol_Sensors_TofData_vec_ref_t v2, FripuckProtocol_Sensors_BatteryData_vec_ref_t v3,\
  FripuckProtocol_Sensors_EncoderData_vec_ref_t v4, FripuckProtocol_Sensors_ImuData_vec_ref_t v5, flatbuffers_uint8_vec_ref_t v6, FripuckProtocol_Sensors_AudioMetadata_vec_ref_t v7, flatbuffers_uint8_vec_ref_t v8, FripuckProtocol_Sensors_VideoMetadata_vec_ref_t v9
#define __FripuckProtocol_Sensors_SensorBatch_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8, v9
static inline FripuckProtocol_Sensors_SensorBatch_ref_t FripuckProtocol_Sensors_SensorBatch_create(flatbuffers_builder_t *B __FripuckProtocol_Sensors_SensorBatch_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, FripuckProtocol_Sensors_SensorBatch, FripuckProtocol_Sensors_SensorBatch_file_identifier, FripuckProtocol_Sensors_SensorBatch_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_base_timestamp, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(1, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_proximity, FripuckProtocol_Sensors_ProximityData, FripuckProtocol_Sensors_ProximityData_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(2, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_tof, FripuckProtocol_Sensors_TofData, FripuckProtocol_Sensors_TofData_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(3, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_battery, FripuckProtocol_Sensors_BatteryData, FripuckProtocol_Sensors_BatteryData_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(4, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_encoder, FripuckProtocol_Sensors_EncoderData, FripuckProtocol_Sensors_EncoderData_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(5, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_imu, FripuckProtocol_Sensors_ImuData, FripuckProtocol_Sensors_ImuData_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(6, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_audio_blob, flatbuffers_uint8, uint8_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(7, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_audio_metadata, FripuckProtocol_Sensors_AudioMetadata, FripuckProtocol_Sensors_AudioMetadata_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(8, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_video_blob, flatbuffers_uint8, uint8_t, FripuckProtocol_Sensors_SensorBatch)
__flatbuffers_build_vector_field(9, flatbuffers_, FripuckProtocol_Sensors_SensorBatch_video_metadata, FripuckProtocol_Sensors_VideoMetadata, FripuckProtocol_Sensors_VideoMetadata_t, FripuckProtocol_Sensors_SensorBatch)

static inline FripuckProtocol_Sensors_SensorBatch_ref_t FripuckProtocol_Sensors_SensorBatch_create(flatbuffers_builder_t *B __FripuckProtocol_Sensors_SensorBatch_formal_args)
{
    if (FripuckProtocol_Sensors_SensorBatch_start(B)
        || FripuckProtocol_Sensors_SensorBatch_base_timestamp_add(B, v0)
        || FripuckProtocol_Sensors_SensorBatch_proximity_add(B, v1)
        || FripuckProtocol_Sensors_SensorBatch_tof_add(B, v2)
        || FripuckProtocol_Sensors_SensorBatch_battery_add(B, v3)
        || FripuckProtocol_Sensors_SensorBatch_encoder_add(B, v4)
        || FripuckProtocol_Sensors_SensorBatch_imu_add(B, v5)
        || FripuckProtocol_Sensors_SensorBatch_audio_blob_add(B, v6)
        || FripuckProtocol_Sensors_SensorBatch_audio_metadata_add(B, v7)
        || FripuckProtocol_Sensors_SensorBatch_video_blob_add(B, v8)
        || FripuckProtocol_Sensors_SensorBatch_video_metadata_add(B, v9)) {
        return 0;
    }
    return FripuckProtocol_Sensors_SensorBatch_end(B);
}

static FripuckProtocol_Sensors_SensorBatch_ref_t FripuckProtocol_Sensors_SensorBatch_clone(flatbuffers_builder_t *B, FripuckProtocol_Sensors_SensorBatch_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (FripuckProtocol_Sensors_SensorBatch_start(B)
        || FripuckProtocol_Sensors_SensorBatch_base_timestamp_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_proximity_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_tof_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_battery_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_encoder_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_imu_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_audio_blob_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_audio_metadata_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_video_blob_pick(B, t)
        || FripuckProtocol_Sensors_SensorBatch_video_metadata_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, FripuckProtocol_Sensors_SensorBatch_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SENSORS_BUILDER_H */
