#ifndef SENSORS_VERIFIER_H
#define SENSORS_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef SENSORS_READER_H
#include "sensors_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int FripuckProtocol_Sensors_SensorBatch_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_RingSensorData_identifier, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_RingSensorData_identifier, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_RingSensorData_type_hash, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_RingSensorData_type_hash, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 16, 2);
}

static inline int FripuckProtocol_Sensors_RingSensorData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 16, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_ProximityLightData_identifier, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_ProximityLightData_identifier, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_ProximityLightData_type_hash, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_ProximityLightData_type_hash, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 36, 2);
}

static inline int FripuckProtocol_Sensors_ProximityLightData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 36, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_TofData_identifier, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_TofData_identifier, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_TofData_type_hash, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_TofData_type_hash, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 2);
}

static inline int FripuckProtocol_Sensors_TofData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_BatteryData_identifier, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_BatteryData_identifier, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_BatteryData_type_hash, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_BatteryData_type_hash, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 4, 2);
}

static inline int FripuckProtocol_Sensors_BatteryData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 4, 2);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_EncoderData_identifier, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_EncoderData_identifier, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_EncoderData_type_hash, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_EncoderData_type_hash, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 12, 4);
}

static inline int FripuckProtocol_Sensors_EncoderData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 12, 4);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_Vector3D_identifier, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_Vector3D_identifier, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_Vector3D_type_hash, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_Vector3D_type_hash, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 6, 2);
}

static inline int FripuckProtocol_Sensors_Vector3D_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 6, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_ImuData_identifier, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_ImuData_identifier, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_ImuData_type_hash, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_ImuData_type_hash, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 20, 2);
}

static inline int FripuckProtocol_Sensors_ImuData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 20, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_VolumeData_identifier, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_VolumeData_identifier, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_VolumeData_type_hash, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_VolumeData_type_hash, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 10, 2);
}

static inline int FripuckProtocol_Sensors_VolumeData_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 10, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_AudioMetadata_identifier, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_AudioMetadata_identifier, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_AudioMetadata_type_hash, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_AudioMetadata_type_hash, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 8, 2);
}

static inline int FripuckProtocol_Sensors_AudioMetadata_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 8, 2);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, FripuckProtocol_Sensors_VideoMetadata_identifier, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_VideoMetadata_identifier, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, FripuckProtocol_Sensors_VideoMetadata_type_hash, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_VideoMetadata_type_hash, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 16, 4);
}

static inline int FripuckProtocol_Sensors_VideoMetadata_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 16, 4);
}

static int FripuckProtocol_Sensors_SensorBatch_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* base_timestamp */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 36, 2, INT64_C(119304647)) /* proximity */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 4, 2, INT64_C(1073741823)) /* tof */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 4, 2, INT64_C(1073741823)) /* battery */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 4, 0, 12, 4, INT64_C(357913941)) /* encoder */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 5, 0, 20, 2, INT64_C(214748364)) /* imu */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 6, 0, 1, 1, INT64_C(4294967295)) /* audio_blob */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 7, 0, 8, 2, INT64_C(536870911)) /* audio_metadata */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 8, 0, 1, 1, INT64_C(4294967295)) /* video_blob */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 9, 0, 16, 4, INT64_C(268435455)) /* video_metadata */)) return ret;
    return flatcc_verify_ok;
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Sensors_SensorBatch_identifier, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_SensorBatch_identifier, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, FripuckProtocol_Sensors_SensorBatch_type_identifier, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, FripuckProtocol_Sensors_SensorBatch_type_identifier, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

static inline int FripuckProtocol_Sensors_SensorBatch_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &FripuckProtocol_Sensors_SensorBatch_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SENSORS_VERIFIER_H */
