#ifndef TELEMETRY_READER_H
#define TELEMETRY_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#undef flatbuffers_identifier
#define flatbuffers_identifier "FRI2"
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct Fripuck2_Telemetry_InfoMessage_table *Fripuck2_Telemetry_InfoMessage_table_t;
typedef struct Fripuck2_Telemetry_InfoMessage_table *Fripuck2_Telemetry_InfoMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *Fripuck2_Telemetry_InfoMessage_vec_t;
typedef flatbuffers_uoffset_t *Fripuck2_Telemetry_InfoMessage_mutable_vec_t;
typedef const struct Fripuck2_Telemetry_Entry_table *Fripuck2_Telemetry_Entry_table_t;
typedef struct Fripuck2_Telemetry_Entry_table *Fripuck2_Telemetry_Entry_mutable_table_t;
typedef const flatbuffers_uoffset_t *Fripuck2_Telemetry_Entry_vec_t;
typedef flatbuffers_uoffset_t *Fripuck2_Telemetry_Entry_mutable_vec_t;
typedef const struct Fripuck2_Telemetry_Batch_table *Fripuck2_Telemetry_Batch_table_t;
typedef struct Fripuck2_Telemetry_Batch_table *Fripuck2_Telemetry_Batch_mutable_table_t;
typedef const flatbuffers_uoffset_t *Fripuck2_Telemetry_Batch_vec_t;
typedef flatbuffers_uoffset_t *Fripuck2_Telemetry_Batch_mutable_vec_t;
#ifndef Fripuck2_Telemetry_InfoMessage_file_identifier
#define Fripuck2_Telemetry_InfoMessage_file_identifier "FRI2"
#endif
/* deprecated, use Fripuck2_Telemetry_InfoMessage_file_identifier */
#ifndef Fripuck2_Telemetry_InfoMessage_identifier
#define Fripuck2_Telemetry_InfoMessage_identifier "FRI2"
#endif
#define Fripuck2_Telemetry_InfoMessage_type_hash ((flatbuffers_thash_t)0xd5632fa5)
#define Fripuck2_Telemetry_InfoMessage_type_identifier "\xa5\x2f\x63\xd5"
#ifndef Fripuck2_Telemetry_InfoMessage_file_extension
#define Fripuck2_Telemetry_InfoMessage_file_extension "bin"
#endif
#ifndef Fripuck2_Telemetry_Entry_file_identifier
#define Fripuck2_Telemetry_Entry_file_identifier "FRI2"
#endif
/* deprecated, use Fripuck2_Telemetry_Entry_file_identifier */
#ifndef Fripuck2_Telemetry_Entry_identifier
#define Fripuck2_Telemetry_Entry_identifier "FRI2"
#endif
#define Fripuck2_Telemetry_Entry_type_hash ((flatbuffers_thash_t)0x33b890e)
#define Fripuck2_Telemetry_Entry_type_identifier "\x0e\x89\x3b\x03"
#ifndef Fripuck2_Telemetry_Entry_file_extension
#define Fripuck2_Telemetry_Entry_file_extension "bin"
#endif
#ifndef Fripuck2_Telemetry_Batch_file_identifier
#define Fripuck2_Telemetry_Batch_file_identifier "FRI2"
#endif
/* deprecated, use Fripuck2_Telemetry_Batch_file_identifier */
#ifndef Fripuck2_Telemetry_Batch_identifier
#define Fripuck2_Telemetry_Batch_identifier "FRI2"
#endif
#define Fripuck2_Telemetry_Batch_type_hash ((flatbuffers_thash_t)0x325cb9e2)
#define Fripuck2_Telemetry_Batch_type_identifier "\xe2\xb9\x5c\x32"
#ifndef Fripuck2_Telemetry_Batch_file_extension
#define Fripuck2_Telemetry_Batch_file_extension "bin"
#endif



struct Fripuck2_Telemetry_InfoMessage_table { uint8_t unused__; };

static inline size_t Fripuck2_Telemetry_InfoMessage_vec_len(Fripuck2_Telemetry_InfoMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Fripuck2_Telemetry_InfoMessage_table_t Fripuck2_Telemetry_InfoMessage_vec_at(Fripuck2_Telemetry_InfoMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Fripuck2_Telemetry_InfoMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(Fripuck2_Telemetry_InfoMessage)

__flatbuffers_define_string_field(0, Fripuck2_Telemetry_InfoMessage, text, 0)
typedef uint8_t Fripuck2_Telemetry_Data_union_type_t;
__flatbuffers_define_integer_type(Fripuck2_Telemetry_Data, Fripuck2_Telemetry_Data_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, Fripuck2_Telemetry_Data)
#define Fripuck2_Telemetry_Data_NONE ((Fripuck2_Telemetry_Data_union_type_t)UINT8_C(0))
#define Fripuck2_Telemetry_Data_InfoMessage ((Fripuck2_Telemetry_Data_union_type_t)UINT8_C(1))

static inline const char *Fripuck2_Telemetry_Data_type_name(Fripuck2_Telemetry_Data_union_type_t type)
{
    switch (type) {
    case Fripuck2_Telemetry_Data_NONE: return "NONE";
    case Fripuck2_Telemetry_Data_InfoMessage: return "InfoMessage";
    default: return "";
    }
}

static inline int Fripuck2_Telemetry_Data_is_known_type(Fripuck2_Telemetry_Data_union_type_t type)
{
    switch (type) {
    case Fripuck2_Telemetry_Data_NONE: return 1;
    case Fripuck2_Telemetry_Data_InfoMessage: return 1;
    default: return 0;
    }
}


struct Fripuck2_Telemetry_Entry_table { uint8_t unused__; };

static inline size_t Fripuck2_Telemetry_Entry_vec_len(Fripuck2_Telemetry_Entry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Fripuck2_Telemetry_Entry_table_t Fripuck2_Telemetry_Entry_vec_at(Fripuck2_Telemetry_Entry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Fripuck2_Telemetry_Entry_table_t, vec, i, 0)
__flatbuffers_table_as_root(Fripuck2_Telemetry_Entry)

__flatbuffers_define_scalar_field(0, Fripuck2_Telemetry_Entry, timestamp, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, Fripuck2_Telemetry_Entry, content, Fripuck2_Telemetry_Data, 0)

struct Fripuck2_Telemetry_Batch_table { uint8_t unused__; };

static inline size_t Fripuck2_Telemetry_Batch_vec_len(Fripuck2_Telemetry_Batch_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Fripuck2_Telemetry_Batch_table_t Fripuck2_Telemetry_Batch_vec_at(Fripuck2_Telemetry_Batch_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Fripuck2_Telemetry_Batch_table_t, vec, i, 0)
__flatbuffers_table_as_root(Fripuck2_Telemetry_Batch)

__flatbuffers_define_vector_field(0, Fripuck2_Telemetry_Batch, entries, Fripuck2_Telemetry_Entry_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* TELEMETRY_READER_H */
